### ISSUE TITLE
When a physical server or node goes down, delays occur during failover processing.

### ISSUE THREAD

**Issue by ant103** [lettuce-io/lettuce-core#1272] opened 2020-04-20 09:40 UTC
1. When the physical Redis cluster server itself is down
2, if only the node of the physical Redis cluster server is down
In both cases above,
Retry city for recovery, every 30 seconds by watchdog and every request is blocked and delayed. This symptom persists until the server or node is recovered.

The settings I use are:

`public LettuceClientConfiguration lettuceClientConfiguration () {
ClusterTopologyRefreshOptions topologyRefreshOptions = 
ClusterTopologyRefreshOptions.builder () 
.enablePeriodicRefresh (Duration.ofSeconds (30)) 
.enableAllAdaptiveRefreshTriggers () .build ();
 return LettuceClientConfiguration.builder () 
.commandTimeout (Duration.ofSeconds (1)) .shutdownTimeout (Duration.ZERO) 
.clientOptions (ClusterClientOptions.builder () 
.autoReconnect (true) 
.publishOnScheduler (true) 
.topologyRefreshOptions (topologyRefreshOptions).)
 readFrom (ReadFrom.MASTER) .build (); 
}`

I feel that the retry logic is blocked and processed, but I am wondering if this part can be processed as non-blocking.

Approximate environment
Master cluster * 3 (2 nodes each)
Slave cluster * 3 (2 nodes each)

Thanks for answering in advance.

**Comment by mp911de** [comment] 2020-04-20 10:53
This issue sounds like a duplicate of #1107.

**Closed by mp911de** 2020-04-20 10:53 UTC
Labels: status: duplicate

**Comment by ant103** [comment] 2020-04-21 11:35
When can I try the 6.0 version?

**Comment by mp911de** [comment] 2020-04-21 11:38
It's available as snapshot build from oss.sonatype.org. Check out the [readme](https://github.com/lettuce-io/lettuce-core#binariesdownload) for further details.
