### ISSUE TITLE
KqueueProvider should use log level INFO instead of WARN for KQueue library loading

### ISSUE THREAD

**Issue by lovepoetry** [lettuce-io/lettuce-core#597] opened 2017-09-06 09:39 UTC
File location: https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/com/lambdaworks/redis/KqueueProvider.java
L67, L71

Version: master

**Comment by mp911de** [comment] 2017-09-06 09:41
Thanks for your ticket. That's a duplicate of #596.

**Closed by mp911de** 2017-09-06 09:41 UTC
