### ISSUE TITLE
SSL enabled AWS-cluster connection failing.

### ISSUE THREAD

**Issue by surjadutta** [lettuce-io/lettuce-core#1221] opened 2020-02-07 22:10 UTC
I tried connecting with a SSL enabled elastic-cache cluster using spring-data-redis lib for lettuce. But the connection is failing as RedisHealthIndicator is complaining.

Getting the following exception.

```
2020-02-07 18:48:44.885   WARN [campaigns,,,] 6172 --- [nfoReplicator-0] o.s.b.a.redis.RedisHealthIndicator       : Redis health check failed

org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='<cluster-name>', port=6379]]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1111)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1084)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getClusterConnection(LettuceConnectionFactory.java:363)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:333)
```

Using the below code for connecting with Cluster.

```
 if (clusterEnable) {
            log.info("Connecting to ElasticCache cluster");
            String elasticCacheClusterEndpoint = redisProperties.getCluster().getNodes().get(GET_CONFIG_END_POINT);
            List<String> configEndpointNode = Collections.singletonList(elasticCacheClusterEndpoint);
            RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration(configEndpointNode);
            if(redisProperties.isSsl()) {
                LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder().useSsl().build();
                return new LettuceConnectionFactory(redisClusterConfiguration, lettuceClientConfiguration);
            }
            return new LettuceConnectionFactory(redisClusterConfiguration);
        }

```

**Comment by surjadutta** [comment] 2020-02-07 22:11
I am able to connect with cluster without SSL using the same code.

**Comment by mp911de** [comment] 2020-02-08 10:22
According to the failure, the hostname is empty. I’m not sure how AWS maps cluster names with SSL. Redis itself has no builtin SSL support and in some cases, you need to re-map addresses to SSL-enabled ports.

**Comment by mp911de** [comment] 2020-02-08 11:50
Note that Lettuce uses `CLUSTER NODES` to determine which nodes to connect to. You can enable debug/trace logging for the `io.lettuce.core.protocol` category to view Redis responses.

**Comment by surjadutta** [comment] 2020-02-08 15:08
@mp911de The host name is not empty I have removed the cluster name from the exception. So if you like below is the exact exception. We are using AWS elasticCache, so the cluster is running on the usual port-6379.

I tried with disbalePeerVerivication() also like below but didn't helped.
Any pointer may help. :-)

if(redisProperties.isSsl()) {
                LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder().useSsl().disbalePeerVerivication().build();
                return new LettuceConnectionFactory(redisClusterConfiguration, lettuceClientConfiguration);
            }

2020-02-07 18:48:44.885   WARN [campaigns,,,] 6172 --- [nfoReplicator-0] o.s.b.a.redis.RedisHealthIndicator       : Redis health check failed

org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='clustercfg.mmp-redis-cluster-tls-dev.be4wyx.usw2.cache.amazonaws.com', port=6379]]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1111)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1084)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getClusterConnection(LettuceConnectionFactory.java:363)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:333)

**Comment by mp911de** [comment] 2020-02-08 19:48
The exception has either a cause or suppressed exceptions. Check these as the reason is listed in there.

**Comment by mp911de** [comment] 2020-02-13 08:39
May I close this ticket or is there anything else I can assist you with?

**Comment by surjadutta** [comment] 2020-02-13 18:22
Yes you can close the ticket

**Closed** 2020-02-13 18:38 UTC
Labels: status: invalid

**Comment by arpangupta81** [comment] 2020-05-10 09:33
Can you please help me out, I am facing the same problem. What was the resolution of this issue? @mp911de @surjadutta

**Comment by mp911de** [comment] 2020-05-10 10:58
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem or at least the full stack trace including all suppressed exceptions.

**Comment by MuralikrishnaNandagopal** [comment] 2020-09-17 13:14
Please let me know if any one has template to connect to Redis Cluster using SSL connection from Java? or if the above SSL issue was solved, please let me know how?
