### ISSUE TITLE
Why does the timeout cause OutOfMemoryError

### ISSUE THREAD

**Issue by zhangran2616** [lettuce-io/lettuce-core#1681] opened 2021-03-22 06:30 UTC
![image](https://user-images.githubusercontent.com/6472032/111949022-f1f97480-8b1a-11eb-8290-197aa54be130.png)
![image](https://user-images.githubusercontent.com/6472032/111949131-21a87c80-8b1b-11eb-8357-f2fa120c99d9.png)
![image](https://user-images.githubusercontent.com/6472032/111949147-2705c700-8b1b-11eb-8d18-dddd47aa916d.png)
why OutOfMemoryError？

**Comment by mp911de** [comment] 2021-03-22 07:54
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2021-03-30 12:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-03-30 12:37 UTC
Labels: status: waiting-for-feedback
