### ISSUE TITLE
Creating new RefreshTrigger type named Connection Established.

### ISSUE THREAD

**Issue by doo871128** [lettuce-io/lettuce-core#1549] opened 2020-12-06 11:31 UTC
#### Is your feature request related to a problem? Please describe

For now, we are using refresh trigger type called PERSISTENT_RECONNECTS. 
The reason why we are using this type is because when certain instance from AWS goes down for some reason and goes back to normal, we want to detect it and reflect it to partitions as soon as possible, so that our application can call the redis instance that got back to normal(if this node is reflected on partitions, then it can be selected from ReadFrom).

The thing is there is chance where PERSISTENT_RECONNECTS can miss the event connection established event. let's suppose below situation
- adaptiveRefreshTriggersTimeout is 30 seconds by default
- topology refresh triggered on 0 second and it will not refresh the topology by the next 30 second. 
- connection established on 15 second in the connection watch dog by exponential backoff.
In this case, even if connection(channel) is established, it will not call the REDIS instance since topology is not refreshed. 

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

I want to understand deeply.. :) so please correct me if i am wrong. 
At the first glance, I want to understand why topology refresh is happening on reconnect attempt event instead of connection established event. If we can refresh the topology on the below part from connection watch dog, we don't have to worry about the above case that I mentioned.

`        

            Tuple2<CompletableFuture<Channel>, CompletableFuture<SocketAddress>> tuple = reconnectionHandler.reconnect();
            CompletableFuture<Channel> future = tuple.getT1();

            future.whenComplete((c, t) -> {

                if (c != null && t == null) {
                    //callback for connection established
                    return;
                }`

I believe that the reason why we have PERSISTENT_RECONNECTS is because as soon as the unreachable REDIS node goes back to normal, we do want to call that REDIS node. And, I think the way I suggested is proper to do it. If it fits with lettuce philosophy, can I implement it? 

Thanks :)

**Comment by mp911de** [comment] 2020-12-22 15:09
We should take a step back and address your actual question:

> I want to understand why topology refresh is happening on reconnect attempt event instead of connection established event.

The underlying assumption is that when a cluster node goes away, then the connection to this node gets disconnected. By going away, this means either failover (a master node crashes and a different node is promoted to become the new master, a node was removed entirely from the cluster).

Since we don't want to trigger a refresh on each disconnect (e.g. caused by infrastructure components or network hiccups), we have a threshold in place. Additionally, this threshold gives the cluster enough time to reconfigure itself (perform the promotions) so that a subsequent topology refresh is likely to see the new topology.

We don't use a reconnect success event because we assume that if the node can be connected again, it was some sort of infrastructure issue.

Clearly, each cloud service provided does some trickery around their Redis services which makes it impossible to come up with a one-solution-fits-all approach.

I'd suggest listening to connection events through the event bus so you can trigger a topology refresh from within your application. That way, you can build that feature on your side as we haven't seen similar requests that would justify such a change on our side.

**Comment by mp911de** [comment] 2021-02-03 13:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-02-03 13:54 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
