### ISSUE TITLE
Commands are missing with pipelining in cluster environment

### ISSUE THREAD

**Issue by Choi-Sung-Hoon** [lettuce-io/lettuce-core#2374] opened 2023-03-30 16:36 UTC
## Bug Report

Commands are missing with pipelining in cluster environment.

#### Current Behavior

In the code snippet below, the `rpush()` and `expire()` commands are not delivered to Redis.

I checked the Redis server log and the commands never delivered, but only `del()` commands were delivered and executed successfully.

The number of item is 5,000 so 15,000 commands should be delivered in total.

#### Input Code

<details>
<summary>Input Code</summary>

```java
// create single synchornous cluster connection. (dedicated)
try (StatefulRedisClusterConnection<String, String> connection = myClient.getClusterClient().connect()) {
    connection.setAutoFlushCommands(false);
    for (Item item : items) {
        batchRedisCommands(connection, item);
    }
    connection.setAutoFlushCommands(true);
    connection.flushCommands();
}

// ...

// batch commands
private void batchRedisCommands(StatefulRedisClusterConnection<String, String> connection, Item item) {
    RedisAdvancedClusterAsyncCommands<String, String> async = connection.async();
    async.del(item.getRedisKey());
    async.rpush(item.getRedisKey(), item.getList());
    async.expire(item.getRedisKey(), DAY_IN_SECOND);
}
```

</details>

#### Expected behavior/code

All the `del()`, `rpush()`, `expire()` commands are executed in order per item.

#### Environment

- Lettuce version(s): `io.lettuce:lettuce-core:6.2.3.RELEASE`
- Redis version: `5.0.14`

#### Possible Solution

None.

#### Additional context

There was no problem when I used asynchronous connection pool like below.

```java
// create asynchronous connection pool
private BoundedAsyncPool<StatefulRedisClusterConnection<String, String>> createConnectionPool() {
        CompletionStage<BoundedAsyncPool<StatefulRedisClusterConnection<String, String>>> future =
            AsyncConnectionPoolSupport.createBoundedObjectPoolAsync(
                () -> clusterClient.connectAsync(StringCodec.UTF8),
                BoundedPoolConfig.builder().maxTotal(CONNECTION_POOL_SIZE).build()
            );
        try {
            return future.toCompletableFuture().get();
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }
    }

// ...

// use dedicated async connection from cluster
for (Item item : items) {
    myClient.getConnectionPool().acquire().thenCompose(
        connection -> {
            batchRedisCommands(connection, item);
            return myClient.getConnectionPool().release(connection);
    });
}

// ... 

// batch commands
private void batchRedisCommands(StatefulRedisClusterConnection<String, String> connection, Item item) {
    connection.setAutoFlushCommands(false);
    RedisAdvancedClusterAsyncCommands<String, String> async = connection.async();
    async.del(item.getRedisKey());
    async.rpush(item.getRedisKey(), item.getList());
    async.expire(item.getRedisKey(), DAY_IN_SECOND);
    connection.flushCommands();
}
```

I saw [this comment](https://github.com/lettuce-io/lettuce-core/issues/887#issuecomment-430220187) and changed from connection pooling to single connection creation and this issue happened.

What am I doing wrong?

I have tried

1. to remove `connection.setAutoFlushCommands(false)` and `connection.flushCommands()`
2. to replace async commands with sync commands

(1) had no effect and (2) took multiple times longer than with async commands.

I'd like to ensure fast & correct order of the command exeucution.

I have further questions.

1. What happens when I call `RedisClusterClient.connect()`? Does it create new connection to a node everytime I call the method?
2. if I execute multiple commands for single dedicated connection with `RedisClusterClient`, does all the commands use the same same connection to a single dedicated node?
3. Is it ok to use `try-with-resources` with cluster connection from `RedisClusterClient.connect()` so that it closes the connection after use? In [this wiki](https://lettuce.io/core/release/reference/#redis-cluster) it says that we should not close the cluster connections.
4. If I want to reduce network I/O and guarantee the order of async commands like `del() -> rpush() -> expire()`, how can I do that?

Thank you for the reply in advance!

**Comment by Choi-Sung-Hoon** [comment] 2023-04-12 17:44
@mp911de

Hello, I first apologize for mentioning you for this issue.

I'm so sorry for bothering you but could you check this issue please?
I've been waiting for the reply for 2 weeks 😭

I'm not pushing you but I don't want that I don't get any respond for the questions either.
(I think you are busy tho)

I really want to know the cause and possible solutions.

Could you answer to the questions above please?

**Comment by mp911de** [comment] 2023-04-13 06:54
This is a duplicate of #2380. Basically, all operations in Lettuce are async. Only the flush command API is synchronous. If you use `flushCommands()` before all connections are established, then you will encounter command/synchronization loss.

**Closed by mp911de** 2023-04-13 06:54 UTC
Labels: status: duplicate

**Comment by Choi-Sung-Hoon** [comment] 2023-04-13 11:19
@mp911de 

Thank you for the comment.

Then should I change `thenCompose` to `themComplete` to guarantee the connection is established completely?

```java
myClient.getConnectionPool().acquire().thenCompose( // here
        connection -> {
            batchRedisCommands(connection, item);
            return myClient.getConnectionPool().release(connection);
    });
```

I though that the connection is established and acquired by the line.

and, it was not my goal to solve the issue by mentioning you.

I wanted to understand how lettuce works internally through following questions.

1. What happens when I call RedisClusterClient.connect()? Does it create new connection to a node everytime I call the method?
2. if I execute multiple commands for single dedicated connection with RedisClusterClient, does all the commands use the same same connection to a single dedicated node?
3. Is it ok to use try-with-resources with cluster connection from RedisClusterClient.connect() so that it closes the connection after use? In [this wiki](https://lettuce.io/core/release/reference/#redis-cluster) it says that we should not close the cluster connections.
4. If I want to reduce network I/O and guarantee the order of async commands like del() -> rpush() -> expire(), how can I do that?

Could you re-consider answering to the questions again please?
