### ISSUE TITLE
Connection Leak in Cluster Topology Refresh

### ISSUE THREAD

**Issue by cweitend** [lettuce-io/lettuce-core#721] opened 2018-03-05 09:56 UTC
We are using Lettuce 5.0.2 to connect to a Redis cluster (Elasticache and Azure) with SSL enabled.
We notice that once we enable periodic topology refresh the number of open connections to the cluster steadily increases.

We can reproduce the issue with a simple and pure Lettuce application which does nothing but periodic topology refreshes. The issue is also reproducible with SSL disabled.

The root cause of the issue seems to lie in the `io.lettuce.core.cluster.topology.Connections#drainConnections` method which mixes a local variable and an instance variable in an unintended way.

**Comment by mp911de** [comment] 2018-03-05 10:33
Thanks a lot. Not sure if that's related to #705.

**Comment by cweitend** [comment] 2018-03-05 12:53
We re-tested the original issue in a non-SSL setup and observed the same connection leak.
 
The PR (#722) seems to fix the issue for us - we did not observe any increase in cluster connections over several hours.

**Comment by mp911de** [comment] 2018-03-05 14:20
Awesome, thank's a lot for your pull-request. Will take a look.

**Comment by cweitend** [comment] 2018-03-05 15:01
You are welcome, always glad to help.

Just to give a better picture of our setup: We use `dynamicRefreshSources = false` as we talk to a rather large cluster.
 
With dynamic refresh enabled we came across some other random instabilities like very long running `ClusterTopologyRefreshTasks` and some exceptions here and there (even with a smaller cluster). We have not yet investigated these issues any further as we don't need this feature at the moment and the issues might well be AWS specific.

**Comment by mp911de** [comment] 2018-03-06 09:37
That's fixed now in snapshot builds of Lettuce 5.0.3 and 5.1.0.

**Closed by mp911de** 2018-03-06 09:37 UTC
Labels: bug

**Comment by ramizmehran** [comment] 2019-11-12 09:05
The problem is occuring again in the latest jar versions: 5.1.4.RELEASE

**Comment by mp911de** [comment] 2019-11-12 09:47
The most recent version is 5.2.1. Can you retest and file a ticket if the problem persists?
