### ISSUE TITLE
Lettuce can't connect to Redis Cluster + SSL but can connect to same Redis server + SSL if treated as Standalone node.

### ISSUE THREAD

**Issue by shubhambhattar** [lettuce-io/lettuce-core#1454] opened 2020-10-10 06:42 UTC
#### Current Behavior

I've an Azure Cache for Redis - Premium and Cluster enabled. I've been trying to connect to that Redis using `spring-boot-starter-data-redis` (spring boot version: `2.3.4.RELEASE`, Java version: `11`) and using lettuce client but Lettuce is throwing SSL exception when I am treating my Redis as a Redis Cluster but connects just fine when using it as a Standalone Redis server.

<details>
<summary>Stack trace</summary>

```java
java.lang.IllegalStateException: Failed to execute CommandLineRunner
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
    ...
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Redis connection failed; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to [RedisURI [host='<redacted>.redis.cache.windows.net', port=6380]]
    at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:66) ~[spring-data-redis-2.3.4.RELEASE.jar:2.3.4.RELEASE]
    ...
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to [RedisURI [host='<redacted>.redis.cache.windows.net', port=6380]]
    at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[lettuce-core-5.3.4.RELEASE.jar:5.3.4.RELEASE]
    ...
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address <redacted> found
    ...
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address <redacted> found
    at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:165) ~[na:na]
    ...
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.data.redis.RedisProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.connection.*;
import org.springframework.data.redis.connection.lettuce.LettuceClientConfiguration;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.data.redis.core.StringRedisTemplate;


@Configuration
class LettuceConfig {

    @Bean
    StringRedisTemplate getStringRedisTemplate(final RedisProperties redisProperties) {
        return new StringRedisTemplate(getRedisConnectionFactory(redisProperties));
    }

    @Bean
    RedisConnectionFactory getRedisConnectionFactory(final RedisProperties redisProperties) {
    
        final RedisNode redisNode = RedisNode.newRedisNode()
                .listeningAt(redisProperties.getHost(), redisProperties.getPort())
                .build();

        // Connecting as a Redis Cluster
        final RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration();
        redisClusterConfiguration.addClusterNode(redisNode);
        redisClusterConfiguration.setPassword(RedisPassword.of(redisProperties.getPassword()));

        // Connecting as a Standalone Redis server
        final RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
        redisStandaloneConfiguration.setHostName(redisProperties.getHost());
        redisStandaloneConfiguration.setPort(redisProperties.getPort());
        redisStandaloneConfiguration.setPassword(RedisPassword.of(redisProperties.getPassword()));

        final LettuceClientConfiguration.LettuceClientConfigurationBuilder lettuceClientConfigurationBuilder =
                LettuceClientConfiguration.builder()
                .clientName(redisProperties.getClientName())
                .commandTimeout(redisProperties.getTimeout());

        if (redisProperties.isSsl()) {
            lettuceClientConfigurationBuilder.useSsl();
        }

        final LettuceClientConfiguration lettuceClientConfiguration = lettuceClientConfigurationBuilder.build();

        return new LettuceConnectionFactory(redisClusterConfiguration, lettuceClientConfiguration);
    }
}

@SpringBootApplication
public class LettuceClusterApplication implements CommandLineRunner {

    private final StringRedisTemplate stringRedisTemplate;

    @Autowired
    public LettuceClusterApplication(final StringRedisTemplate stringRedisTemplate) {
        this.stringRedisTemplate = stringRedisTemplate;
    }

    public static void main(String[] args) {
        SpringApplication.run(LettuceClusterApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        System.out.println(stringRedisTemplate.hasKey("abc"));
    }
}
```

</details>

<details>
<summary>pom.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.4.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>lettuce-cluster-connect</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>lettuce-cluster-connect</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

```
</details>

My `application.properties` file:
```
spring.redis.host = <redacted>.redis.cache.windows.net
spring.redis.port = 6380
spring.redis.password = <redacted>
spring.redis.ssl = true
spring.redis.clientName = ${HOSTNAME}
spring.redis.timeout = 100000
```

#### Expected behavior/code

Lettuce should've been able to connect to Redis Cluster just fine and run the command just like it did when treating it as a standalone Redis node.

#### Environment

- Lettuce version(s): `5.3.4.RELEASE` (bundled under `spring-boot-starter-data-redis`)
- Redis version: `4.0.14`

#### Additional context

Found a similar GitHub issue: https://github.com/lettuce-io/lettuce-core/issues/246 
and the documentation link: https://lettuce.io/core/release/reference/#ssl which both basically states that this issue is fixed with Lettuce version > `4.2`. Quoting the relevant part of the documentation:

> Lettuce supports SSL connections since version 3.1 on Redis Standalone connections and since version 4.2 on Redis Cluster.

Link to StackOverflow question: https://stackoverflow.com/q/64287424/3160529

**Comment by mp911de** [comment] 2020-10-13 07:04
The linked ticket #246 and #209 are about general SSL support for Redis Cluster.

This report is related to the fact that the Redis certificate doesn't contain Redis cluster IP addresses. The Redis cluster topology is based on IP addresses, not hostnames (see https://redis.io/commands/cluster-nodes). Enabling SSL also enables SSL certificate validation. `No subject alternative names matching IP address` basically means that the supplied SSL certificate doesn't list the target IP address.

There are a couple of things you can do about:

1. If the Redis IP addresses can be mapped onto a hostname, then please configure a `MappingSocketAddressResolver` through `ClientResources` to map IP addresses into hostnames that are listed in the SSL certificate
2. Reach out to the Azure support team so that they fix the SSL certificates and include all cluster IP addresses
3. (least favorable option) Disable SSL certificate validation. That can be done with `RedisURI.setVerifyPeer(false)` when using Lettuce directly. For Spring, you should be able to register a `LettuceClientConfigurationBuilder` customizer to invoke `LettuceSslClientConfigurationBuilder.disablePeerVerification()`.

**Comment by shubhambhattar** [comment] 2020-10-22 19:00
@mp911de Thanks for the response. We're currently using the 3rd option to continue our operations but are also planning on discussing with Azure team as well for this. Will update this issue as I get more information on this.

**Comment by mp911de** [comment] 2020-10-22 20:30
FTR, with #1460 we want to improve on TLS verification options

**Comment by aravindyeduvaka** [comment] 2020-11-09 21:25
@mp911de on Azure Redis, the cluster node addresses are always on the same IP that the DNS (cacheName.redis.cache.windows.net) points towards. 

With this in mind, can we possibly change the default SocketAddressResolver to an implementation that verifies/provides a default mapping if the IPs can be mapped/resolved to one of the initialURIs with a DNS hostname?

This will definitely be a lot more secure since most people right now might be defaulting to the 3rd and the least favorable option simply because it is the easiest to do.

**Comment by aravindyeduvaka** [comment] 2020-11-10 19:47
For reference, I also had a look how StackExchange.Redis does the host verification and it seems that they infer the hostname from the initial config rather than try using the IP endpoints directly which does not also seem like a bad idea.

https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ConfigurationOptions.cs#L807

**Comment by mp911de** [comment] 2020-12-22 15:13
Since there isn't anything actionable on this ticket, I'm going to close it. If you would like us to look at this issue, please provide additional information and we will re-open the issue.

**Closed by mp911de** 2020-12-22 15:13 UTC
Labels: status: waiting-for-feedback

**Comment by sdoxsee** [comment] 2020-12-22 15:22
Thanks @mp911de . I'm not up on the details but I think @aravindyeduvaka provided an actionable suggestion to change the default SocketAddressResolver? Alternatively, could an example be provided for suggestion 1 with a MappingSocketAddressResolver that handles this? I took a look at this and wasn't able to easily figure out how to do this. I suspect suggestion 2 is unlikely to get traction and I'm unwilling to go with suggestion 3. Thanks for the great work you do.

**Comment by mp911de** [comment] 2020-12-22 15:34
We're not going to change `SocketAddressResolver` for a functionality that isn't reflecting any operational defaults but something that introduces complexity caused by Azure. 

Note this is a community project, that isn't sponsored by Microsoft or anyone else, and our maintainers are the ones who are left with trying to figure out way how to cope with quirks of AWS, RedisLabs, Azure,... you name it. Hence we're reluctant to introducing provider-specific quirks.

You can find an example of how to solve the issue via `MappingSocketAddressResolver` at https://github.com/lettuce-io/lettuce-core/blob/1e334f68aaa3cbd6a021e0b699c85a450551f42d/src/test/java/io/lettuce/core/resource/MappingSocketAddressResolverUnitTests.java#L69-L70

**Comment by ilr39** [comment] 2021-03-04 15:49
This is a ticket for Azure feedback to possibly resolve this from their side
https://feedback.azure.com/forums/169382-cache/suggestions/42831483-the-certificate-of-azure-redis-in-cluster-mode-sho

**Comment by rethab** [comment] 2023-06-01 10:22
I found these docs from azure on "Lettuce best practices": https://github.com/Azure/AzureCacheForRedis/blob/main/Lettuce%20Best%20Practices.md

They recommend basically the same (copying the code from that link):

```java
    Function<HostAndPort, HostAndPort> mappingFunction = new Function<HostAndPort, HostAndPort>() {
        @Override
        public HostAndPort apply(HostAndPort hostAndPort) {
            InetAddress[] addresses = new InetAddress[0];
            try {
                addresses = DnsResolvers.JVM_DEFAULT.resolve(host);
            } catch (UnknownHostException e) {
                e.printStackTrace();
            }
            String cacheIP = addresses[0].getHostAddress();
            HostAndPort finalAddress = hostAndPort;

            if (hostAndPort.hostText.equals(cacheIP))
                finalAddress = HostAndPort.of(host, hostAndPort.getPort());
            return finalAddress;
        }
    };

    MappingSocketAddressResolver resolver = MappingSocketAddressResolver.create(DnsResolvers.JVM_DEFAULT,mappingFunction);

    ClientResources res =  DefaultClientResources.builder()
            .socketAddressResolver(resolver).build();
```
