### ISSUE TITLE
Command timed out after 1 minute(s)

### ISSUE THREAD

**Issue by Kiranmai148** [lettuce-io/lettuce-core#1299] opened 2020-05-28 05:32 UTC
Below is the spring boot redis dependency i am using.
compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-redis', version: '2.2.7.RELEASE'

Am facing this issue once in a while. Please do let me know what is the cause of this issue and suggest me how can i avoid it.

Below is the configuration.

@Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        return new LettuceConnectionFactory(redisHost, redisPort);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory());
        template.setHashValueSerializer(new StringRedisSerializer());
        template.setEnableTransactionSupport(true);
        template.setKeySerializer(new StringRedisSerializer());
        template.setHashKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(new GenericToStringSerializer<Object>(Object.class));
        template.afterPropertiesSet();
        return template;
    }

Below are the logs.
Caused by: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
    at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
    at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
    at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
    at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
    at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:799)
    at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:148)
    at org.springframework.data.redis.connection.DefaultedRedisConnection.set(DefaultedRedisConnection.java:274)
    at org.springframework.data.redis.core.DefaultValueOperations$3.inRedis(DefaultValueOperations.java:240)
    at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:59)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
    at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
    at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:236)
    at com.paytmmoney.equity.marketstatus.timer.cron.publisher.RedisMessagePublisher.pushToRedis(RedisMessagePublisher.java:38)
    at com.paytmmoney.equity.marketstatus.timer.cron.service.MarketStatusTimerCronService.processTimerResponse(MarketStatusTimerCronService.java:119)
    at com.paytmmoney.equity.marketstatus.timer.cron.service.MarketStatusTimerCronService.updateTimerData(MarketStatusTimerCronService.java:66)
    ... 14 common frames omitted
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
    at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
    at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
    at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
    at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
    at com.sun.proxy.$Proxy94.set(Unknown Source)
    at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.set(LettuceStringCommands.java:146)
    ... 24 common frames omitted

**Comment by mp911de** [comment] 2020-05-28 07:41
The cause is that the client didn't receive a response in time. It makes sense to record a debug log up to the point where the exception is thrown to see which other commands were issued prior to the timeout.

**Comment by Kiranmai148** [comment] 2020-05-28 08:45
@mp911de Do you have any idea how to reproduce this issue, could you please tell me is yes????

**Comment by mp911de** [comment] 2020-06-08 09:52
Can you attach a debug log and thread dump for further diagnosis?

**Comment by mp911de** [comment] 2020-07-01 06:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-07-01 06:38 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
