### ISSUE TITLE
the subscription will be lost after multiple switchovers in the sentinel mode

### ISSUE THREAD

**Issue by zzlxxi** [lettuce-io/lettuce-core#1059] opened 2019-06-13 13:11 UTC
Sentinel mode multiple switch connection unavailable / subscription lost.
Will the address of this sentinel continue to be re-used after a period of recovery? My problem is that after multiple instances of the sentinel are closed, the connection lost subscription will not reconnect (spring-data-redis + lettuce)

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by zzlxxi** [comment] 2019-06-13 13:14
for help. thanks

**Comment by mp911de** [comment] 2019-06-13 15:48
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2019-06-29 16:21
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-06-29 16:21 UTC
Labels: status: waiting-for-feedback, type: bug
