### ISSUE TITLE
lettuce uses the UDP protocol to occupy two random ports

### ISSUE THREAD

**Issue by qqhai007** [lettuce-io/lettuce-core#2192] opened 2022-09-05 13:46 UTC
## Bug Report

Reids uses the domain name, and lettuce uses the UDP protocol to occupy two random ports.

#### Current Behavior

 netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 182.10.21.136:8088      0.0.0.0:*               LISTEN      519/java
udp        0      0 0.0.0.0:53578           0.0.0.0:*                           519/java
udp        0      0 0.0.0.0:59364           0.0.0.0:*                           519/java

The UDP port is not released. After the restart, the port changes.

**Comment by qqhai007** [comment] 2022-09-06 05:56
The underlying DNS protocol uses UDP, but it is not clear why the port is not released.

**Comment by qqhai007** [comment] 2022-11-01 03:59
5.2.2 exist this problem
6.1.6 dose't exist

**Comment by mp911de** [comment] 2022-11-17 08:34
Since 5.x is no longer maintained and the issue is resolved in 6.1, closing the ticket.

**Closed by mp911de** 2022-11-17 08:34 UTC
