### ISSUE TITLE
Lettuce can't connect to Azure Redis 6(standalone mode) over SSL, but can connect to Azure Redis 4(clustered mode) over SSL.

### ISSUE THREAD

**Issue by umang92** [lettuce-io/lettuce-core#1817] opened 2021-07-26 13:54 UTC
#### Current Behavior

The code works fine with Azure Redis 4 (clustered mode) over SSL using the DNSResolver techniques explained here:
1. https://stackoverflow.com/questions/64287424/lettuce-cant-connect-to-redis-cluster-using-ssl-but-can-connect-to-same-redis-s
2. https://github.com/lettuce-io/lettuce-core/issues/1454
 
But when I try to connect the Azure Redis 6 (standalone mode) over SSL, I get the following exception:
```Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to <redacted>.redis.cache.windows.net/20.**.***.1:6380```

<details>
<summary>Stack trace</summary>

```java
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to <redacted>.redis.cache.windows.net/20.**.***.1:6380
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:320)
	at io.lettuce.core.RedisClient.connectPubSub(RedisClient.java:355)
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
        RedisURI.Builder builder = RedisURI.Builder.redis(hosts.getHost(), hosts.getPort());
        builder.withSsl(Boolean.TRUE);
        builder.withPassword(hosts.getPassword());
        builder.withTimeout(Duration.ofMillis(properties.getRedisCommandTimeout()));
        res = DefaultClientResources.builder().dnsResolver(new DirContextDnsResolver()).build();
        redisClusterClient = RedisClient.create(res, builder.build());
       redisClusterClient.connectPubSub(new StreamRedisCodec()).sync();
```

</details>

#### Expected behavior/code

The expectation is that the connection should go through fine without any exception.

#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version: 6

**Comment by mp911de** [comment] 2021-07-26 13:56
Can you please attach a trace log of the `io.lettuce.core.protocol` logger? Supposedly, the issue is on the Azure side as we've seen several of such reports already.

**Comment by umang92** [comment] 2021-07-26 18:40
[trace_logs.txt](https://github.com/lettuce-io/lettuce-core/files/6880436/trace_logs.txt)
@mp911de Please see if this helps.

**Comment by mp911de** [comment] 2021-07-27 06:54
Thanks. This is essentially a duplicate of #1776, see https://github.com/lettuce-io/lettuce-core/issues/1776#issuecomment-887259577 for further details. That is a server problem.

**Closed by mp911de** 2021-07-27 06:54 UTC
Labels: status: duplicate

**Comment by umang92** [comment] 2021-07-27 12:27
Thanks, @mp911de. So essentially Azure Redis 6 is following RESP3 during the handshake and lettuce doesn't support that yet. Does moving to lettuce version 6 help with this?

I suppose the problem would remain the same even with Azure Redis 6(clustered mode)?

Also looking at https://redis.io/commands/hello is seems like RESP3 is introduced with Redis 6. But the same code works fine with AWS Elasticache Reds 6(both standalone and clustered mode). Why is there a difference between cloud providers?

**Comment by mp911de** [comment] 2021-07-27 15:15
Azures RESP3 implementation is broken. Lettuce supports RESP3 since one or two years already. You can switch to RESP2 through configuring ClientOptions.

**Comment by umang92** [comment] 2021-07-30 08:30
Falling back RESP2 worked. But had to upgrade to Lettuce 6.1.0 for that.

Code:

```
//connect function
        RedisURI.Builder builder = RedisURI.Builder.redis(hosts.getHost(), hosts.getPort());
        builder.withSsl(Boolean.TRUE);
        builder.withPassword(hosts.getPassword());
        builder.withTimeout(Duration.ofMillis(properties.getRedisCommandTimeout()));
        ClientResources res = clientResources(hosts);
        redisClusterClient = RedisClient.create(res, builder.build());
        redisClusterClient.setOptions(ClientOptions.builder()
                        .protocolVersion(ProtocolVersion.RESP2)
                        .build());
       redisClusterClient.connectPubSub(new StreamRedisCodec()).sync();

    private ClientResources clientResources(RedisHosts hosts) throws UnknownHostException {
        DefaultClientResources.Builder clientResourcesBuilder = DefaultClientResources.builder();
        String configuredHost = hosts.getHost();
        List<InetAddress> inetAddresses = Arrays.asList(InetAddress.getAllByName(configuredHost));
        logger.info("inetAddrs {}", inetAddresses);
        MappingSocketAddressResolver resolver = MappingSocketAddressResolver.create(
                DnsResolvers.UNRESOLVED,
                hostAndPort -> inetAddresses.stream()
                        .anyMatch(i -> i.getHostAddress().equals(hostAndPort.getHostText())) ?
                        HostAndPort.of(configuredHost, hostAndPort.getPort()) :
                        hostAndPort
        );
        clientResourcesBuilder.socketAddressResolver(resolver);
        return clientResourcesBuilder.build();
    }

```
