### ISSUE TITLE
Commands Timeout ignored/not working during refresh

### ISSUE THREAD

**Issue by pendula95** [lettuce-io/lettuce-core#1107] opened 2019-08-12 16:10 UTC
#### Current Behavior
Command timeout is ignored in period of adaptive/periodic refresh

#### Expected behavior/code

Command timeout should be respected in this state. 

#### Environment

- Lettuce version(s): 5.1.7.RELEASE
- Redis version: 5.0.0

#### Possible Solution

I assume that refresh is blocking the eventloop and timeout can not be executed during this period

#### Additional context

Reproducer can be found here:
[https://github.com/pendula95/lettuce-reproducer](https://github.com/pendula95/lettuce-reproducer)

**Comment by mp911de** [comment] 2019-08-14 07:39
Care to be more specific? Do you mean that command timeouts of user-space commands are not respected if a Redis cluster node is not available?

**Comment by pendula95** [comment] 2019-08-15 14:41
Here is info on how I create connection. It is commands timeout.

<details>
<summary>Input Code</summary>

```java
clusterClient = RedisClusterClient
                .create("redis://localhost:7002/");
        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enableAllAdaptiveRefreshTriggers()
                .refreshTriggersReconnectAttempts(1)
                .adaptiveRefreshTriggersTimeout(Duration.ofMillis(100))
                .build();

        TimeoutOptions timeoutOptions = TimeoutOptions.builder().fixedTimeout(Duration.ofMillis(1000))
            .timeoutCommands(true).build();

        clusterClient.setOptions(ClusterClientOptions.builder()
                .topologyRefreshOptions(topologyRefreshOptions)
                .timeoutOptions(timeoutOptions)
                .build());

        StatefulRedisClusterConnection<String, String> connection = clusterClient.connect();
        reactiveCommands = connection.reactive();
```
</details>

**Comment by mp911de** [comment] 2019-08-15 14:46
> Do you mean that command timeouts of user-space commands are not respected if a Redis cluster node is not available?

Can you provide a bit more information?

**Comment by pendula95** [comment] 2019-08-15 14:55
Reproducers preforms commands on redis cluster per cycle. It logs counter value that was obtained byt Redis get. This is done in while loop. When for example one master is killed commands start to timeout as timeout is set to 1 second. You can see in log lines: 

> 11:08:17.101 [lettuce-nioEventLoop-4-2] WARN  c.i.lettuce.RetryWithDelay - Retry = 0 time for error = Connection reset by peer

And everything is fine as I have mechanism to retry timeouted commands. Please care for timestamps, everything is ok as each command in instantly retried and than timeouted after a second.

> 11:08:18.142 [lettuce-eventExecutorLoop-1-8] WARN  c.i.lettuce.RetryWithDelay - Retry = 1 time for error = Command timed out after 1 second(s)
11:08:19.143 [lettuce-eventExecutorLoop-1-3] WARN  c.i.lettuce.RetryWithDelay - Retry = 2 time for error = Command timed out after 1 second(s)
11:08:20.145 [lettuce-eventExecutorLoop-1-4] WARN  c.i.lettuce.RetryWithDelay - Retry = 3 time for error = Command timed out after 1 second(s)
11:08:21.147 [lettuce-eventExecutorLoop-1-5] WARN  c.i.lettuce.RetryWithDelay - Retry = 4 time for error = Command timed out after 1 second(s)

In the background reconnect process starts and while this is done commands are not timeouted. You can see that in the log there is a 7 sec delay between retry - reconnect failed - retry. This means reconnect is blocking timeout or timeout is ignored during this period.
You can find more info in log:
<details>
<summary>Log</summary>

```java
11:08:17.031 [lettuce-nioEventLoop-4-2] INFO  com.ipification.lettuce.LettuceConn - Count = 305
11:08:17.042 [lettuce-nioEventLoop-4-3] INFO  com.ipification.lettuce.LettuceConn - Count = 306
11:08:17.051 [lettuce-nioEventLoop-4-3] INFO  com.ipification.lettuce.LettuceConn - Count = 307
11:08:17.060 [lettuce-nioEventLoop-4-4] INFO  com.ipification.lettuce.LettuceConn - Count = 308
11:08:17.069 [lettuce-nioEventLoop-4-2] INFO  com.ipification.lettuce.LettuceConn - Count = 309
11:08:17.079 [lettuce-nioEventLoop-4-3] INFO  com.ipification.lettuce.LettuceConn - Count = 310
11:08:17.101 [lettuce-nioEventLoop-4-2] WARN  c.i.lettuce.RetryWithDelay - Retry = 0 time for error = Connection reset by peer
11:08:17.227 [lettuce-eventExecutorLoop-1-1] INFO  i.l.c.protocol.ConnectionWatchdog - Reconnecting, last destination was /172.20.0.3:6379
11:08:17.234 [lettuce-eventExecutorLoop-1-1] WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.20.0.3:6379
11:08:17.233 [lettuce-nioEventLoop-4-7] WARN  i.l.c.c.t.ClusterTopologyRefresh - Unable to connect to 172.20.0.3:6379
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.20.0.3:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:330)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:670)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.20.0.3:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	... 8 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	... 12 common frames omitted
11:08:18.142 [lettuce-eventExecutorLoop-1-8] WARN  c.i.lettuce.RetryWithDelay - Retry = 1 time for error = Command timed out after 1 second(s)
11:08:19.143 [lettuce-eventExecutorLoop-1-3] WARN  c.i.lettuce.RetryWithDelay - Retry = 2 time for error = Command timed out after 1 second(s)
11:08:20.145 [lettuce-eventExecutorLoop-1-4] WARN  c.i.lettuce.RetryWithDelay - Retry = 3 time for error = Command timed out after 1 second(s)
11:08:21.147 [lettuce-eventExecutorLoop-1-5] WARN  c.i.lettuce.RetryWithDelay - Retry = 4 time for error = Command timed out after 1 second(s)
11:08:22.149 [lettuce-eventExecutorLoop-1-6] WARN  c.i.lettuce.RetryWithDelay - Retry = 5 time for error = Command timed out after 1 second(s)
11:08:23.152 [lettuce-eventExecutorLoop-1-7] WARN  c.i.lettuce.RetryWithDelay - Retry = 6 time for error = Command timed out after 1 second(s)
11:08:24.154 [lettuce-eventExecutorLoop-1-8] WARN  c.i.lettuce.RetryWithDelay - Retry = 7 time for error = Command timed out after 1 second(s)
11:08:25.155 [lettuce-eventExecutorLoop-1-1] WARN  c.i.lettuce.RetryWithDelay - Retry = 8 time for error = Command timed out after 1 second(s)
11:08:26.156 [lettuce-eventExecutorLoop-1-2] WARN  c.i.lettuce.RetryWithDelay - Retry = 9 time for error = Command timed out after 1 second(s)
11:08:27.158 [lettuce-eventExecutorLoop-1-3] WARN  c.i.lettuce.RetryWithDelay - Retry = 10 time for error = Command timed out after 1 second(s)
11:08:27.427 [lettuce-eventExecutorLoop-1-5] INFO  i.l.c.protocol.ConnectionWatchdog - Reconnecting, last destination was 172.20.0.3:6379
11:08:28.159 [lettuce-eventExecutorLoop-1-4] WARN  c.i.lettuce.RetryWithDelay - Retry = 11 time for error = Command timed out after 1 second(s)
11:08:29.160 [lettuce-eventExecutorLoop-1-4] WARN  c.i.lettuce.RetryWithDelay - Retry = 12 time for error = Command timed out after 1 second(s)
11:08:30.161 [lettuce-eventExecutorLoop-1-5] WARN  c.i.lettuce.RetryWithDelay - Retry = 13 time for error = Command timed out after 1 second(s)
11:08:37.442 [lettuce-nioEventLoop-4-5] WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /172.20.0.3:6379
11:08:37.445 [lettuce-nioEventLoop-4-7] WARN  i.l.c.c.t.ClusterTopologyRefresh - Unable to connect to 172.20.0.3:6379
java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /172.20.0.3:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:330)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:269)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.20.0.3:6379
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	... 9 common frames omitted
11:08:37.501 [lettuce-eventExecutorLoop-1-6] WARN  c.i.lettuce.RetryWithDelay - Retry = 14 time for error = Command timed out after 1 second(s)
11:08:37.507 [lettuce-nioEventLoop-4-3] INFO  com.ipification.lettuce.LettuceConn - Count = 311
11:08:37.513 [lettuce-nioEventLoop-4-4] INFO  com.ipification.lettuce.LettuceConn - Count = 312
11:08:37.522 [lettuce-nioEventLoop-4-4] INFO  com.ipification.lettuce.LettuceConn - Count = 313
11:08:37.526 [lettuce-eventExecutorLoop-1-2] INFO  i.l.c.protocol.ConnectionWatchdog - Reconnecting, last destination was 172.20.0.3:6379
11:08:37.531 [lettuce-nioEventLoop-4-3] INFO  com.ipification.lettuce.LettuceConn - Count = 314
11:08:37.539 [lettuce-nioEventLoop-4-3] INFO  com.ipification.lettuce.LettuceConn - Count = 315
```
</details>

**Comment by mp911de** [comment] 2019-08-16 12:23
I wasn't able to reproduce the issue. See the attached log file. Retries are fired every second.

[app.log](https://github.com/lettuce-io/lettuce-core/files/3509516/app.log)

I suggest that you run your code in a debugger to inspect what happens within the 7 silent seconds.

**Comment by pendula95** [comment] 2019-08-16 12:42
What cluster topology did you use?

**Comment by mp911de** [comment] 2019-08-16 12:58
Two masters and two replicas.

**Comment by pendula95** [comment] 2019-08-16 13:07
Ok, can you please use topology where cluster can recover. Example 3 master/3 slave and keep program running until commands start to success again. I ran the test again and I wasn't able to reproduce from first time. Looks like it won't happen each time but here is reproduction log with DEBUG.

Please take a look at timestamps [14:57:53.071] - [14:58:00.288]

[app.log](https://github.com/lettuce-io/lettuce-core/files/3509679/app.log)

**Comment by pendula95** [comment] 2019-08-16 13:13
Can you please use topology where cluster can recover 3master/3slave and wait for program to continue after recovered cluster. 
I wasn't able to replicate from first attempt but there was in second attempt I got bug again. Here is the DEBUG full log:
[app.log](https://github.com/lettuce-io/lettuce-core/files/3509706/app.log)
Take a look at timestamps [14:57:53.071] - [14:58:00.288]
I don't see any logs in the pause period, like nothing is happening.

**Comment by pendula95** [comment] 2019-08-16 13:34
I guess this is due to blocking reconnect nature?

**Comment by mp911de** [comment] 2019-08-24 09:06
> I assume that refresh is blocking the eventloop and timeout can not be executed during this period

It took quite a while to understand what happens here and how to reproduce the issue. I wasn't able to reproduce the issue because my topology refresh/connect attempts immediately receive a connection refused which makes topology refresh a matter of milliseconds.

Timeout expiry and topology refresh are executed on the same thread pool. Expiries are distributed evenly across multiple threads but once a thread is busy with refresh, then subsequent expiries are delayed until the topology refresh has finished.

The only fix is to rewrite the refresh procedure to be non-blocking. This is likely to happen with Lettuce 6.

**Comment by pendula95** [comment] 2019-08-25 11:17
I would like to try and contribute with the issue. Can you point me in the right direction for rewriting this in Lettuce as I am not yet familiar with project.

**Comment by mp911de** [comment] 2019-09-06 10:20
[`ClusterTopologyRefresh`](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/cluster/topology/ClusterTopologyRefresh.java) is the class that initiates topology refresh. We need to convert that code to be asynchronous, ideally using Project Reactor as a reactive API allows for better composition and error handling than `CompletableFuture`.

**Comment by mp911de** [comment] 2020-03-13 09:35
That's fixed now by rewriting the topology refresh into an non-blocking process.

**Closed by mp911de** 2020-03-13 09:35 UTC
Labels: target: Lettuce 6, type: bug
