### ISSUE TITLE
NullPointerException in ArrayOutput

### ISSUE THREAD

**Issue by asalabaev** [lettuce-io/lettuce-core#1534] opened 2020-11-27 10:04 UTC
#### Current Behavior

Unstable error 
```
Caused by: java.lang.NullPointerException
        at io.lettuce.core.output.ArrayOutput.set(ArrayOutput.java:48)
        at io.lettuce.core.output.MultiOutput.set(MultiOutput.java:70)
        at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:374)
        at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:178)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:716)
        at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:680)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:675)
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:596)
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:811)
```
<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
            final RedisCommands<String, String> sync = j.sync();
            sync.multi();
            for (PojoMap x : keyValues_org)
                x.del(sync, orderedFieldsByType, indexedFieldsByType);
            sync.exec();

```
x.del() function contains srem, zrem, del invocations
</details>

#### Environment

- Lettuce version(s): 5.3.1.RELEASE
- Redis version: e.g. 5.05

#### Possible Solution

No solution found

**Comment by asalabaev** [comment] 2020-11-27 10:28
At the same time I also noticed another NullPointerException (please let me know  if they are not connected and should be logged selarately)

Caused by: java.lang.NullPointerException
        at io.lettuce.core.StatefulRedisConnectionImpl.preProcessCommand(StatefulRedisConnectionImpl.java:262)
        at io.lettuce.core.StatefulRedisConnectionImpl.dispatch(StatefulRedisConnectionImpl.java:166)
        at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:472)
        at io.lettuce.core.AbstractRedisAsyncCommands.xadd(AbstractRedisAsyncCommands.java:1519)

**Comment by mp911de** [comment] 2020-11-27 11:09
Thanks for the report. I'm not able to reproduce the issue. The second exception indicates that connections are shared across multiple threads in combination with transactional use. When using transactions, ensure that the connection isn't used by other threads at the same time since transactions affect the connection state and weird exceptions may happen. I assume that's also the case for the error above.

**Comment by asalabaev** [comment] 2020-11-27 18:30
Your finding is absolutely correct. A shared connection, multi-threaded system, transactions.

But please guide and/or correct me.. I might be confused about the connections usage

after reading the https://github.com/lettuce-io/lettuce-core/wiki/Connection-Pooling-5.1 and https://github.com/lettuce-io/lettuce-core/wiki/Stateful-Connections  my understanding was that until I use blocking operations I can safely share one stateful connection (created via client.connect() ) and use it the way I do.

I definitely missed the notes from https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing
especially 


> You should not use transactional commands (MULTI) on shared connection. If you use Redis-blocking commands (e. g. BLPOP) all invocations of the shared connection will be blocked until the blocking command returns which impacts the performance of other threads. Blocking commands can be a reason to use multiple connections.

I was under impression that shared connections and blocking operations is the no-go combination. And as I see it after your response the MULTI is also not for the shared connections. 
I will re-do my code. 

Thank you for the prompt reply!

**Comment by mp911de** [comment] 2020-11-27 19:21
The both limitations are probably mentioned everywhere (reader, wiki start page at https://github.com/lettuce-io/lettuce-core/wiki). 

Closing this ticket then.

**Closed** 2020-11-27 19:21 UTC
Labels: status: invalid
