### ISSUE TITLE
Peaks on Redis connected clients

### ISSUE THREAD

**Issue by ThomasJacqueminet** [lettuce-io/lettuce-core#2478] opened 2023-08-11 15:03 UTC
#### Current Behavior

Hello, 

We have an API that is called 24/7 with peaks in the morning : from 6K calls per min to 12-20K.
These calls are inputs processed then updated/stored into REDIS.
We are using Redis HA.

![image](https://github.com/lettuce-io/lettuce-core/assets/13131870/052ecd0d-39cd-48a6-8fd8-9de10e008b1d)

We have several pods that are linked to as REDIS instance that behaves « properly » and a stable number of connected clients (Lettuce 3.5.0) :
 
![image](https://github.com/lettuce-io/lettuce-core/assets/13131870/5e7e8af9-a56c-4ca9-8fba-c8e3e4e6d2ef)

When we upgraded our libs to our new version, we discovered that our REDIS connections were going nuts when we had those calling peaks :
 
![image](https://github.com/lettuce-io/lettuce-core/assets/13131870/ab1a8e02-31c0-4ed9-a514-117ebedd36a2)

It climbs to fast we reach the threshold of 10K and are met with this error :
« org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to xxxxxxx »

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment
Our project is running on an Azure Kubernetes Service, in version 1.26.3.
We use EFK and Prometheus for monitoring.

**Lib upgrades :**
Here are all the upgrades we made with our last release
Spring 4.2.4 => 5.3.28
Spring security 4.0.3 => 5.7.5
Spring data redis 1.6.6 => 2.7.14
Jackson 1.9.13 => 2.14.0
Hibernate 4.3.5.Final => 5.4.24.Final
Quartz 2.2.1 => 2.3.2
Cxf 3.1.10 => 3.5.6
Jcsv 1.4.0 => 1.4.0
Guava 16.0.1 => 30.0-jre
Spring ldap 2.0.2.RELEASE => 2.4.0
Lettuce « forked » 3.5.0.final => 6.2.5

#### Possible Solution
_What we tried :_

- Add more logs
- - We add custom logs to monitor exactly what’s happening in our code, and logs were criticaly increasing only when interacting Redis Tampon with Lettuce.
- Modifying our infrastructure
- - We could reproduce the issue in our testing environment with 50% of the api calls, if we reduced the number of pods from 5 to 2.
- - 5 pods and the REDIS connections stay stable with the same API inputs
- - 2 pods and the REDIS connections peak at 4-5K
- - 1 pod and the connections peak even more and kill the pod
- Modifying the connectionFactory : In progress

#### Additional context

We had a bug thread with Lettuce 3.5.0, so we fixed it with this edit, found on 4.X Lettuce’s Github :
 
![image](https://github.com/lettuce-io/lettuce-core/assets/13131870/6bb39a67-43b3-427d-b691-90e7a47d3def)

Would you have advices we could follow or some leads ?
Most of the « resolved » issue we find on this type of problem ends with switching to Jedis.

Regards,
Thomas

**Comment by mp911de** [comment] 2023-08-14 07:28
Do you use connection pooling for Lettuce? Pooling is mainly used for caching connections. However, it can also have a limiting nature to detect early where connections get lost (leaked) and never returned. 

Can you take a heap dump to investigate the references to Lettuce connections to learn which components hold onto the connections.

**Comment by JuSuperSonic** [comment] 2023-08-14 07:40
No we don't use the pooling connection !
Here the detail about our LettuceConnectionFactory 
`    @Bean
    public RedisConnectionFactory redisConnectionFactory(RedisSentinelConfiguration sentinelConfiguration) {

        logger.logTechniqueDebug(LogTechniqueFactory.getLogTechnique(new Date(), LogType.REDIS, this.getClass().getName(), "Création de la Redis connection Factory.",
                "Création de la Redis connection Factory, mode sentinels."));

        LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
                .readFrom(ReadFrom.REPLICA_PREFERRED)
                .clientName(MessageFormat.format("{0}{1}", getHosname(), COMMAND))
                .commandTimeout(Duration.ofMillis(timeout))
                .shutdownTimeout(Duration.ofMillis(shutdownTimeout))
                .build();
        return new LettuceConnectionFactory(sentinelConfiguration, clientConfig);
    }`

We tried to disable the sharedNativeConnection and it was a terrible idea : 

-     Our pods needs more RAM to handle this disabled options.
-     The increase of connections to 10 000K (on master and sentinels) was faster (and higher)

When i try to increase the CPU, (and after re-enable the sharedNativeConnection option) the peaks of connection increase only to 250 (instead of 3000).

**Comment by mp911de** [comment] 2023-08-14 07:59
Keeping `sharedNativeConnection` is indeed a good approach. With using `readFrom` I strongly recommend using pooling because these connections connect to sentinel and data nodes with a lot of TCP connections. It will not only improve latency (because the handshake phase is shorter) but also allocate a lot less memory due to keeping connections pooled.

**Comment by JuSuperSonic** [comment] 2023-08-14 08:02
I just a detail : our application use redis in two differents way : 

- Spring Data Redis (with RedisTemplate)
- SpringIntegration with intput/output channel
---

This morning we had this graph about connections : 
![image](https://github.com/lettuce-io/lettuce-core/assets/62757996/f9f661fa-3dcc-457c-a63e-c4d68a72851e)
(You can see the start of problem at 06:31:10)
And i get from lettuce 9Mo of this logs : 

> 2023-08-14T04:31:29.843017997Z 06:31:29.842 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.RedisClient - Cannot connect Redis Sentinel at redis://redis-sentinel-0.redis-sentinel.redis.svc.cluster.local:26379?clientName=my-application-859fd46587-7kpxr-cmd: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: redis-sentinel-0.redis-sentinel.redis.svc.cluster.local/10.X.X.X:26379
2023-08-14T04:31:29.847968640Z 06:31:29.847 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.RedisClient - Cannot connect Redis Sentinel at redis://redis-sentinel-0.redis-sentinel.redis.svc.cluster.local:26379?clientName=my-application-859fd46587-7kpxr-cmd: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: redis-sentinel-0.redis-sentinel.redis.svc.cluster.local/10.X.X.X:26379

**Comment by JuSuperSonic** [comment] 2023-08-14 08:08
> Keeping `sharedNativeConnection` is indeed a good approach. With using `readFrom` I strongly recommend using pooling because these connections connect to sentinel and data nodes with a lot of TCP connections. It will not only improve latency (because the handshake phase is shorter) but also allocate a lot less memory due to keeping connections pooled.

When you say use a pooling if i choose to use the option .readFrom(ReadFrom.REPLICA_PREFERRED) and not .readFrom(ReadFrom.MASTER) ?

If i had th configura a pooling you talk about Synchronous/Blocking via Apache Commons Pool 2 instead of Asynchronous/Non-Blocking via a Lettuce-specific pool implementation (since version 5.1) ?

**Comment by mp911de** [comment] 2023-08-14 08:40
> When you say use a pooling if i choose to use the option .readFrom(ReadFrom.REPLICA_PREFERRED) and not .readFrom(ReadFrom.MASTER) ?

Using `readFrom` uses Sentinel's Pub/Sub mechanism to keep track of the topology. It is an indicator to use Lettuce's `MasterReplica` API that includes command routing as per `readFrom`.

The actual `readFrom` value doesn't matter, whether it is `ReadFrom.MASTER` or `ReadFrom.REPLICA`.

If you configure connection pooling, then Spring Data Redis configures both pools for you, the Apache Commons Pool component for synchronous usage and the async pool for reactive usage.

**Comment by JuSuperSonic** [comment] 2023-08-14 11:28
Hum, ok i keep an eye on this part after !
I had this issue before i add this options so definitely not the source of this issue.

This stack trace about connection could be the root cause ?

> I just a detail : our application use redis in two differents way :
> 
> * Spring Data Redis (with RedisTemplate)
> * SpringIntegration with intput/output channel
> 
> This morning we had this graph about connections : ![image](https://user-images.githubusercontent.com/62757996/260390937-f9f661fa-3dcc-457c-a63e-c4d68a72851e.png) (You can see the start of problem at 06:31:10) And i get from lettuce 9Mo of this logs :
> 
> > 2023-08-14T04:31:29.843017997Z 06:31:29.842 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.RedisClient - Cannot connect Redis Sentinel at redis://redis-sentinel-0.redis-sentinel.redis.svc.cluster.local:26379?clientName=my-application-859fd46587-7kpxr-cmd: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: redis-sentinel-0.redis-sentinel.redis.svc.cluster.local/10.X.X.X:26379
> > 2023-08-14T04:31:29.847968640Z 06:31:29.847 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.RedisClient - Cannot connect Redis Sentinel at redis://redis-sentinel-0.redis-sentinel.redis.svc.cluster.local:26379?clientName=my-application-859fd46587-7kpxr-cmd: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: redis-sentinel-0.redis-sentinel.redis.svc.cluster.local/10.X.X.X:26379

I check on sentinel side and i have only this :

`2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.528 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.528 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=44, just started
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.528 # Configuration loaded
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.529 * monotonic clock: POSIX clock_gettime
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.529 * Running mode=sentinel, port=26379.
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.570 * Sentinel new configuration saved on disk
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.570 # Sentinel ID is a178bc8fff94bd4811d7bf136b50b6ba4b27e5ae
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.570 # +monitor master mymaster 10.X.X.X 6379 quorum 2
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.570 * +slave slave 10.Y.Y.Y:6379 10.Y.Y.Y 6379 @ mymaster 10.X.X.X 6379
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.578 * Sentinel new configuration saved on disk
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.578 * +slave slave 10.Z.Z.Z:6379 10.Z.Z.Z 6379 @ mymaster 10.X.X.X 6379
2023-08-12T11:07:01+02:00 44:X 12 Aug 2023 11:07:01.586 * Sentinel new configuration saved on disk
2023-08-12T11:07:02+02:00 44:X 12 Aug 2023 11:07:02.090 * +sentinel sentinel 6000b2e9a3982f38aaab34e0c860d9345852914b 10.5.48.193 26379 @ mymaster 10.X.X.X 6379
2023-08-12T11:07:02+02:00 44:X 12 Aug 2023 11:07:02.100 * Sentinel new configuration saved on disk
2023-08-12T11:07:02+02:00 44:X 12 Aug 2023 11:07:02.108 * Sentinel new configuration saved on disk
2023-08-12T11:07:02+02:00 44:X 12 Aug 2023 11:07:02.108 # +new-epoch 1
2023-08-12T11:07:03+02:00 44:X 12 Aug 2023 11:07:03.472 * +sentinel sentinel 8d166ddfa435e2b7f18c1f5095401614151285b7 10.5.48.222 26379 @ mymaster 10.X.X.X 6379
2023-08-12T11:07:03+02:00 44:X 12 Aug 2023 11:07:03.480 * Sentinel new configuration saved on disk`

**Comment by mp911de** [comment] 2023-08-14 11:41
`Cannot assign requested address` means that there are too many open connections to the same host. It could be that if there's a failure in opening one of the node connections, a connection leak remains.

**Comment by JuSuperSonic** [comment] 2023-08-14 12:24
Okay ! 
I'll deploy redis exporter on my sentinels to be sure about that :)
I little bit confuse to get this behaviour after doing the updates.
Do you have some advises to try to found the root cause or eliminate this behaviour ?

**Comment by JuSuperSonic** [comment] 2023-08-19 16:24
Hi Mark,

Thanks for your help (and your work), set a pool connections solved our issue : 
I set the maxTotal for my test to 40 (and i have 2 instances), now it's seems stable ! :)

![image](https://github.com/lettuce-io/lettuce-core/assets/62757996/1c5bc7d1-aefe-446b-b880-abd788423ffd)

Here my configuration :

```
@Bean
public GenericObjectPoolConfig<StatefulRedisConnection<String, String>> poolConfiguration() {
    GenericObjectPoolConfig<StatefulRedisConnection<String, String>> poolConfig = new GenericObjectPoolConfig<>();
    poolConfig.setMaxTotal(maxTotal);
    poolConfig.setMinIdle(minIdle);
    poolConfig.setMaxIdle(maxIdle);
    poolConfig.setMaxWait(Duration.ofMillis(maxWait));
    poolConfig.setTestOnBorrow(testOnBorrow);
    poolConfig.setTestOnReturn(testOnReturn);
    poolConfig.setTestWhileIdle(testWhileIdle);
    poolConfig.setMinEvictableIdleTime(Duration.ofMillis(minEvictableIdleTime));
    poolConfig.setTimeBetweenEvictionRuns(Duration.ofMillis(timeBetweenEvictionRuns));
    poolConfig.setNumTestsPerEvictionRun(numTestsPerEvictionRun);
    poolConfig.setBlockWhenExhausted(blockWhenExhausted);
    return poolConfig;
}

@Bean
public RedisConnectionFactory redisConnectionFactory(GenericObjectPoolConfig<StatefulRedisConnection<String, String>> poolConfiguration,
                                                     RedisSentinelConfiguration sentinelConfiguration) {
    LettucePoolingClientConfiguration clientConfig = LettucePoolingClientConfiguration.builder()
            .readFrom(ReadFrom.REPLICA_PREFERRED)
            .poolConfig(poolConfiguration)
            .clientName(MessageFormat.format("{0}{1}", getHosname(), COMMAND))
            .commandTimeout(Duration.ofMillis(timeout))
            .shutdownTimeout(Duration.ofMillis(shutdownTimeout))
            .build();
    return new LettuceConnectionFactory(sentinelConfiguration, clientConfig);
}
```

**Comment by mp911de** [comment] 2023-08-21 08:43
Thanks for letting me know. While we didn't get to the root cause, the issue is solved and I'm closing this one as it is not actionable any more.

**Closed by mp911de** 2023-08-21 08:43 UTC
Labels: status: works-as-designed
