### ISSUE TITLE
io.lettuce.core.protocol.RedisProtocolException: Invalid first byte: 34 (") at buffer index 1 decoding using RESP2

### ISSUE THREAD

**Issue by vampireslove** [lettuce-io/lettuce-core#1796] opened 2021-07-07 12:36 UTC
When high concurrency and the amount of value corresponding to the key is large, an exception is thrown. Invalid first byte: 34 (") at buffer index 1 decoding using RESP2, the entire client is unavailable, restart the service to recover。

====================================================
```
Caused by: io.lettuce.core.protocol.RedisProtocolException: Invalid first byte: 34 (") at buffer index 1 decoding using RESP2
        at io.lettuce.core.protocol.RedisStateMachine.readReplyType(RedisStateMachine.java:610) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:325) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:799) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:750) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:724) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:618) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:560) ~[lettuce-core-6.0.1.RELEASE.jar!/:6.0.1.RELEASE]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.57.Final.jar!/:4.1.57.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.57.Final.jar!/:4.1.57.Final]
        ... 1 more
```

**Comment by mp911de** [comment] 2021-07-07 13:03
There was a similar report with #1512. Care to upgrade to check whether the issue is already addressed? Other than that, we need a reproducer to diagnose the problem.

**Comment by mp911de** [comment] 2021-09-03 13:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-09-03 13:06 UTC
Labels: status: waiting-for-feedback
