### ISSUE TITLE
Requests begin failing with IllegalStateExceptions

### ISSUE THREAD

**Issue by joefruland** [lettuce-io/lettuce-core#1645] opened 2021-03-04 16:16 UTC
## Bug Report

We have now had a few instances in the last few months where our service using Lettuce has started throwing exceptions on every request to Redis. The stack trace that occurs can be found below. We are using an AWS Elasticache Redis cluster, and this seems to happen when our instance starts encountering intermittent network issues as we see HTTP requests to other services failing around the same time. The HTTP request errors stop, but the Lettuce client never recovers until the service is restarted. In case it's relevant, the Lettuce requests that are failing are all asynchronous EVAL requests. Please let me know if you need any more information.

#### Current Behavior

Lettuce client gets in a bad state where all requests start to fail with an IllegalStateException.

<details>
<summary>Stack trace</summary>

```java
java.lang.IllegalStateException: null
\tat io.lettuce.core.output.CommandOutput.set(CommandOutput.java:87)
\tat io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:441)
\tat io.lettuce.core.protocol.RedisStateMachine.handleInteger(RedisStateMachine.java:215)
\tat io.lettuce.core.protocol.RedisStateMachine.access$300(RedisStateMachine.java:41)
\tat io.lettuce.core.protocol.RedisStateMachine$State$Type.lambda$static$2(RedisStateMachine.java:63)
\tat io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:76)
\tat io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:166)
\tat io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:142)
\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:742)
\tat io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:706)
\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:701)
\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:622)
\tat io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
\tat java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

#### Environment

- Lettuce version(s): 5.3.5.RELEASE
- Redis version: 6.0.5 (Also occurred on Redis 5.0.0)

**Comment by mp911de** [comment] 2021-03-05 08:11
It looks like something has caused an offset in the protocol so it's no longer in sync. Either a command response was dropped or an command was completed and some leftovers remain in the receive buffer.

It's hard to diagnose these issues as it requires some detailed investigation over what happened before the first exception.

**Comment by joefruland** [comment] 2021-03-10 16:46
There were timeout exceptions making requests before the first IllegalStateExceptions, but that's about all I am able to gather from our logs.  Is it possible to detect the protocol becoming out of sync and at least drop the connection to cause a reconnect, or some other workaround to get us back in sync? I'm guessing it's impossible to prevent this entirely, but it sure would be helpful to not stay stuck in this state permanently.

**Comment by mp911de** [comment] 2021-03-11 08:40
It's pretty hard to diagnose where these issues stem from, especially on busy systems. We've seen that encoding errors could lead to such a state.

**Comment by joefruland** [comment] 2021-03-20 14:06
We had this happen again yesterday, and again it was immediately after a redis connection loss. Since my last post, we have upgraded to Lettuce v6.0.2.RELEASE. This has only happened after sudden connection loss, so I don't think there is any evidence that this is due to encoding errors on our side. Here are the exceptions that lead up to the constant stream of IllegalStateExceptions:

It always starts with timeout errors:
```
"io.lettuce.core.RedisCommandTimeoutException: Command timed out after 10 second(s)
\tat io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:53)
\tat io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:172)
\tat io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
\tat io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
\tat io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
\tat java.base/java.lang.Thread.run(Thread.java:834)
"
```
Followed by the Lettuce ConnectionWatchdog thread reconnecting traces:
```java
Reconnecting, last destination was ...
```
The ConnectionWatchdog thread failed to reconnect at least once during the reconnect while the network connection was still flaky:
```
Cannot reconnect to [...]: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
java.util.concurrent.CompletionException: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
\tat java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
\tat io.lettuce.core.RedisHandshake.lambda$tryHandshakeResp3$1(RedisHandshake.java:105)
\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
\tat io.lettuce.core.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:139)
\tat io.lettuce.core.protocol.AsyncCommand.completeExceptionally(AsyncCommand.java:132)
\tat io.lettuce.core.RedisHandshake.lambda$dispatch$5(RedisHandshake.java:224)
```

And a few requests failed with the following exception:
```
java.util.concurrent.CancellationException: null
\tat java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)
\tat io.lettuce.core.protocol.AsyncCommand.cancel(AsyncCommand.java:146)
\tat io.lettuce.core.protocol.AsyncCommand.cancel(AsyncCommand.java:180)
\tat io.lettuce.core.protocol.CommandWrapper.cancel(CommandWrapper.java:111)
\tat io.lettuce.core.protocol.CommandHandler.cancelCommands(CommandHandler.java:932)
\tat io.lettuce.core.protocol.CommandHandler.reset(CommandHandler.java:912)
\tat io.lettuce.core.protocol.CommandHandler.userEventTriggered(CommandHandler.java:253)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
\tat io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
\tat io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
\tat io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:365)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
\tat io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
\tat io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
\tat io.netty.channel.AbstractChannelHandlerContext.access$500(AbstractChannelHandlerContext.java:61)
\tat io.netty.channel.AbstractChannelHandlerContext$6.run(AbstractChannelHandlerContext.java:337)
\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:388)
\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
\tat java.base/java.lang.Thread.run(Thread.java:834)
```

A few seconds later we get a reconnected trace, and right after that we begin to see some IllegalStateExceptions. This does not happen on every request, but at high load there are a lot. The newest stack is only slightly different than the last:
```
java.lang.IllegalStateException: io.lettuce.core.output.StatusOutput does not support set(long)
\tat io.lettuce.core.output.CommandOutput.set(CommandOutput.java:107)
\tat io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:778)
\tat io.lettuce.core.protocol.RedisStateMachine.handleInteger(RedisStateMachine.java:404)
\tat io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206)
\tat io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334)
\tat io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295)
\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:815)
\tat io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:766)
\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:749)
\tat io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:632)
\tat io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:572)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
\tat io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
```
There were also several error traces like this from lettuce-epollEventLoop threads during this time:
```
null Unexpected exception during request: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```
This was followed by more reconnecting/reconnected traces until the connection was finally stable, at which point we continue to see the `IllegalStateExceptions` until the server is restarted. Any suggestions for trying to fix or work around this issue would be helpful.

**Comment by hulandianqing** [comment] 2021-04-08 03:41
I also encountered the same problem. I used Multi in the program, and Multi had 5 commands set, Set, Lpush, Set, DEL. I use Arthas to monitor the Commandoutput.set method. The following data is obtained at an abnormality.
```shell
#Monitoring command
watch *CommandOutput set "{target,params}" -x 5
```
```text
ts=2021-04-07 19:41:13; [cost=0.418405ms] result=@ArrayList[
    @StatusOutput[
        OK=@HeapByteBuffer[
            hb=@byte[][isEmpty=false;size=2],
            offset=@Integer[0],
            isReadOnly=@Boolean[false],
            bigEndian=@Boolean[true],
            nativeByteOrder=@Boolean[false],
            SPLITERATOR_CHARACTERISTICS=@Integer[16464],
            mark=@Integer[-1],
            position=@Integer[0],
            limit=@Integer[2],
            capacity=@Integer[2],
            address=@Long[0],
        ],
        codec=@ByteBufferCodec[
            INSTANCE=@ByteBufferCodec[INSTANCE],
            $VALUES=@ByteBufferCodec[][isEmpty=false;size=1],
            name=@String[INSTANCE],
            ordinal=@Integer[0],
        ],
        output=null,
        error=null,
    ],
    @Object[][
        @Long[1],
    ],
]
ts=2021-04-07 19:41:13; [cost=136.371134ms] result=@ArrayList[
    @MultiOutput[
        queue=@ArrayDeque[
            @TransactionalCommand[TransactionalCommand [type=SET, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.RedisPublisher$SubscriptionCommand]],
            @TransactionalCommand[TransactionalCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.RedisPublisher$SubscriptionCommand]],
        ],
        responses=@ArrayList[
            @String[OK],
            null,
        ],
        discarded=@Boolean[false],
        codec=@ByteBufferCodec[
            INSTANCE=@ByteBufferCodec[INSTANCE],
            $VALUES=@ByteBufferCodec[][isEmpty=false;size=1],
            name=@String[INSTANCE],
            ordinal=@Integer[0],
        ],
        output=null,
        error=null,
    ],
    @Object[][
        @Long[1],
    ],
]
```

There are only two commands in the Queue of MultiOutput, so I think the exception occurs on the processing of the fourth command set. And in response is normal, two OK an Integer is a value of 1. But now there is only one OK and a NULL.

The following is the data that is performed under normal circumstances.
```text
ts=2021-04-08 10:04:38; [cost=64.176924ms] result=@ArrayList[
    @MultiOutput[
        queue=@ArrayDeque[
            @TransactionalCommand[
                COUNT_UPDATER=@AtomicIntegerFieldUpdaterImpl[java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl@36587f50],
                command=@SubscriptionCommand[SubscriptionCommand [type=SET, output=StatusOutput [output=OK, error='null'], commandType=io.lettuce.core.protocol.Command]],
                count=@Integer[1],
                result=null,
                stack=@UniWhenComplete[java.util.concurrent.CompletableFuture$UniWhenComplete@111c4f0a],
                NIL=@AltResult[java.util.concurrent.CompletableFuture$AltResult@39d2bf87],
                useCommonPool=@Boolean[true],
                asyncPool=@ForkJoinPool[java.util.concurrent.ForkJoinPool@d568a91[Running, parallelism = 11, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]],
                SYNC=@Integer[0],
                ASYNC=@Integer[1],
                NESTED=@Integer[-1],
                SPINS=@Integer[256],
                UNSAFE=@Unsafe[sun.misc.Unsafe@3c6df879],
                RESULT=@Long[12],
                STACK=@Long[16],
                NEXT=@Long[16],
            ],
            @TransactionalCommand[
                COUNT_UPDATER=@AtomicIntegerFieldUpdaterImpl[java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl@36587f50],
                command=@SubscriptionCommand[SubscriptionCommand [type=DEL, output=IntegerOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]],
                count=@Integer[1],
                result=null,
                stack=@UniWhenComplete[java.util.concurrent.CompletableFuture$UniWhenComplete@28274dba],
                NIL=@AltResult[java.util.concurrent.CompletableFuture$AltResult@39d2bf87],
                useCommonPool=@Boolean[true],
                asyncPool=@ForkJoinPool[java.util.concurrent.ForkJoinPool@d568a91[Running, parallelism = 11, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]],
                SYNC=@Integer[0],
                ASYNC=@Integer[1],
                NESTED=@Integer[-1],
                SPINS=@Integer[256],
                UNSAFE=@Unsafe[sun.misc.Unsafe@3c6df879],
                RESULT=@Long[12],
                STACK=@Long[16],
                NEXT=@Long[16],
            ],
        ],
        responses=@ArrayList[
            @String[OK],
            @String[OK],
            @Long[1],
        ],
        discarded=@Boolean[false],
        codec=@ByteBufferCodec[
            INSTANCE=@ByteBufferCodec[
                INSTANCE=@ByteBufferCodec[INSTANCE],
                $VALUES=@ByteBufferCodec[][isEmpty=false;size=1],
                name=@String[INSTANCE],
                ordinal=@Integer[0],
            ],
            $VALUES=@ByteBufferCodec[][
                @ByteBufferCodec[INSTANCE],
            ],
            name=@String[INSTANCE],
            ordinal=@Integer[0],
        ],
        output=null,
        error=null,
    ],
    @Object[][
        @DirectByteBuffer[
            unsafe=@Unsafe[
                theUnsafe=@Unsafe[sun.misc.Unsafe@3c6df879],
                INVALID_FIELD_OFFSET=@Integer[-1],
                ARRAY_BOOLEAN_BASE_OFFSET=@Integer[16],
                ARRAY_BYTE_BASE_OFFSET=@Integer[16],
                ARRAY_SHORT_BASE_OFFSET=@Integer[16],
                ARRAY_CHAR_BASE_OFFSET=@Integer[16],
                ARRAY_INT_BASE_OFFSET=@Integer[16],
                ARRAY_LONG_BASE_OFFSET=@Integer[16],
                ARRAY_FLOAT_BASE_OFFSET=@Integer[16],
                ARRAY_DOUBLE_BASE_OFFSET=@Integer[16],
                ARRAY_OBJECT_BASE_OFFSET=@Integer[16],
                ARRAY_BOOLEAN_INDEX_SCALE=@Integer[1],
                ARRAY_BYTE_INDEX_SCALE=@Integer[1],
                ARRAY_SHORT_INDEX_SCALE=@Integer[2],
                ARRAY_CHAR_INDEX_SCALE=@Integer[2],
                ARRAY_INT_INDEX_SCALE=@Integer[4],
                ARRAY_LONG_INDEX_SCALE=@Integer[8],
                ARRAY_FLOAT_INDEX_SCALE=@Integer[4],
                ARRAY_DOUBLE_INDEX_SCALE=@Integer[8],
                ARRAY_OBJECT_INDEX_SCALE=@Integer[4],
                ADDRESS_SIZE=@Integer[8],
            ],
            arrayBaseOffset=@Long[16],
            unaligned=@Boolean[true],
            att=@DirectByteBuffer[
                unsafe=@Unsafe[sun.misc.Unsafe@3c6df879],
                arrayBaseOffset=@Long[16],
                unaligned=@Boolean[true],
                att=null,
                cleaner=null,
                $assertionsDisabled=@Boolean[true],
                fd=null,
                unused=@Byte[0],
                hb=null,
                offset=@Integer[0],
                isReadOnly=@Boolean[false],
                bigEndian=@Boolean[true],
                nativeByteOrder=@Boolean[false],
                SPLITERATOR_CHARACTERISTICS=@Integer[16464],
                mark=@Integer[-1],
                position=@Integer[0],
                limit=@Integer[16777216],
                capacity=@Integer[16777216],
                address=@Long[140416347275264],
            ],
            cleaner=null,
            $assertionsDisabled=@Boolean[true],
            fd=null,
            unused=@Byte[0],
            hb=null,
            offset=@Integer[0],
            isReadOnly=@Boolean[false],
            bigEndian=@Boolean[true],
            nativeByteOrder=@Boolean[false],
            SPLITERATOR_CHARACTERISTICS=@Integer[16464],
            mark=@Integer[-1],
            position=@Integer[0],
            limit=@Integer[2],
            capacity=@Integer[16777216],
            address=@Long[140416347275264],
        ],
    ],
]
```

I will still exist from 5.1 upgrades to 5.3. How should I check it next?
code:
``` java
connection.multi()
                    .doOnSuccess(o -> {
                        for (; ; ) {
                            Consumer commond = commonds.poll();
                           // callback
                            commond.accept(connection);
                        }
                    })
                    .flatMap(o -> connection.exec())
```

**Comment by mp911de** [comment] 2021-09-03 13:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue. Without a reproducer it's not possible to diagnose the problem.

**Closed by mp911de** 2021-09-03 13:07 UTC
Labels: status: waiting-for-feedback

**Comment by jessie-bigfacekitty** [comment] 2022-09-26 06:36
we had the same problem like [hulandianqing].
Has this issue been solved yet?
