### ISSUE TITLE
Lettuce tracing gaps/latency

### ISSUE THREAD

**Issue by andrewjamesbrown** [lettuce-io/lettuce-core#1979] opened 2022-01-26 23:50 UTC
#### Current Behavior

We are using datadog tracing, implemented as a wrapper around the Lettuce/Brave SPI.
The behaviour that we see, is that our Lettuce wrapper library (really just a thin facade around Lettuce), starts the trace, but occasionally we do not see a trace from Lettuce for another 600+ms.

This is a screenshot of "correct" behaviour:
![image](https://user-images.githubusercontent.com/6012516/151265905-07f17a71-4a95-456e-85d8-4805dbf52353.png)

While this is a screenshot of the "bad" behaviour:
![image](https://user-images.githubusercontent.com/6012516/151266017-da118623-df29-4a40-b2d5-393b56426a76.png)

From the caller's perspective, a Redis SET is taking 990ms, but Lettuce itself is only reporting e.g. 1.17ms in the span.
We're wondering where the extra time is going... is it queue time within Lettuce?  How can we measure that?  Can we measure the current size of the queue/stack? (I looked at metrics, but only see command completion timing/counts)

#### Input Code

Note that we use a `RedisKey`
caller:
```
fun recordData(token: String, value: String) {
  redisClient.set(token, value)
}
```

"write splitting" library
```
fun set(key: String, value: String): Boolean {
  return tracer.trace("WriteSplittingClient", "set") {
    val data = value.toByteArray()
    val status = primary.set(key, data)
    if (status) {
      secondary.asyncCommands().set(key, data, setArgs)
    }
    status
  }
}
```

delegate library (primary/secondary above)
```
val syncCommands = connection.sync()

fun asyncCommands(): RedisClusterAsyncCommands<String, ByteArray> {
  return asyncCommands 
}
  
fun set(key: String, value: ByteArray): Boolean {
  return tracer.trace("RealLettuceClient", "set") {
    try {
      val response = syncCommands.set(stringKey, value, SetArgs().px(RedisClient.DEFAULT_EXPIRATION_MILLIS))
      RedisClient.SUCCESS_RESPONSE.equals(response, ignoreCase = true)
    } catch (e: RedisException) {
      logger.warn(e, "Failed to set $key")
      false
    }
  }
}
```

#### Expected behavior/code

We're wondering where the time is spent - our library is a pretty thin wrapper around Lettuce (mainly to do write splitting and support cluster + standalone with a single API) - and it doesn't really do much between calling starting the trace and calling into Lettuce, so we don't know where the gaps are coming from (when they appear - this isn't 100% of the time)

#### Environment

- Lettuce version(s): 6.1.2.RELEASE
- Redis version: Elasticache 5.06

**Comment by mp911de** [comment] 2022-01-27 07:44
Lettuce starts command tracing once the command enters the I/O loop (`CommandHandler.write`). Everything before is not recorded. If you're seeing gaps then this might be caused by connection creation, e.g. if you're using Redis Cluster then the individual node connections need to be established first. Also, it is possible that a disconnected connection is being reconnected and it takes a while until this is completed.

You can generally subscribe to `EventBus` to listen for [connect/disconnect/connection activated/deactivated events](https://lettuce.io/core/release/reference/index.html#events).

**Comment by andrewjamesbrown** [comment] 2022-01-27 13:12
Thanks @mp911de!  That makes sense - we'll add an `EventBus` subscription to see what's going on there.
One more question, if I may.  On some other traces, we're seeing very long lettuce requests (see below).

![image](https://user-images.githubusercontent.com/6012516/151364476-e9bc87d4-ed67-4f7c-9b6b-edc2413e5cf6.png)

Each of the `redis.query MGET` is for a similar key, of the form `{CacheID_ValueType:ShardID}:######`.
`CacheID_ValueType` is static, `ShardID` is a value from 0-15, and `######` is a 6 digit integer.  Each of these will be routed to a different hash slot, possibly on a different Redis node in the cluster.

Are these long requests a result of becoming disconnected from a Redis Cluster node, or is something else going on here?  (and what telemetry is available to investigate?)

Thanks!

**Comment by mp911de** [comment] 2022-01-27 13:37
6 seconds is indeed quite an outlier in comparison to the other commands. You would need to enable debug logging to get more details. I cannot say why this is, note that debug logging can reveal that something else has happened with the command. It can also be that it just took that long.

**Comment by mp911de** [comment] 2022-07-11 06:59
Closing as this isn't actionable in the current state.

**Closed by mp911de** 2022-07-11 06:59 UTC
