### ISSUE TITLE
io.lettuce.core.RedisCommandTimeoutException when use @Transactional

### ISSUE THREAD

**Issue by hifishzlj** [lettuce-io/lettuce-core#1026] opened 2019-04-28 06:50 UTC
I'm using Lettuce with  Spring-data-redis,when i  use  @Transactional(propagation = Propagation.SUPPORTS, readOnly = true, rollbackFor = Exception.class) ,it will throw  Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out , but if use @Transactional(propagation = Propagation.REQUIRED, readOnly = false, rollbackFor = Exception.class)  ,it works well.
	
```java
@Override
	@Transactional(propagation = Propagation.REQUIRED, readOnly = false, rollbackFor = Exception.class)
	public void test() {
		redisOperations.execute(new SessionCallback<Object>() {
			@Override
			public Object execute(RedisOperations operations)
					throws DataAccessException {

				operations.multi();
				operations.watch("testKey");
				operations.opsForValue().set("testKey", "1");
				operations.exec();
				return null;
			}
		});
	}

	@Override
	@Transactional(propagation = Propagation.SUPPORTS, readOnly = true, rollbackFor = Exception.class)
	public void test2() {
		redisOperations.execute(new SessionCallback<Object>() {
			@Override
			public Object execute(RedisOperations operations)
					throws DataAccessException {

				operations.multi();
				operations.watch("testKey");
				operations.opsForValue().set("testKey", "1");
				operations.exec();
				return null;
			}
		});
	}
```

```
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1500 millisecond(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.multi(LettuceConnection.java:672)
	at org.springframework.data.redis.core.RedisTemplate.lambda$multi$21(RedisTemplate.java:1006)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.multi(RedisTemplate.java:1005)
```

**Comment by mp911de** [comment] 2019-04-29 08:18
Please inspect the debug/trace log when commands where sent. 

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

Please also note that the code above uses Spring Data Redis and this issue tracker is designated for issues related to Lettuce.

**Comment by mp911de** [comment] 2019-05-07 11:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-05-07 11:12 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
