### ISSUE TITLE
brpop when timeout is set 0 issue

### ISSUE THREAD

**Issue by giridharkannan** [lettuce-io/lettuce-core#2394] opened 2023-04-20 10:41 UTC
#### Current Behavior

When blocking indefinitely by specifying 0 for timeout, after lettuce internal timeout, any new command on the connection will be blocked indefinitely until we receive reply to the old BRPOP and we will also miss that message sent by REDIS server.

```
RedisClient c = RedisClient.create(RedisURI.Builder.redis("127.0.0.1", 6379).build());
RedisCommands<String, String> cmd = c.connect().sync();
while (true) {
    try {
        KeyValue<String, String> resp = cmd.brpop(0, QUEUE_KEY);
        System.out.println(">>" + resp.getValue());
    } catch (RedisCommandTimeoutException e) {
        /* Will not get response of this command until you get response for brpop
           and we will also miss the old response */
        cmd.ttl(QUEUE_KEY);
    }
}
```

#### Reason for the current behaviour

Old BRPOP command was not closed and we are piping new commands, which will be processed by REDIS server
only after an LPUSH

#### Expected behavior/code

Must not have client timeout for command BLPOP queue 0 or must at least close the connection rather than missing message, which is unacceptable

#### Environment

- Lettuce version(s): 6.2.4.RELEASE
- Redis version: 7.0.8

**Comment by mp911de** [comment] 2023-04-20 13:40
This is correct and the code works as designed. Assuming a command timeout of 60 seconds, the `BPROP 0 <some-key>` times out after 60 seconds and the calling code will see an exception.

However, the command is still running in the Redis server unless an element will be inserted into the list at `<some-key>`. Once this happens, Redis responds to the command that has timed out. Because the calling code has seen already a timeout exception, it doesn't see the pop result of `<some-key>`.

**Closed by mp911de** 2023-04-20 13:40 UTC

**Comment by giridharkannan** [comment] 2023-04-20 15:05
How could missing an message sent from REDIS server or making client to wait indefinitely after an Timeout be explained as "correct design"

If you feel it's not worth fixing the issue or not interested to fix the issue, I can completely understand, but saying this is no issue and this is the correct design is not acceptable.

Would the flow be designed this way if REDIS had given an command to come out of BLPOP? Also, how many people will know that blpop will miss messages after client timeout? Indirectly you are making people miss messages without even they realising what's happening.

**Comment by mp911de** [comment] 2023-04-20 15:21
The timeout setting and control over timeouts for commands is your responsibility. Lettuce cannot un-timeout a command and it cannot retract it from Redis. Therefore there's nothing we can do here. All `B*POP` and `BZPOP` commands fall into that category. We recommend using a reasonable timeout with `B*POP` commands and not using infinite Redis timeout as the Redis timeout doesn't match the client-side timeout.
