### ISSUE TITLE
Lots of new connection + COMMAND to slaves in Redis Cluster

### ISSUE THREAD

**Issue by marcdejonge** [lettuce-io/lettuce-core#816] opened 2018-07-23 06:30 UTC
#### Current Behavior

In the current Redis Cluster setup with 3 masters and 3 slaves, my java daemon is reconnecting to one of the slaves continuously. When performing a `tcpdump`, I constantly see a new connection being opened, a `COMMAND` being sent, then the connection closes again (the TCP FIN is initiated by the client).

#### Input Code

We're just using Spring Boot 2.0.0 with Lettuce to connect to Redis. This seems to be done by the library, since I don't have specific code here. Just using the RedisTemplates in a few places.

#### Expected behavior/code

I expected that the slaves are connected to once to get the cluster information and maybe a single connection to keep checking the status. I have no idea why it keeps opening and closing connections.

#### Environment

- Lettuce version(s): 5.0.2
- Redis version: 3.2.10

#### Additional context

We are using a lot of connections on a busy server. I'm not able to reproduce it locally when not performing a lot of actions.

**Comment by marcdejonge** [comment] 2018-07-23 06:47
I found this issue, which sound like a similar problem: https://github.com/lettuce-io/lettuce-core/issues/808

The issue is that we haven't done much configuring, just added the 3 master IP addresses to the configuration.

**Comment by mp911de** [comment] 2018-07-23 10:12
Possibly a duplicate of #808, depends on the actual configuration, so there can be two issues:

1. Lettuce periodically connects to cluster nodes to determine whether they are alive. In any case, connecting to any Redis server initiates a connection sequence which consists of a series of commands that need to be sent to determine the server's capabilities.

2. When you use Redis through Spring Data Redis with Cluster, then you might find that Redis Cluster connections are not shared. Please use either a connection pool as a temporary workaround or upgrade to Spring Data Redis 2.1M1 or later as Spring Data fixed a connection sharing issue with [DATAREDIS-731](https://jira.spring.io/browse/DATAREDIS-731). Without connection sharing, cluster connections are created on each command that is invoked on `RedisTemplate`.

**Comment by marcdejonge** [comment] 2018-07-23 10:18
Thank you for the quick response. I'll go upgrade the libraries and test this.

**Comment by marcdejonge** [comment] 2018-07-24 08:18
Just upgrading to 2.1M3 didn't work for me, it didn't change anything. Adding an explicit pool configuration did fix it though! I'm left with a question though: are the connection numbers in the config (minIdle, maxIdle and maxActive) for each node, or cumulative?

Other than that, I would say this is an improvement:
![image](https://user-images.githubusercontent.com/354901/43125615-d6dde0da-8f2a-11e8-8191-4e1ba49d0870.png)

**Comment by mp911de** [comment] 2018-07-24 09:59
minIdle, maxIdle and maxActive are the numbers of logical connections. A Lettuce Cluster connection consists itself then of multiple physical connections:

Consider:

(number of nodes *n* x 2) + 1

That's the total maximum of physical connections that are bundled under a logical connection.

Closing this ticket as the issue is solved externally.

**Closed by mp911de** 2018-07-24 09:59 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage

**Comment by flowinglight** [comment] 2021-02-21 23:58
hi @marcdejonge what config did you use to get around of this issue? We have seen the same problem now and updating versions doesn't help either.
