### ISSUE TITLE
UnsupportedOperationException in ValueSetOutput.set

### ISSUE THREAD

**Issue by markusheiden** [lettuce-io/lettuce-core#1540] opened 2020-11-30 20:27 UTC
#### Current Behavior

<details>
<summary>
ValueSetOutput not initialized correctly when accessing the set method.
Apparently the initialization with Collections.emptySet() has not been changed before calling the set method.

</summary>

```java
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: java.lang.UnsupportedOperationException
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.convertLettuceAccessException(LettuceSetCommands.java:520) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:245) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.sMembers(DefaultedRedisConnection.java:791) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.lambda$members$10(DefaultSetOperations.java:214) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:214) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:152) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:129) ~[spring-session-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.data.redis.RedisIndexedSessionRepository.cleanupExpiredSessions(RedisIndexedSessionRepository.java:407) ~[spring-session-data-redis-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: io.lettuce.core.RedisException: java.lang.UnsupportedOperationException
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:134) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:79) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at com.sun.proxy.$Proxy182.smembers(Unknown Source) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:243) ~[spring-data-redis-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	... 17 more
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractCollection.add(AbstractCollection.java:251) ~[?:?]
	at io.lettuce.core.output.ValueSetOutput.set(ValueSetOutput.java:41) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:457) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.handleBytes(RedisStateMachine.java:274) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.access$000(RedisStateMachine.java:41) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.lambda$static$5(RedisStateMachine.java:66) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:76) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:166) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:142) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:742) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:706) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:692) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:622) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591) ~[lettuce-core-5.3.5.RELEASE.jar:5.3.5.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.54.Final-linux-x86_64.jar:4.1.54.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.54.Final-linux-x86_64.jar:4.1.54.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.54.Final-linux-x86_64.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.54.Final.jar:4.1.54.Final]
	... 1 more
```
</details>

#### Input Code

<details>
<summary>Input Code</summary>
Use of Spring Data Redis Session for session persistence. 
Using connection pooling.
</details>

#### Expected behavior/code
No exception.

#### Environment

- Lettuce version(s): 5.35.RELEASE
- Redis version: GCP

#### Possible Solution
Add init check in set method too?

**Comment by mp911de** [comment] 2020-12-01 07:19
Care to upgrade to Lettuce 6 to verify whether the issue persists? For some reason, the initializing method isn't called. Also, are you able to reliably reproduce the issue so we can investigate the cause?

**Comment by markusheiden** [comment] 2020-12-01 08:59
Sorry, currently we are not able to update to Spring Boot 2.4 / Lettuce 6 because of some failing tests. So I cannot test this in production. Locally I did not have this problem yet, but I will try to reproduce it.

**Comment by markusheiden** [comment] 2020-12-03 09:18
I was not able to reproduce it locally, sorry.

**Comment by mp911de** [comment] 2020-12-22 15:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-12-22 15:10 UTC
Labels: status: waiting-for-feedback
