### ISSUE TITLE
why reids client many threads is TIMED_WAITING status

### ISSUE THREAD

**Issue by chinadeng** [lettuce-io/lettuce-core#2089] opened 2022-04-30 13:43 UTC
## Bug Report

At any given time approximately 300~400 concurrent request will be made to redis server. Out of all, 90% of threads goes to TIMED_WAITING state; Looking at ThreadDump, all of them are waiting..but redis server  connectd client is 18. The top command  show redis server is very low load average ,CPU 、IO and Memory are normal .  My application is based on spring boot 2.3, redis client  sharenativeconnetcion is default value ture,why this happen  @mp911de 

#### Current Behavior

<details>
<summary>Stack trace</summary>
catalina-exec-441" #556 daemon prio=5 os_prio=0 tid=0x00007f2fadd13000 nid=0x1a07 waiting on condition [0x00007f2f46be5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f3ae3688> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1695)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1775)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at io.lettuce.core.protocol.AsyncCommand.await(AsyncCommand.java:81)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:117)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:131)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:79)
	at com.sun.proxy.$Proxy285.get(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:66)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:266)
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)
</details>

#### Input Code

<details>
<summary>Input Code</summary>
my config:
spring.redis.cluster.lettuce.pool.max-actvie =100

spring.redis.cluster.lettuce.pool.max-waite=10000

spring.redis.cluster.lettuce.pool.max-idle=8

spring.redis.cluster.lettuce.pool.min-idel=1

spring.redis.cluster.lettuce.pool.time-between-eviction-runs =5000

redistemplate.opsforvalue.set(key,value);

</details>

#### Environment
-spring boot 2.3
- Lettuce version(s): [e.g. 5.3.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 5.0.9]

**Comment by chinadeng** [comment] 2022-05-06 09:55
what problem in my application?

**Comment by mp911de** [comment] 2022-07-01 14:13
`TIMED_WAITING` is the state when a thread is blocked and awaits a response from a future or a lock. To diagnose the issue, we would require a proper reproducer.

**Comment by mp911de** [comment] 2022-11-22 10:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-11-22 10:36 UTC
Labels: status: waiting-for-feedback
