### ISSUE TITLE
RedisCommandTimeoutException occurs Randomly

### ISSUE THREAD

**Issue by Joan7** [lettuce-io/lettuce-core#1250] opened 2020-03-30 10:04 UTC
Current Behavior
We're using Redis 5.0.3 with Spring Data Redis 2.2.5.RELEASE as a client. Lettuce 5.2.2, with **io.lettuce.core.protocol: TRACE**, but when getting the following exceptions quite often, but at random times, there is no log from **io.lettuce.core.protocol** and **i.l.c.EpollProvider,i.l.c.KqueueProvider** ,my usage is referring RedisRateLimiter -`Flux<List<Long>> flux = this.redisTemplate.execute(this.script, Arrays.asList("tokenKey", "timestampKey"), args);`,exceptions throw from `
return flux.onErrorResume((throwable) -> {
                    this.log.error("...reddis execute error..."+throwable.toString());
                    return Flux.just(Arrays.asList(1L, -1L));
                })
`:

> ERROR, c.c.w.c.g.f.CustomerRedisRateLimiter, lettuce-eventExecutorLoop-2-1, 203600198, , CustomerRedisRateLimiter.java, 187, lambda$isAllowed2$1 ...reddis execute error...org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 3 second(s)

**Comment by mp911de** [comment] 2020-03-30 12:54
Timeout exceptions are a protection for your system and not the cause. Please inspect how long the script execution takes and which commands were issued earlier to investigate the actual cause.

**Comment by Joan7** [comment] 2020-03-30 13:34
> Timeout exceptions are a protection for your system and not the cause. Please inspect how long the script execution takes and which commands were issued earlier to investigate the actual cause.

The normal cases are < 10ms and I set the timeout 5s, no commands issued earlier. The content in [] are not shown when the timeout occurs

```
2020-03-30 11:03:15.144, , , INFO, c.c.w.c.g.f.CustomerRedisRateLimiter, boundedElastic-56, 17948, , CustomerRedisRateLimiter.java, 179, isAllowed2 ...Start redis execute...
[

2020-03-30 11:03:15.268, , , INFO, i.l.c.EpollProvider, boundedElastic-56, 18072, , EpollProvider.java, 68, <clinit> Starting without optional epoll library
2020-03-30 11:03:15.270, , , INFO, i.l.c.KqueueProvider, boundedElastic-56, 18074, , KqueueProvider.java, 70, <clinit> Starting without optional kqueue library
2020-03-30 11:03:15.296, , , DEBUG, i.l.c.p.CommandHandler, lettuce-nioEventLoop-4-1, 18100, , CommandHandler.java, 162, channelRegistered [channel=0x75ecc270, [id: 0x7af4f065] (inactive), chid=0x1] channelRegistered()
.
.
.
2020-03-30 11:03:15.946, , , DEBUG, i.l.c.p.DefaultEndpoint, lettuce-nioEventLoop-4-1, 18750, , DefaultEndpoint.java, 153, write [channel=0x75ecc270, /10.79.98.121:50410 -> /10.240.214.114:7379, epid=0x1] write() done
2020-03-30 11:03:16.132, , , DEBUG, i.l.c.p.CommandHandler, lettuce-nioEventLoop-4-1, 18936, , CommandHandler.java, 544, channelRead [channel=0x75ecc270, /10.79.98.121:50410 -> /10.240.214.114:7379, chid=0x1] Received: 12 bytes, 1 commands in the stack
2020-03-30 11:03:16.133, , , TRACE, i.l.c.p.CommandHandler, lettuce-nioEventLoop-4-1, 18937, , CommandHandler.java, 559, channelRead [channel=0x75ecc270, /10.79.98.121:50410 -> /10.240.214.114:7379, chid=0x1] Buffer: *2
:1
:1
2020-03-30 11:03:16.133, , , DEBUG, i.l.c.p.CommandHandler, lettuce-nioEventLoop-4-1, 18937, , CommandHandler.java, 590, decode [channel=0x75ecc270, /10.79.98.121:50410 -> /10.240.214.114:7379, chid=0x1] Stack contains: 1 commands
2020-03-30 11:03:16.133, , , DEBUG, i.l.c.p.RedisStateMachine, lettuce-nioEventLoop-4-1, 18937, , RedisStateMachine.java, 94, decode Decode LatencyMeteredCommand [type=EVAL, output=NestedMultiOutput [output=[], error='null'], commandType=io.lettuce.core.RedisPublisher$SubscriptionCommand]
2020-03-30 11:03:16.134, , , DEBUG, i.l.c.p.RedisStateMachine, lettuce-nioEventLoop-4-1, 18938, , RedisStateMachine.java, 191, decode Decoded LatencyMeteredCommand [type=EVAL, output=NestedMultiOutput [output=[1, 1], error='null'], commandType=io.lettuce.core.RedisPublisher$SubscriptionCommand], empty stack: true
]
2020-03-30 11:03:16.138, , , INFO, c.c.w.c.g.f.CustomerRedisRateLimiter, lettuce-nioEventLoop-4-1, 18942, , CustomerRedisRateLimiter.java, 195, lambda$isAllowed2$3 ...End redis execute...
```

**Comment by mp911de** [comment] 2020-03-31 07:58
According to the timestamps, the sequence is no longer than 1 second. So there is no timeout happening or do I miss something?

**Comment by Joan7** [comment] 2020-04-01 02:23
> According to the timestamps, the sequence is no longer than 1 second. So there is no timeout happening or do I miss something?

yes, I just not make that clear, the log are the normal case when deployed redis time is only **10ms**,but when timeout happened what I can get from log is nothing
As you mentioned, there is no commands executed even EpollProvider

> which commands were issued earlier 

logs only outside "[]" from above, no content which start from  "i.l.c.EpollProvider" to i.l.c.p.RedisStateMachine

**Comment by mp911de** [comment] 2020-04-07 12:06
Can you provide a reproducer? Right now we don't have sufficient information to diagnose the issue.

**Comment by Joan7** [comment] 2020-04-07 12:12
> Can you provide a reproducer? Right now we don't have sufficient information to diagnose the issue.

No, but it happened almost everyday, is there any other threadlevel log I may open for checking, or any other debug method you suggest for this seems thread hanging cases, I checked my cpu and mem seems no abonormal ,BTW service was deployed in container(kubernetes)

**Comment by Joan7** [comment] 2020-04-07 12:25
I can submit a sample repo

**Comment by mp911de** [comment] 2020-06-08 09:56
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-06-08 09:56 UTC
Labels: type: bug
