### ISSUE TITLE
NPE during Sentinel topology change

### ISSUE THREAD

**Issue by vleushin** [lettuce-io/lettuce-core#666] opened 2017-12-12 15:20 UTC
lettuce-5.0.0.RELEASE in Kubernetes in 1.8.0 . We are testing redis+sentinel setup. So far so good but we stumble upon one problem with lettuce: getting "Error during background refresh" after we kill master node. Sentinel switches master just fine. And lettuce gets stuck during topology change.

```
exceptionClass
java.lang.NullPointerException

exceptionStackTrace
io.lettuce.core.masterslave.MasterSlaveTopologyRefresh.getNodeSpecificViews(MasterSlaveTopologyRefresh.java:111)
io.lettuce.core.masterslave.MasterSlaveTopologyRefresh.getNodes(MasterSlaveTopologyRefresh.java:77)
io.lettuce.core.masterslave.MasterSlave.lambda$connectSentinel$0(MasterSlave.java:172)
java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
io.lettuce.core.masterslave.SentinelTopologyRefresh.lambda$null$2(SentinelTopologyRefresh.java:149)
io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
java.lang.Thread.run(Thread.java:748)

full_message
Error during background refresh

level
3

loggerName
io.lettuce.core.masterslave.MasterSlave
```

Any thoughts?

**Comment by vleushin** [comment] 2017-12-12 15:27
Update: I'm trying to reproduce problem locally with two empty Redises and one Sentinel. It is reproducible, but not stable -- I'm not able to tell how to exactly reproduce. I get same exception (in about 10% cases), but it does not gets stuck. On Kubernetes environment it gets stuck everytime. (One Kubernetes specific is that new Redis instances always have new ip)

I use following commands:

`redis-server`
`redis-server --port 6380 --slaveof 127.0.0.1 6379`
```
sentinel monitor mymaster 127.0.0.1 6379 1
sentinel down-after-milliseconds mymaster 10000
```

**Comment by mp911de** [comment] 2017-12-12 15:34
That's a duplicate of #659. The issue is reproducible if a Redis node (master or slave) is known to Sentinel but cannot be connected to run a `PING` response. It's fixed with `5.0.2.BUILD-SNAPSHOT`. Care to give the snapshot version a spin?

**Comment by vleushin** [comment] 2017-12-12 15:36
@mp911de Thanks! I will give it a try and write you back!

**Comment by vleushin** [comment] 2017-12-12 15:40
Sorry for likely stupid question, but where can I find or build `5.0.2.BUILD-SNAPSHOT` version?

**Comment by mp911de** [comment] 2017-12-12 15:52
It's available from http://oss.sonatype.org/content/repositories/snapshots.

```xml
<dependency>
  <groupId>io.lettuce</groupId>
  <artifactId>lettuce-core</artifactId>
  <version>5.0.2.BUILD-SNAPSHOT</version>
</dependency>

<repositories>
  <repository>
    <id>sonatype-nexus-snapshots</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by vleushin** [comment] 2017-12-12 20:46
Thanks. On `5.0.2.BUILD-SNAPSHOT` in Kubernetes I get endless loop of this:
```
java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.233.98.107:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_151]
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync$1(AbstractRedisClient.java:275) ~[lettuce-core-5.0.2.BUILD-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:600) ~[netty-transport-native-epoll-4.1.16.Final-linux-x86_64.jar:4.1.16.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[netty-transport-native-epoll-4.1.16.Final-linux-x86_64.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.233.98.107:6379
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:598) ~[netty-transport-native-epoll-4.1.16.Final-linux-x86_64.jar:4.1.16.Final]
	... 8 more
2017-12-12 20:40:45.802 [WARN] [lettuce-epollEventLoop-46-3] [i.l.c.m.MasterSlaveTopologyRefresh] - Unable to connect to RedisURI [host='10.233.101.45', port=6379]
java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.233.101.45:6379
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_151]
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync$1(AbstractRedisClient.java:275) ~[lettuce-core-5.0.2.BUILD-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:600) ~[netty-transport-native-epoll-4.1.16.Final-linux-x86_64.jar:4.1.16.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[netty-transport-native-epoll-4.1.16.Final-linux-x86_64.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) ~[netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /10.233.101.45:6379
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:598) ~[netty-transport-native-epoll-4.1.16.Final-linux-x86_64.jar:4.1.16.Final]
	... 8 more
```

and no topology update.

**Comment by mp911de** [comment] 2017-12-12 21:15
Please make sure you can connect to `10.233.101.45:6379` from your pod. I think we could omit the stack trace. Having a warning gives an indication when tracing down issues.

**Comment by vleushin** [comment] 2017-12-12 21:28
You cannot connect to it because it does not exist anymore (this is Kubernetes "feature"). After I kill pod with redis master, it is gone and new pod is started with different IP and clean state. Previous slave becomes master and new pod becomes slave.

Logs from sentinel look like this:
```
1:X 12 Dec 20:40:29.929 # +sdown master redis-service 10.233.98.107 6379
1:X 12 Dec 20:40:29.947 # +new-epoch 6
1:X 12 Dec 20:40:29.951 # +vote-for-leader 1af87494eea2f6b28ff59fbd59844586b19d14f9 6
1:X 12 Dec 20:40:29.985 # +odown master redis-service 10.233.98.107 6379 #quorum 3/2
1:X 12 Dec 20:40:29.985 # Next failover delay: I will not start a failover before Tue Dec 12 20:42:30 2017
1:X 12 Dec 20:40:30.631 # +config-update-from sentinel 1af87494eea2f6b28ff59fbd59844586b19d14f9 10.233.101.4 26379 @ redis-service 10.233.98.107 6379
1:X 12 Dec 20:40:30.632 # +switch-master redis-service 10.233.98.107 6379 10.233.101.47 6379
1:X 12 Dec 20:40:30.633 * +slave slave 10.233.101.45:6379 10.233.101.45 6379 @ redis-service 10.233.101.47 6379
1:X 12 Dec 20:40:30.633 * +slave slave 10.233.98.107:6379 10.233.98.107 6379 @ redis-service 10.233.101.47 6379
1:X 12 Dec 20:40:40.659 # +sdown slave 10.233.101.45:6379 10.233.101.45 6379 @ redis-service 10.233.101.47 6379
1:X 12 Dec 20:40:40.660 # +sdown slave 10.233.98.107:6379 10.233.98.107 6379 @ redis-service 10.233.101.47 6379
1:X 12 Dec 20:43:01.350 * +slave slave 10.233.98.122:6379 10.233.98.122 6379 @ redis-service 10.233.101.47 6379
```

**Comment by mp911de** [comment] 2017-12-13 07:05
Lettuce should stop attempting to connect the old node (`10.233.101.45`) once it's gone. Plase make sure that sentinel does not report the node anymore via `SENTINEL MASTER redis-service` and `SENTINEL SLAVES redis-service`.

**Comment by vleushin** [comment] 2017-12-13 08:48
`10.233.101.45` is indeed in sentinel slave list. However, it's normal (according to https://redis.io/topics/sentinel ):
 
>Sentinels never forget about slaves of a given master, even when they are unreachable for a long time. This is useful, because Sentinels should be able to correctly reconfigure a returning slave after a network partition or a failure event.
Moreover, after a failover, the failed over master is virtually added as a slave of the new master, this way it will be reconfigured to replicate with the new master as soon as it will be available again.
However sometimes you want to remove a slave (that may be the old master) forever from the list of slaves monitored by Sentinels.
In order to do this, you need to send a SENTINEL RESET mastername command to all the Sentinels: they'll refresh the list of slaves within the next 10 seconds, only adding the ones listed as correctly replicating from the current master INFO output.

So we have to use RESET command to remove it. It raises a lot of questions (like when and who should call it?). Any thoughts?

**Comment by mp911de** [comment] 2017-12-13 08:59
I think the problem you're running in is caused because of Kubernetes' nature. In a static hardware/VM setup, the node would come back with the same IP address. In your case, the node is coming back with a new IP address. That's an task to be solved with your specific setup.

Or seeing it from a different perspective: Redis Sentinel isn't made for use cases where you change the IP address when recovering from a crash.

**Comment by vleushin** [comment] 2017-12-13 09:14
Yes, in Kubernetes you get new IPs. But keeping dead unreachable slaves in hope they will come back sometime in future is Sentinels intended feature, in our case they just will not come back (and we will eventually do RESET, when everything stabilized). But during this time, lettuce is not able to refresh topology, because it expects all slaves to be reachable? Even on static hardware you can restart or turn off machine for maintenance -- you will get same problem, no?

**Comment by mp911de** [comment] 2017-12-13 10:51
You'll get the same issue on regular hardware. I wonder whether there is additional details in Sentinel that allows to derive whether a node is reachable. 
In any case, let's close this issue as it's a duplicate of an already solved ticket. Care to open a new ticket along output of `SENTINEL master redis-service` and `SENTINEL slaves redis-service`?

There is already a check in place for down flags (`s_down`, `o_down`, `disconnected`) but maybe it's not sufficient.

**Closed by mp911de** 2017-12-13 10:51 UTC
Labels: duplicate, feedback requested
