### ISSUE TITLE
IllegalStateException: null after the network is disconnected and recovered

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#1753] opened 2021-05-15 02:02 UTC
## Bug Report

I found the error: IllegalStateException: null throw by CommandOutput class in our service after the network of client host is disconnected and recovered;

I restart this client and it runs well

what confused me is that this exception is throw by CommandOutput class not by its subclass

**there is the error stack：(get command)**
Caused by: java.lang.IllegalStateException: null
    at io.lettuce.core.output.CommandOutput.set(CommandOutput.java:85)
    at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:358)
    at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:139)
    at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:716)
    at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:680)
    at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:675)
    at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:596)
    at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)

my service would create 2 lettuce instance(cluster mode) and select the least used one to handle request 

#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version:  4.0.11
- Netty version: 4.1.47.Final

**Comment by mp911de** [comment] 2021-05-17 07:08
`CommandOutput` provides template methods to decode individual Redis responses. For some reason, the command output doesn't match the command that is being decoded. Can you reproduce the issue? Also, please upgrade to a more recent version of Lettuce.

**Comment by StillerRen** [comment] 2021-05-19 08:09
sorry, I can't reproduce, just 1 host met this problem.

Do you think the reason is that the data in the channel is out of order?

**Comment by mp911de** [comment] 2021-06-09 07:33
Closing since this ticket isn't actionable in any way.

**Closed by mp911de** 2021-06-09 07:33 UTC
Labels: status: waiting-for-feedback
