### ISSUE TITLE
Spring-Lettuce : Taking more than 10 min to reconnect on azure if we reboot redis

### ISSUE THREAD

**Issue by upen4a3** [lettuce-io/lettuce-core#1465] opened 2020-10-19 20:59 UTC
We are using Lettuce-5.3.1-RELEASE(spring-data-redis-2.3.1-RELEASE) in reactive approach.When we reboot redis on azure it is taking more than 10 min approximately 15 min to establish connection again, but when we test locally reconnection time is less than 5 min.Do we have. to add any additional properties for force reconnect on either in spring boot or azure side.

This are some of the repeated logs we have seen and also sometimes timeout exceptions.

```
19-10-2020 15:57:33.994 DEBUG r.n.http.server.HttpServerOperations  [id: 0x6ef9d608, L:/10.0.0.111:8080 - R:/10.0.0.6:54100] Increasing pending responses, now 1 
19-10-2020 15:57:33.994 DEBUG reactor.netty.http.server.HttpServer  [id: 0x6ef9d608, L:/10.0.0.111:8080 - R:/10.0.0.6:54100] Handler is being applied: org.springframework.http.server.reactive.ReactorHttpHandlerAdapter@47bcb563 
19-10-2020 15:57:33.999 DEBUG r.n.http.server.HttpServerOperations  [id: 0x6ef9d608, L:/10.0.0.111:8080 - R:/10.0.0.6:54100] Detected non persistent http connection, preparing to close 
19-10-2020 15:57:34.000 DEBUG r.n.http.server.HttpServerOperations  [id: 0x6ef9d608, L:/10.0.0.111:8080 - R:/10.0.0.6:54100] Last HTTP response frame 
19-10-2020 15:57:34.000 DEBUG r.n.http.server.HttpServerOperations  [id: 0x6ef9d608, L:/10.0.0.111:8080 - R:/10.0.0.6:54100] Last HTTP packet was sent, terminating the channel 
19-10-2020 15:58:03.994 DEBUG r.n.http.server.HttpServerOperations  [id: 0xbfe5c284, L:/10.0.0.111:8080 - R:/10.0.0.6:54626] New http connection, requesting read 
19-10-2020 15:58:03.994 DEBUG r.netty.channel.BootstrapHandlers  [id: 0xbfe5c284, L:/10.0.0.111:8080 - R:/10.0.0.6:54626] Initialized pipeline DefaultChannelPipeline{(BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpServerCodec), (reactor.left.httpTrafficHandler = reactor.netty.http.server.HttpTrafficHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)} 
19-10-2020 15:58:03.994 DEBUG r.n.http.server.HttpServerOperations  [id: 0xbfe5c284, L:/10.0.0.111:8080 - R:/10.0.0.6:54626] Increasing pending responses, now 1 
19-10-2020 15:58:03.995 DEBUG reactor.netty.http.server.HttpServer  [id: 0xbfe5c284, L:/10.0.0.111:8080 - R:/10.0.0.6:54626] Handler is being applied: org.springframework.http.server.reactive.ReactorHttpHandlerAdapter@47bcb563 
19-10-2020 15:58:04.003 DEBUG r.n.http.server.HttpServerOperations  [id: 0xbfe5c284, L:/10.0.0.111:8080 - R:/10.0.0.6:54626] Detected non persistent http connection, preparing to close 
19-10-2020 15:58:04.004 DEBUG r.n.http.server.HttpServerOperations  [id: 0xbfe5c284, L:/10.0.0.111:8080 - R:/10.0.0.6:54626] Last HTTP response frame 
 
```

**Comment by mp911de** [comment] 2020-10-20 06:51
Looks like a duplicate of #1466. `HttpServerOperations` isn't related to Lettuce.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2020-11-14 17:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-11-14 17:47 UTC
Labels: status: waiting-for-feedback, type: bug
