### ISSUE TITLE
springboot+lettuce occurs a OutOfMemory Error

### ISSUE THREAD

**Issue by linww** [lettuce-io/lettuce-core#1834] opened 2021-08-27 08:09 UTC
## Bug Report
    My project is using springboot 2.0.9.RELEASE, it connects to redis cluster by lettuce which is provided by spring-boot-starter-data-redis. it occured a OutOfMemoryError this morning, but I cannot reproduce it.

#### Current Behavior
![image](https://user-images.githubusercontent.com/10493366/131094088-6443b3f0-8069-451b-b9b5-626bd6eb058e.png)

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```
 I dump the heap file, and open it with Eclise Memory Analyzer, this is reported by Eclipse Memory Analyzer.
![image](https://user-images.githubusercontent.com/10493366/131094280-6aac5884-3b40-48c3-a1be-6bc0b82e4eb2.png)
![image](https://user-images.githubusercontent.com/10493366/131094364-9631e9f0-9ab1-4427-a954-fc68b2e99393.png)
![image](https://user-images.githubusercontent.com/10493366/131094411-8ac7b517-520c-4841-aa5d-d68c95ccda13.png)
![image](https://user-images.githubusercontent.com/10493366/131094529-e7b40118-eb12-4827-b845-6aa60cab37b0.png)
and this is the configurations about redis:
![image](https://user-images.githubusercontent.com/10493366/131095139-0a4d8f12-b91c-4834-83ea-b8627d19ff13.png)

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment] 2021-09-03 12:47
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2022-07-11 06:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-07-11 06:59 UTC
Labels: status: waiting-for-feedback
