### ISSUE TITLE
Why "Connecting to Redis at" cost so long time? why timeout is ignored?

### ISSUE THREAD

**Issue by mylesliechen** [lettuce-io/lettuce-core#2071] opened 2022-04-08 07:55 UTC
## Bug Report

why connect to redis cost so long time?about 2 min? and at last it not TimeoutException? that's why ??

<details>
<summary>Stack trace</summary>

```java

2022-04-07 19:58:09.384 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.l.core.cluster.RedisClusterClient      : connectCluster([RedisURI [host='redis-cluster.com', port=6379]]) (RedisClusterClient.java:505)
2022-04-07 19:58:09.385 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.l.c.c.RoundRobinSocketAddressSupplier  : Resolved SocketAddress 110.231.106.123:6379 using for Cluster node 1ebd89211a4587092a9c59f0677dbf6b9cb7fbee (RoundRobinSocketAddressSupplier.java:77)
2022-04-07 19:58:09.402 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisClient              : Connecting to Redis at 110.231.106.123:6379 (AbstractRedisClient.java:257)
2022-04-07 20:00:43.298 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisChannelHandler      : dispatching command AsyncCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command] (RedisChannelHandler.java:120)
2022-04-07 20:00:43.299 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x16cfe9ea, /127.0.0.1:43182 -> /110.231.106.123:6379, epid=0x17b81] write() writeAndFlush command ClusterCommand [command=AsyncCommand [type=COMMAND, output=ArrayOutput [output=[], error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=5] (DefaultEndpoint.java:313)
2022-04-07 20:00:43.299 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x16cfe9ea, /127.0.0.1:43182 -> /110.231.106.123:6379, epid=0x17b81] write() done (DefaultEndpoint.java:129)
2022-04-07 20:00:43.309 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisChannelHandler      : dispatching command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] (RedisChannelHandler.java:120)
2022-04-07 20:00:43.309 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.l.c.c.PooledClusterConnectionProvider  : getConnection(READ, 13142) (PooledClusterConnectionProvider.java:100)
2022-04-07 20:00:43.310 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] ider$DefaultClusterNodeConnectionFactory : Resolved SocketAddress 110.231.64.138:6379 using for Cluster node at 110.231.64.138:6379 (AbstractClusterNodeConnectionFactory.java:84)
2022-04-07 20:00:43.310 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.l.core.cluster.RedisClusterClient      : connectToNodeAsync(110.231.64.138:6379 at 110.231.64.138:6379) (RedisClusterClient.java:425)
2022-04-07 20:00:43.311 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] ider$DefaultClusterNodeConnectionFactory : Resolved SocketAddress 110.231.64.138:6379 using for Cluster node at 110.231.64.138:6379 (AbstractClusterNodeConnectionFactory.java:84)
2022-04-07 20:00:43.311 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisClient              : Connecting to Redis at 110.231.64.138:6379 (AbstractRedisClient.java:257)
2022-04-07 20:00:43.316 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisChannelHandler      : close() (RedisChannelHandler.java:100)
2022-04-07 20:00:43.316 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x16cfe9ea, /127.0.0.1:43182 -> /110.231.106.123:6379, epid=0x17b81] close() (DefaultEndpoint.java:480)
2022-04-07 20:00:43.317 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisChannelHandler      : close() (RedisChannelHandler.java:100)
2022-04-07 20:00:43.317 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.l.core.cluster.ClusterNodeEndpoint     : [channel=0x755dedf0, /127.0.0.1:48434 -> /110.231.64.138:6379, epid=0x17bf5] close() (ClusterNodeEndpoint.java:64)
2022-04-07 20:00:43.318 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x755dedf0, /127.0.0.1:48434 -> /110.231.64.138:6379, epid=0x17bf5] close() (DefaultEndpoint.java:480)
2022-04-07 20:00:43.602 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] io.lettuce.core.RedisChannelHandler      : dispatching command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] (RedisChannelHandler.java:120)
2022-04-07 20:00:43.603 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.l.c.c.PooledClusterConnectionProvider  : getConnection(READ, 14231) (PooledClusterConnectionProvider.java:100)
2022-04-07 20:00:43.603 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x5ea4df00, /127.0.0.1:48468 -> /110.231.64.138:6379, epid=0x17bf9] write() writeAndFlush command ClusterCommand [command=AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=5] (DefaultEndpoint.java:313)
2022-04-07 20:00:43.603 DEBUG 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] i.lettuce.core.protocol.DefaultEndpoint  : [channel=0x5ea4df00, /127.0.0.1:48468 -> /110.231.64.138:6379, epid=0x17bf9] write() done (DefaultEndpoint.java:129)
2022-04-07 20:00:43.608  INFO 30104 --- [http-nio-8081-exec-270] [BAE23649E981740C] j.b.a.s.BucketPolicyAuthorizationService : check bucketPolicy result is [DefaultDeny] (BucketPolicyAuthorizationService.java:101)

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
redis config:
  redis:
    cluster:
      nodes: 
    password: password
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        max-wait: 10ms
        min-idle: 5


    @Bean
    public LettuceClientConfigurationBuilderCustomizer customizer() {
        return clientConfigurationBuilder -> {
            LettuceClientConfiguration lettuceClientConfiguration = clientConfigurationBuilder.build();
            ClientOptions clientOptions = lettuceClientConfiguration.getClientOptions().orElse(null);
            if (clientOptions == null) {
                clientConfigurationBuilder.clientOptions(
                        ClusterClientOptions.builder()
                                .validateClusterNodeMembership(VALIDATE_CLUSTER_NODE_MEMBERSHIP)
                                .topologyRefreshOptions(ClusterTopologyRefreshOptions.builder()
                                        .enableAllAdaptiveRefreshTriggers()
                                        .build())
                                .build()
                );
                return;
            }
            ClusterClientOptions.Builder builder = ClusterClientOptions.builder()
                    .socketOptions(clientOptions.getSocketOptions())
                    .sslOptions(clientOptions.getSslOptions())
                    .autoReconnect(clientOptions.isAutoReconnect())
                    .cancelCommandsOnReconnectFailure(clientOptions.isCancelCommandsOnReconnectFailure())
                    .disconnectedBehavior(clientOptions.getDisconnectedBehavior())
                    .pingBeforeActivateConnection(clientOptions.isPingBeforeActivateConnection())
                    .requestQueueSize(clientOptions.getRequestQueueSize())
                    .suspendReconnectOnProtocolFailure(clientOptions.isSuspendReconnectOnProtocolFailure())
                    .validateClusterNodeMembership(VALIDATE_CLUSTER_NODE_MEMBERSHIP)
                    .topologyRefreshOptions(ClusterTopologyRefreshOptions.builder()
                            .enableAllAdaptiveRefreshTriggers()
                            .build());
            if (clientOptions instanceof ClusterClientOptions) {
                ClusterClientOptions clusterClientOptions = (ClusterClientOptions) clientOptions;
                builder.maxRedirects(clusterClientOptions.getMaxRedirects());
            }
            clientConfigurationBuilder.clientOptions(builder.build());
        };
    }

    @Bean(destroyMethod = "shutdown")
    public RedisClusterClient redisClusterClient(RedisProperties properties, ClientResources clientResources) {
        return RedisClusterClient.create(clientResources, getRedisURIs(properties));
    }

```

</details>

#### Environment

- Lettuce version(s): [5.0.5.RELEASE]
- Redis version: [e.g. 4.0.9]
- 5 master and 5 slave

###

**Comment by mylesliechen** [comment] 2022-04-08 07:56
@mp911de please

**Comment by mp911de** [comment] 2022-07-01 14:12
These issues are impossible to debug for me because they are highly environment-specific. The debug log does not show `CommandHandler` logs to find out when the channel was activated.

**Comment by mp911de** [comment] 2022-07-11 06:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-07-11 06:57 UTC
Labels: status: waiting-for-feedback

**Comment by DurableHumorGitHub** [comment] 2023-07-20 06:49
have you identified the cause of this problem or found a solution
