### ISSUE TITLE
Regression in lettuce 5: TopologyRefresher creates an infinite number of connections over time 

### ISSUE THREAD

**Issue by fabienrenaud** [lettuce-io/lettuce-core#737] opened 2018-03-21 20:22 UTC
100% repro.
Repro project:
 * https://github.com/fabienrenaud/lettuce-topology-refresh-connection-leak
 * App code/config: https://github.com/fabienrenaud/lettuce-topology-refresh-connection-leak/blob/master/src/main/java/com/example/App.java
 * runs a local redis-cluster in docker for ease of set up but the issue was originally noticed against an AWS elasticache redis cluster.

Configured identically in lettuce 4 and 5, the topology refresher in lettuce 5 spins up new connections without closing the old ones. Over time, lettuce creates and holds thousands of connections to the redis cluster.

**Lettuce v4.4.3.Final**
Maintain a small and constant number of connections to the redis cluster.
```
~ gradle run

> Task :run
Mar 21, 2018 1:10:59 PM com.lambdaworks.redis.EpollProvider <clinit>
INFO: Starting without optional Epoll library
Mar 21, 2018 1:10:59 PM com.lambdaworks.redis.KqueueProvider <clinit>
INFO: Starting without optional kqueue library
Wed Mar 21 13:11:00 PDT 2018: still alive
id=4 addr=127.0.0.1:35509 fd=10 name= age=592 idle=0 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=replconf
id=41 addr=172.17.0.1:56324 fd=20 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client

Wed Mar 21 13:11:05 PDT 2018: still alive
id=4 addr=127.0.0.1:35509 fd=10 name= age=597 idle=1 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=replconf
id=41 addr=172.17.0.1:56324 fd=20 name= age=5 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client

Wed Mar 21 13:11:10 PDT 2018: still alive
id=4 addr=127.0.0.1:35509 fd=10 name= age=602 idle=1 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=replconf
id=41 addr=172.17.0.1:56324 fd=20 name= age=10 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client

<=========----> 75% EXECUTING [16s]
```

**Lettuce v5.0.2.RELEASE**
Lettuce creates a new connection every time the topology is refreshed. Old connections are maintained too.
```
~ gradle run

> Task :run
[DEBUG] (main) Using Console logging
[DEBUG] (main) Starting UnsafeSupport init in Java 1.8
[TRACE] (main) sun.misc.Unsafe.theUnsafe ok
[TRACE] (main) sun.misc.Unsafe.copyMemory ok
[TRACE] (main) java.nio.Buffer.address ok
[DEBUG] (main) Unsafe is available
Mar 21, 2018 1:11:24 PM io.lettuce.core.EpollProvider <clinit>
INFO: Starting without optional epoll library
Mar 21, 2018 1:11:24 PM io.lettuce.core.KqueueProvider <clinit>
INFO: Starting without optional kqueue library
Wed Mar 21 13:11:24 PDT 2018: still alive
id=5 addr=127.0.0.1:7001 fd=10 name= age=615 idle=8 flags=M db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=63 addr=172.17.0.1:49604 fd=7 name=lettuce#ClusterTopologyRefresh age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=64 addr=172.17.0.1:49612 fd=20 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client

Wed Mar 21 13:11:29 PDT 2018: still alive
id=66 addr=172.17.0.1:49632 fd=23 name=lettuce#ClusterTopologyRefresh age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=67 addr=172.17.0.1:49644 fd=24 name=lettuce#ClusterTopologyRefresh age=2 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=5 addr=127.0.0.1:7001 fd=10 name= age=620 idle=3 flags=M db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=63 addr=172.17.0.1:49604 fd=7 name=lettuce#ClusterTopologyRefresh age=5 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=69 addr=172.17.0.1:49668 fd=26 name=lettuce#ClusterTopologyRefresh age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=64 addr=172.17.0.1:49612 fd=20 name= age=5 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
id=65 addr=172.17.0.1:49620 fd=22 name=lettuce#ClusterTopologyRefresh age=4 idle=4 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=68 addr=172.17.0.1:49656 fd=25 name=lettuce#ClusterTopologyRefresh age=1 idle=1 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client

Wed Mar 21 13:11:34 PDT 2018: still alive
id=70 addr=172.17.0.1:49680 fd=27 name=lettuce#ClusterTopologyRefresh age=4 idle=4 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=73 addr=172.17.0.1:49716 fd=31 name=lettuce#ClusterTopologyRefresh age=1 idle=1 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=63 addr=172.17.0.1:49604 fd=7 name=lettuce#ClusterTopologyRefresh age=10 idle=10 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=69 addr=172.17.0.1:49668 fd=26 name=lettuce#ClusterTopologyRefresh age=5 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=64 addr=172.17.0.1:49612 fd=20 name= age=10 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
id=65 addr=172.17.0.1:49620 fd=22 name=lettuce#ClusterTopologyRefresh age=9 idle=9 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=71 addr=172.17.0.1:49692 fd=28 name=lettuce#ClusterTopologyRefresh age=3 idle=3 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=72 addr=172.17.0.1:49704 fd=30 name=lettuce#ClusterTopologyRefresh age=2 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=68 addr=172.17.0.1:49656 fd=25 name=lettuce#ClusterTopologyRefresh age=6 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=66 addr=172.17.0.1:49632 fd=23 name=lettuce#ClusterTopologyRefresh age=8 idle=8 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=67 addr=172.17.0.1:49644 fd=24 name=lettuce#ClusterTopologyRefresh age=7 idle=7 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=5 addr=127.0.0.1:7001 fd=10 name= age=625 idle=8 flags=M db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=74 addr=172.17.0.1:49730 fd=32 name=lettuce#ClusterTopologyRefresh age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=client
```

I do not see a migration guide from v4 to v5 on the [wiki](https://github.com/lettuce-io/lettuce-core/wiki/Getting-started-(5.0)) so I suppose my configuration is still valid in v5. If so, this is a regression. If not, pease let me know of any updates I should do to the configuration.

PS:
 * `ClusterTopologyRefresh` did not change between v4 and v5 so the error could manifest itself in other ways as well. Using the ClusterTopologyRefresher is at least one way to trigger the issue.
 * explicitly setting `closeStaleConnections` to true does nothing more (true is the default).

**Comment by mp911de** [comment] 2018-03-22 08:27
Thanks a lot for reporting the issue. It looks like a duplicate of #721. Care to retest against `5.0.3.BUILD-SNAPSHOT`?

**Comment by fabienrenaud** [comment] 2018-03-22 15:14
Tested. I do not see this issue in `5.0.3.BUILD-SNAPSHOT`.

Considering the gravity of the issue (my whole cluster crashes after a few hours due to this bug), could you do an emergency release of 5.0.3 with only this patch in? I don't want to use a snapshot version that is susceptible to change any day...

**Comment by mp911de** [comment] 2018-03-22 17:31
5.0.3 will be released next week Tuesday

Am 22. März 2018, 16:14 +0100 schrieb Fabien Renaud <notifications@github.com>:

**Closed** 2018-03-23 10:33 UTC
Labels: bug, duplicate
