### ISSUE TITLE
CompleteableCommand should follow normal Tracing lifecycle?

### ISSUE THREAD

**Issue by anuraaga** [lettuce-io/lettuce-core#1652] opened 2021-03-10 02:08 UTC
## Feature Request

Currently, tracing `CompleteableCommand` requires manually hooking into its lifecycle.

https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/tracing/BraveTracing.java#L346

It would be nice if for this also it called into the normal `Tracing.finish`, `Tracing.error` to not have two ways of managing finishing spans.

#### Is your feature request related to a problem? Please describe

I am upgrading some instrumentation to support Lettuce 6 and found this mysterious code needed. It's not really obvious that this pattern of `instanceof` should be needed, especially because we already have lifecycle methods `error`, `finish`.

#### Describe the solution you'd like

`error` and `finish` are called for all commands, not just those that aren't `CompleteableCommand`

#### Describe alternatives you've considered

Status quo is ok, but very confusing.

#### Teachability, Documentation, Adoption, Migration Strategy

Instrumentation will be easier to write with that approach, but I don't know if there is a technical issue blocking it.

**Comment by mp911de** [comment] 2021-03-11 08:25
The reason for this design is that we don't want to have yet another wrapper around the command to implement tracing. We already have quite a few wrappers (`TransactionalCommand`, `LatencyMeteredCommand`, `ClusterCommand`) and adding another wrapping layer adds complexity to places where commands are unwrapped and reset for retry.

Can you help us understand what the actual issue is? The tracing implementation is intended to be used as-is without further need of customization.

**Comment by mp911de** [comment] 2021-03-24 09:08
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-03-24 09:08 UTC
Labels: status: waiting-for-feedback

**Comment by zmapleshine** [comment] 2021-07-13 09:45
@mp911de  Hi , I think I have the same problem about this issue. 
I use the ``tracer.span`` class to implement an indicator of the number of requests being processed.

However use ``completeableCommand.onComplete(...)`` method to close the span will lead to a problem  that if ``CommandHandler`` executes ``span.start()`` then connection suddenly unavailable ,then ``span.finish()`` method will never be executed.

This can also result in spans not being closed properly.

**Comment by mp911de** [comment] 2021-07-13 09:54
> However use completeableCommand.onComplete(...) method to close the span will lead to a problem that if CommandHandler executes span.start() then connection suddenly unavailable ,then span.finish() method will never be executed.

Care to point me in the right direction? `onComplete(BiConsumer)` is called on successful and on exception command completion. If the connection gets disconnected, then either commands get retried and completed afterwards or if the timeout for a command is exceeded, the command is completed with a `TimeoutException`. Closing a connection with unfinished commands should result in `CancellationException`.

If you found a loophole, that isn't calling the callback function, we need a way to identify it, ideally with a reproducer and we should fix it.

**Comment by zmapleshine** [comment] 2021-07-13 10:45
> Care to point me in the right direction? `onComplete(BiConsumer)` is called on successful and on exception command completion. If the connection gets disconnected, then either commands get retried and completed afterwards or if the timeout for a command is exceeded, the command is completed with a `TimeoutException`. Closing a connection with unfinished commands should result in `CancellationException`.
> 
I found it easy to repeat the problem in debug mode.

Put a break point on this line:
https://github.com/lettuce-io/lettuce-core/blob/a39b05b564ade64c27cd3deae3e660a442060b00/src/main/java/io/lettuce/core/protocol/CommandHandler.java#L429
```java
            span.start();
```
When the breakpoint duration exceeds the timeout (e.g. 2s, which in a real production environment would be set to the millisecond level because of the need to "fail-fast"), this method is not entered.

So, unless there is some time-consuming logic in the custom trace, It doesn't happen in theory that the span cannot be closed, do I understand you correctly?


Also, I noticed that the method ``span.finish()`` was not called in version 6.x. Does that mean that the lifecycle of the ``Tracer`` is defined by the client itself?

**Comment by mp911de** [comment] 2021-07-13 12:16
I see what you mean. There's a potential gap between attaching the callback to the command and starting the span. However, if these things happen in your system, then you should consider your timeout settings vs. the system load. Can you file a ticket so that we attach the completion first and then start the span?

**Comment by zmapleshine** [comment] 2021-07-14 06:09
> I see what you mean. There's a potential gap between attaching the callback to the command and starting the span. However, if these things happen in your system, then you should consider your timeout settings vs. the system load. Can you file a ticket so that we attach the completion first and then start the span?

OK, I started a new issue to focus more on this issue.
