### ISSUE TITLE
BLPOP Command timed out after 1 minute(s) causes output loss 

### ISSUE THREAD

**Issue by deepshiv126** [lettuce-io/lettuce-core#1179] opened 2019-11-08 22:31 UTC
## Bug Report

We have BlockingQueue Implementation on top of RedisList, the consumer thread of queue invokes BLPOP command to keep listening queue until it receives any event. Whenever shared connections are enabled, Blocking Redis Commands times out, whereas when shared connections are disabled, lettuce honor the blocking nature of Redis command and having Apache Pool Configured has no impact on this, plus disable-shared connections add more performance overhead.

Now, in order to balance between performance overhead vs shared connection, we had a logic to invoke queue, on each timed out until it receives an event.  This behavior is leading to output loss.  

Observing Lettuce Code especially "CommandHandler"."addToStack", stacks add redisCommand if "ChannelPromise" is void and I think "CommandHandler"."isWriteable" is checking whether redisCommand is Done or not, in case of BLPOP Command timeout, may be redisCommand it not Done;  

When event-data are published to queue using "RPUSH", then lettuce assume those BLPOP which are timed out are still active and providing event-data with an error saying "Command timed out after 1 minute(s)" and also reduces stack size. In order to make the queue work back again, multiple event-data should be pushed clear all stack with timeout redis command.

We think the problem is still with Lettuce not cleaning up the stack of redis command, upon redis command time-out and in meantime it will discard all the event-data/bytes.

![image](https://user-images.githubusercontent.com/12883918/68514992-4789f580-0234-11ea-823f-682f6392997e.png)

```java
Logs


2019-11-07--03-30-36-237 [T: U: D: Tx:/ URI: M:] [lettuce-nioEventLoop-20-3] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0x109a692e, /##.##.###.###:32808 -> xxxxxx-xxxxxxxxxxxxxx-0001-001.xxxxxx-xxxxxxxxxxxxxx.xxxxxx.use1.cache.amazonaws.com/##.##.###.###:6379, chid=0x9] Received: 1328 bytes, 2 commands in the stack
2019-11-07--03-30-36-237 [T: U: D: Tx:/ URI: M:] [lettuce-nioEventLoop-20-3] TRACE io.lettuce.core.protocol.CommandHandler - [channel=0x109a692e, /##.##.###.###:32808 -> xxxxxx-xxxxxxxxxxxxxx-0001-001.xxxxxx-xxxxxxxxxxxxxx.xxxxxx.use1.cache.amazonaws.com/##.##.###.###:6379, chid=0x9] Buffer: *2^M
$33^M
��^@^Et^@^ZQUEUE_xxxxIFICATE_REQUESTS^M
$1275^M
��^@^Esr^@>xxx.xxxxxxxxxx.xxxxxxx.service.pki.xxxxxxxxxxxxxxxxxxQueueItem^@^@^@^@^@^@^@^A^B^@^CZ^@^QstopWorkerThreadsL^@^LmdmChannelIdt^@^PLjava/util/UUID;L^@"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxst^@^PLjava/util/List;xp^@sr^@^Njava.util.UUID��^C��m�
2019-11-07--03-30-36-237 [T: U: D: Tx:/ URI: M:] [lettuce-nioEventLoop-20-3] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0x109a692e, /##.##.###.###:32808 -> xxxxxx-xxxxxxxxxxxxxx-0001-001.xxxxxx-xxxxxxxxxxxxxx.xxxxxx.use1.cache.amazonaws.com/##.##.###.###:6379, chid=0x9] Stack contains: 2 commands
2019-11-07--03-30-36-237 [T: U: D: Tx:/ URI: M:] [lettuce-nioEventLoop-20-3] DEBUG io.lettuce.core.protocol.RedisStateMachine - Decode ClusterCommand [command=AsyncCommand [type=BLPOP, output=KeyValueOutput [output=null, error='Command timed out after 1 minute(s)'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=5]
2019-11-07--03-30-36-237 [T: U: D: Tx:/ URI: M:] [lettuce-nioEventLoop-20-3] DEBUG io.lettuce.core.protocol.RedisStateMachine - Decoded ClusterCommand [command=AsyncCommand [type=BLPOP, output=KeyValueOutput [output=KeyValue[[B@3348d498, [B@2534987f], error='Command timed out after 1 minute(s)'], commandType=io.lettuce.core.protocol.Command], redirections=0, maxRedirections=5], empty stack: true

```

#### Environment
- Lettuce version(s): 5.1.8.RELEASE
- Redis version: 5.0.5

**Comment by mp911de** [comment] 2019-11-09 15:59
> Whenever shared connections are enabled, Blocking Redis Commands times out, whereas when shared connections are disabled, lettuce honor the blocking nature of Redis command and having Apache Pool Configured has no impact on this, plus disable-shared connections add more performance overhead.

Care to elaborate on shared connections? Lettuce itself isn't providing any means of shared connections.

I'm not sure I follow. There are two things that play into the general behavior: Timeout and protocol synchronization.

For timeouts, a command that does not receive within the given timeout a response is timed out in the synchronous, `Future` or `Subscription` frontend, depending on which API you're using. The command itself gets canceled to properly indicate the timeout.

The timeout counter starts at the time where the command is dispatched and written to the transport. In a typical arrangement, dispatch happens immediately when calling a Redis command method. In reactive arrangements, dispatch may happen at a later time.

Lettuce does not await completion of earlier commands before dispatching a new command as Lettuce uses pipelining. Commands that are written to the transport are added to the protocol stack awaiting a response. If a command in the stack gets canceled, then we have no means to communicate that fact to Redis. To retain protocol synchronization, we must wait until Redis sends a response. We cannot simply remove the command from the stack because such an action would desynchronize the protocol state.

 If Redis never responds but the connection gets broken, then what happens is that non-canceled commands get retried as we already know that the caller of the command has received a signal that the command is not valid anymore.


Does this help?

**Comment by mp911de** [comment] 2019-12-25 14:11
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-12-25 14:11 UTC
Labels: status: waiting-for-feedback, type: bug

**Comment by Yeganloo** [comment] 2021-07-04 11:53
Same Problem and solved by setting the default timeout of client to zero.
As the BLPOP command has a timeout argument, using that argument on connection, instead of default timeout will reduce confusion.

**Comment by Yeganloo** [comment] 2021-07-04 12:16
Same Problem and solved by setting the default timeout of client to zero.
As the BLPOP command has a timeout argument, using that argument on connection, instead of default timeout will be less confusing.

**Comment by mp911de** [comment] 2021-07-04 12:24
The problem with a timeout that is shared between the client and server is that the client side will always lead to a timeout exception. This is, because the timeout starts counting on invoking the command. That is before encoding and before the command has arrived at the server (imagine a multi-second latency).

**Comment by Yeganloo** [comment] 2021-07-04 13:38
So the problem is that the connection is opening with a timeout, before the command be known by 
lettuce?

**Comment by reed-sandberg** [comment] 2024-12-19 07:30
Tip: set timeoutOptions on your Redis(Cluster)Client.setOptions with a timeoutSource that uses a longer timeout for blocking commands (blpop, etc):

```
ClusterClientOptions.builder().timeoutOptions(
    TimeoutOptions.builder()
        .timeoutSource(new TimeoutOptions.TimeoutSource() {... })
        .build()
)
```
