### ISSUE TITLE
java.lang.RuntimeException: io.lettuce.core.RedisException: io.lettuce.core.RedisException: Invalid first byte: 34

### ISSUE THREAD

**Issue by phpusername** [lettuce-io/lettuce-core#2130] opened 2022-06-29 07:44 UTC
Caused by: io.lettuce.core.RedisException: Invalid first byte: 34
	at io.lettuce.core.protocol.RedisStateMachine.readReplyType(RedisStateMachine.java:315)
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:162)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:142)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:748)
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:712)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:698)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:628)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:597)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by phpusername** [comment] 2022-06-29 07:45
... 1 more

	at org.apache.dubbo.rpc.filter.ExceptionFilter.onResponse(ExceptionFilter.java:98) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.FilterNode.lambda$invoke$0(FilterNode.java:99) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.AsyncRpcResult.lambda$whenCompleteWithContext$0(AsyncRpcResult.java:197) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) ~[?:1.8.0_232]
	at org.apache.dubbo.rpc.AsyncRpcResult.whenCompleteWithContext(AsyncRpcResult.java:195) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:81) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at com.tingyun.common.dubbo.monitor.DubboMetricsMonitorFilter.invoke(DubboMetricsMonitorFilter.java:48) ~[aa577a7f_tingyun-dubbo-monitor-service-1.1.jar:1.1]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:192) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:129) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:148) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[8fe44a92_dubbo-2.7.13.jar:2.7.13]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[4329f3bf_dubbo-common-2.7.13.jar:2.7.13]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by phpusername** [comment] 2022-06-29 07:57
This error has been reported in the project recently, and there is no good way to solve it

**Comment by mp911de** [comment] 2022-06-29 10:09
We have no context on this where this happens, what the Redis version is etc.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2022-11-22 10:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-11-22 10:36 UTC
Labels: status: waiting-for-feedback
