### ISSUE TITLE
master-slave. App nodes don't receive topology change event.

### ISSUE THREAD

**Issue by kas-kad** [lettuce-io/lettuce-core#1296] opened 2020-05-25 12:05 UTC
#### Current Behavior
we have 4 master-slave + 9 sentinels Redis deployment. Afer every failover, 2 (only two and always the same two) out of 8 nodes of our application don't receive a topology change signal, so start failing writing to redis (do not know about a new master):
`io.lettuce.core.RedisCommandExecutionException: READONLY You can't write against a read only replica.`
We've been aware of the issue for a while now, so we've enabled logging for topology updates:
```xml
<logger name="io.lettuce.core.masterslave.SentinelTopologyRefresh" level="DEBUG" />
<logger name="io.lettuce.core.masterslave.SentinelConnector" level="DEBUG" />
```
Let me know of any additional logs/info that you need.

#### Input Code
<details>
<summary>Input Code</summary>

```kotlin
    private val redisUri: RedisURI by lazy {
        val ub = RedisURI.builder()
        sentinels
                .split(",")
                .forEach {
                    val (host, port) = it.split(":")
                    ub.withSentinel(host, port.toInt())
                    ub.withSentinelMasterId(master)
                    ub.withDatabase(2)
                }
        ub.build()
    }

    private val connection: StatefulRedisMasterSlaveConnection<String, String> by lazy {
        val connection = MasterSlave
                .connect(
                        client,
                        Utf8StringCodec(),
                        redisUri
                )
        connection.readFrom = ReadFrom.MASTER
        connection
    }

    private val client: RedisClient = RedisClient.create()
```

here are the logs from a node that succesfully handled the failover, however there are no such logs on the two invalid nodes:

```
[2020-05-25 11:00:16,078] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE]]
[2020-05-25 11:00:16,080] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (-sdown), scheduling topology update
[2020-05-25 11:00:21,080] DEBUG [lettuce-eventExecutorLoop-1-1] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 11:00:21,103] DEBUG [lettuce-nioEventLoop-4-1] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE]]
[2020-05-25 11:00:26,096] DEBUG [lettuce-nioEventLoop-4-3] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+convert-to-slave), scheduling topology update
[2020-05-25 11:00:31,096] DEBUG [lettuce-eventExecutorLoop-1-1] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 11:00:31,120] DEBUG [lettuce-nioEventLoop-4-1] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE]]
[2020-05-25 11:00:36,110] DEBUG [lettuce-nioEventLoop-4-3] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+role-change), scheduling topology update
[2020-05-25 11:00:41,110] DEBUG [lettuce-eventExecutorLoop-1-1] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 11:00:41,132] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE]]
[2020-05-25 11:02:27,891] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+sdown), scheduling topology update
[2020-05-25 11:02:32,892] DEBUG [lettuce-eventExecutorLoop-1-1] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 11:02:32,914] DEBUG [lettuce-nioEventLoop-4-2] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=SLAVE]]
```

</details>

#### Expected behavior/code

As mentioned before it's only two application nodes do not get the topology update, which is undesired behavior.

#### Environment

Dockerized application, dockerized redis master, slaves, sentinels.
- Lettuce version(s): 5.1.6.RELEASE
- Redis version: 5.0.5

**Comment by kas-kad** [comment] 2020-05-26 08:13
After a recent failover, we had a successful signaling of topology change. But still there is a difference on the two client nodes that stands out.
here is the set of logs from "healthy" client node:
```
[2020-05-25 14:46:22,686] DEBUG [lettuce-nioEventLoop-4-3] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+sdown), scheduling topology update
[2020-05-25 14:46:23,972] DEBUG [lettuce-nioEventLoop-4-2] i.l.core.masterslave.SentinelTopologyRefresh - Received sentinel state changed signal from Redis Sentinel, scheduling sentinel reconnect attempts
[2020-05-25 14:46:27,686] DEBUG [lettuce-eventExecutorLoop-1-1] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:46:27,727] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE]]
[2020-05-25 14:46:35,150] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+convert-to-slave), scheduling topology update
[2020-05-25 14:46:40,150] DEBUG [lettuce-eventExecutorLoop-1-2] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:46:40,171] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE]]
[2020-05-25 14:46:45,193] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+role-change), scheduling topology update
[2020-05-25 14:46:50,194] DEBUG [lettuce-eventExecutorLoop-1-2] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:46:50,220] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE]]
[2020-05-25 14:46:55,064] DEBUG [lettuce-nioEventLoop-4-2] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+switch-master), scheduling topology update
[2020-05-25 14:47:00,063] DEBUG [lettuce-eventExecutorLoop-1-2] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:47:00,082] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE]]
[2020-05-25 14:47:49,009] INFO  [lettuce-eventExecutorLoop-1-2] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /10.76.155.220:6379
[2020-05-25 14:47:49,013] INFO  [lettuce-nioEventLoop-4-1] io.lettuce.core.protocol.ReconnectionHandler - Reconnected to 10.76.155.220:6379
[2020-05-25 14:50:25,926] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+sdown), scheduling topology update
[2020-05-25 14:50:30,926] DEBUG [lettuce-eventExecutorLoop-1-3] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:50:30,942] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER]]
[2020-05-25 14:50:59,525] DEBUG [lettuce-nioEventLoop-4-2] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (-sdown), scheduling topology update
[2020-05-25 14:51:04,526] DEBUG [lettuce-eventExecutorLoop-1-3] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:51:04,590] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE]]
[2020-05-25 14:51:13,080] DEBUG [lettuce-nioEventLoop-4-2] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (-sdown), scheduling topology update
[2020-05-25 14:51:18,084] DEBUG [lettuce-eventExecutorLoop-1-3] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:51:18,138] DEBUG [lettuce-nioEventLoop-4-1] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE]]
```

and here is the set of logs from "faulty" one, a few times less events:
```
[2020-05-25 14:46:22,688] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received topology changed signal from Redis Sentinel (+sdown), scheduling topology update
[2020-05-25 14:46:24,139] DEBUG [lettuce-nioEventLoop-4-1] i.l.core.masterslave.SentinelTopologyRefresh - Received sentinel state changed signal from Redis Sentinel, scheduling sentinel reconnect attempts
[2020-05-25 14:46:27,689] DEBUG [lettuce-eventExecutorLoop-1-4] io.lettuce.core.masterslave.SentinelConnector - Refreshing topology
[2020-05-25 14:46:27,716] DEBUG [lettuce-nioEventLoop-4-3] io.lettuce.core.masterslave.SentinelConnector - New topology: [RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.220', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.155.142', port=6379], role=MASTER], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.61', port=6379], role=SLAVE], RedisMasterSlaveNode [redisURI=RedisURI [host='10.76.121.62', port=6379], role=SLAVE]]
[2020-05-25 14:47:49,092] INFO  [lettuce-eventExecutorLoop-1-1] io.lettuce.core.protocol.ConnectionWatchdog - Reconnecting, last destination was /10.76.155.220:6379
[2020-05-25 14:47:49,100] INFO  [lettuce-nioEventLoop-4-2] io.lettuce.core.protocol.ReconnectionHandler - Reconnected to 10.76.155.220:6379
```

**Comment by mp911de** [comment] 2020-05-26 12:48
Thanks for the report. Looking at the topologies, in both cases `New topology` reports the same roles

```
10.76.155.142 MASTER
10.76.155.220 SLAVE
10.76.121.61 SLAVE
10.76.121.62 SLAVE
```

Are you able to retrieve a heap dump from the affected nodes or debug into these? If so, then the state of `MasterSlaveConnectionProvider` and `AsyncConnectionProvider` would be interesting to see where the issue is rooted.

**Comment by mp911de** [comment] 2020-06-24 11:50
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-06-24 11:50 UTC
Labels: status: waiting-for-feedback, type: bug
