### ISSUE TITLE
io.lettuce.core.RedisCommandTimeoutException: Command timed out

### ISSUE THREAD

**Issue by LakshmikanthQuickRide** [lettuce-io/lettuce-core#1092] opened 2019-07-30 05:39 UTC
#### Current Behavior

<details>
<summary>Stack trace</summary>
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 10 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at com.sun.proxy.$Proxy72.get(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:191) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.1.6.RELEASE.jar:?]
	at com.sun.proxy.$Proxy72.get(Unknown Source) ~[?:?]
```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
public StatefulRedisClusterConnection<String, String> getRedisClient() {
		log.debug("getRedisClient()");
		if (pool == null) {
			synchronized (this) {
				pool = initializeConnectionPool();
			}
		}
		try {
			return pool.borrowObject();
		} catch (Exception e) {
			log.error("getting pool connection failed",e);
		}
		return null;
	}
	
	public GenericObjectPool<StatefulRedisClusterConnection<String, String>> initializeConnectionPool() {
		RedisClusterClient clusterClient = RedisClusterClient.create(new RedisURI(clusterUrl, clusterPort,Duration.ofMillis(10000)));
		ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
			      .enableAllAdaptiveRefreshTriggers()
			      .refreshTriggersReconnectAttempts(30)
			      .build();
		clusterClient.setOptions(ClusterClientOptions.builder()
                .topologyRefreshOptions(topologyRefreshOptions)
                .build());
		pool = ConnectionPoolSupport.createGenericObjectPool(() -> clusterClient.connect(), getLettucePoolConfig());
		return pool;
	}

private GenericObjectPoolConfig getLettucePoolConfig() {
		GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
		poolConfig.setMaxTotal(256);
		poolConfig.setBlockWhenExhausted(true);
		poolConfig.setMaxWaitMillis(10000);
		poolConfig.setMaxIdle(100);
		poolConfig.setMinIdle(50);
		poolConfig.setTestOnBorrow(false);
		poolConfig.setTestWhileIdle(true);
		return poolConfig;
	}
```

</details>

#### Environment

- Lettuce version(s):  5.1.6-Release
- Redis version:  5.0.4

**Comment by mp911de** [comment] 2019-07-30 08:33
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The code does not contain any obvious issues. Please grab a thread dump once the issue occurs the next time. Maybe it's related to #1086.

**Comment by LakshmikanthQuickRide** [comment] 2019-07-30 10:10
@mp911de 

Thanks for the update , We have seen lot of threads are waiting at LockSupport.parkNanos , May we know when this version made public or any beta version available to verify the issue is fixed

"http-bio-8080-exec-80" #703 daemon prio=5 os_prio=0 tid=0x00007f3a4400e800 nid=0x1227 waiting on condition [0x00007f393d2d3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f3fc846a088> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at io.lettuce.core.cluster.PipelinedRedisFuture.await(PipelinedRedisFuture.java:79)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:112)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy72.mget(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:191)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy72.mget(Unknown Source)

**Comment by mp911de** [comment] 2019-07-30 10:13
The mentioned scenario is a regular one. The synchronous facade awaits command completion. Do you see other ones that are blocked, too? (Other ones than `ClusterFutureSyncInvocationHandler`).

**Comment by mp911de** [comment] 2019-07-30 11:54
Thanks a lot. This is likely the cause for timeouts that for some reason Log4j blocks the I/O threads.

**Comment by mp911de** [comment] 2019-07-30 12:07
May I close this ticket or is there anything else I can assist you with?

**Comment by LakshmikanthQuickRide** [comment] 2019-07-30 12:30
@mp911de 
How can we disable debug logs for lettuce client and log only warnings or errors

**Comment by mp911de** [comment] 2019-07-30 12:46
Make sure your `Log4jLoggerAdapter` properly considers `isDebugEnabled()` flags. Lettuce checks on startup whether debug logging is enabled. If it's disabled, then Lettuce skips logging calls (see https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/protocol/CommandEncoder.java#L39-L98).

Logging category for Lettuce is `io.lettuce.core`.

**Closed by mp911de** 2019-07-30 12:46 UTC
Labels: for: external-project, status: invalid
