### ISSUE TITLE
NumberFormatException on "inf" zscore

### ISSUE THREAD

**Issue by DarkSeraphim** [lettuce-io/lettuce-core#528] opened 2017-04-29 01:10 UTC
ScoredValueStreamingOutput does not appear to be handling the 'inf' score (as Java only parses 'Infinity'). This bug occurred on 4.3.1.Final, and _appears_ to exist in later builds as well (unless something rewrites the byte[] internally, but I haven't tested it, so it's all speculation at this point).

[stack trace](https://gist.github.com/DarkSeraphim/77c8e5472f0debd38b41e569382ef0de)

To reproduce, I suppose all you'd need to do is to add an entry to a sorted set with score `Double.POSITIVE_INFINITY`, and try to grab it through `zrangebyscoreWithScores(ScoredValueStreamingChannel<V>, K, Range<? extends Number> range)`

```
// connection is a StatefulRedisConnection<String, String> field
final String KEY = "foo";
this.connection.sync().zadd(KEY, Double.POSITIVE_INFINITY, "bar");

RedisAsyncCommands<String, String> asyncRedis = this.connection.async();
Range<Double> range = Range.from(Range.Boundary.including((double) System.currentTimeMillis()),
                                 Range.Boundary.including(Double.POSITIVE_INFINITY));
asyncRedis.zrangebyscoreWithScores(entry -> {
    // TODO: fill
}, KEY, range);
```

**Comment by mp911de** [comment] 2017-04-29 10:58
Thanks a lot for the ticket. It contains exactly the details required to reproduce and fix the issue. The issue is fixed now in the 4.3.3, 4.4 and 5.0 branches.

**Closed by mp911de** 2017-04-29 10:58 UTC
Labels: bug
