### ISSUE TITLE
Cannot download netty-tcnative dependency in 6.2.2

### ISSUE THREAD

**Issue by modrym** [lettuce-io/lettuce-core#2320] opened 2023-02-10 13:46 UTC
## Bug Report

There is a problem with downloading a dependency netty-tcnative:

```
Could not find artifact io.netty:netty-tcnative:jar:osx-aarch_64:2.0.54.Final in central
```

#### Current Behavior

Even though it is run on Centos (architecture: amd64), it tries to install the dependency for osx-aarch_64.

There is the following entry in pom.xml:

<details>
<summary>pom.xml</summary>

```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <version>2.0.54.Final</version>
            <classifier>${os.detected.classifier}</classifier>
            <optional>true</optional>
        </dependency>
```

</details>

It contains the following classifier: `${os.detected.classifier}` which seems to be resolved at build time.

I see previously it was resolved to `osx-x86_64` 

https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.1.RELEASE/lettuce-core-6.2.1.RELEASE.pom
https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.0.RELEASE/lettuce-core-6.2.0.RELEASE.pom
https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.1.10.RELEASE/lettuce-core-6.1.10.RELEASE.pom

but it changed in 6.2.2.RELEASE:

https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.2.RELEASE/lettuce-core-6.2.2.RELEASE.pom

There is no package for that architecture:

https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.54.Final/

#### Expected behavior/code

It should download the correct package. 

#### Environment

- Lettuce version(s): 6.2.2.RELEASE
- System: Centos
- Architecture: amd64

#### Possible Solution

The minimal solution would be to use `osx-x86_64` or `linux-x86_64`.

**Comment by zentheprogrammer** [comment] 2023-02-10 14:22
I have the same problem in my project (Java: 17, Os: Ubuntu); if I execute `mvn dependecy:go-offline` I recive:
### org.eclipse.aether.resolution.DependencyResolutionException: io.netty:netty-tcnative:jar:osx-aarch_64:2.0.54.Final was not found

**Comment by mp911de** [comment] 2023-02-13 09:09
Given that there's no aarch version for OSX, we cannot really fix the issue. Both Linux and the one osx variant ship with arch classifiers. If we use `x86_64`, then we will break Linux arm users. `netty-tcnative` is an optional dependency, so excluding it should actually give you the chance to pull in the dependency into your own pom, no?

**Comment by zentheprogrammer** [comment] 2023-02-13 09:44
Hi @mp911de,
I tried to exclude tcnative:
<dependency>
      <groupId>io.lettuce</groupId>
      <artifactId>lettuce-core</artifactId>
      <version>6.2.2.RELEASE</version>
      <exclusions>
          <exclusion>
              <groupId>io.netty</groupId>
              <artifactId>netty-tcnative</artifactId>
          </exclusion>
      </exclusions>
</dependency>
but actually the command `mvn dependency:go-offline` doesn't work.
I made a second test too, including the `x86_64` version on my pom (before lettucce-core) but the command print the same error

**Comment by mp911de** [comment] 2023-02-14 15:38
You should be able to set the [`excludeArtifactIds` property](https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html) to be able to exclude the artifact.

Since there's a workaround and nothing more we intend to do, I'm closing this ticket.

**Closed by mp911de** 2023-02-14 15:38 UTC

**Comment by iNikem** [comment] 2023-03-28 07:17
> Given that there's no aarch version for OSX, we cannot really fix the issue. Both Linux and the one osx variant ship with arch classifiers. If we use `x86_64`, then we will break Linux arm users. `netty-tcnative` is an optional dependency, so excluding it should actually give you the chance to pull in the dependency into your own pom, no?

I am sorry, but the issue is that this project publishes a pom file which has a non-existing dependency in it. https://repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.2.RELEASE/lettuce-core-6.2.2.RELEASE.pom references `netty-tcnative` with classifier `osx-aarch_64`. The pom file that this project publishes is _certainly_ under this project's control. Why are you saying that you cannot fix this issue??

**Comment by Feniksovich** [comment] 2023-10-12 16:59
Pretty painful, it should be resolved if possible.
