### ISSUE TITLE
evalsha throws UnsupportedOperationException

### ISSUE THREAD

**Issue by nikolayspb** [lettuce-io/lettuce-core#595] opened 2017-09-05 12:07 UTC
Hello Mark,

When change from Lettuce 4.3.3 to 4.4.0 I got this exception in one of my tests so it fails. It uses evalsha method. Can you spot an issue or need additional information from my side?

```
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.lambdaworks.redis.output.NestedMultiOutput.multi(NestedMultiOutput.java:72)
	at com.lambdaworks.redis.protocol.RedisStateMachine.safeMulti(RedisStateMachine.java:445)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:218)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:313)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:257)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:934)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:397)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mp911de** [comment] 2017-09-05 12:11
That's a duplicate of #589.

Can you check whether `4.4.1-SNAPSHOT` fixes the issue?

**Comment by nikolayspb** [comment] 2017-09-05 12:17
yes, with snapshot issue is fixed. indeed duplicate.

**Closed** 2017-09-05 12:19 UTC
Labels: bug, duplicate
