### ISSUE TITLE
Publisher stop working after a period of time

### ISSUE THREAD

**Issue by EURedBoy** [lettuce-io/lettuce-core#2515] opened 2023-10-07 20:50 UTC
#### Current Behavior

After a period of time my publisher disconnect

<details>
<summary>Stack trace</summary>

```java
No stack trace
```

</details>

#### Input Code
![aaa](https://github.com/lettuce-io/lettuce-core/assets/69308679/ddbbea9f-880b-4e30-8a05-7a01e8814d12)
![image](https://github.com/lettuce-io/lettuce-core/assets/69308679/79e62cb7-925f-41ff-89a0-0274da6a180f)

</details>

#### Expected behavior/code
I expect that the publisher doesn't disconnect or at least it reconnects automatically
#### Environment

- Lettuce version(s):  6.2.5
- Redis version: 6.0.16

**Comment by mp911de** [comment] 2023-10-09 07:00
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

As per the docs, Lettuce auto-reconnects by default. So if you can reproduce the issue, then I'm happy to have a look.

**Comment by EURedBoy** [comment] 2023-10-09 20:01
Tomorrow i will explain the problem better, but i think that pub/sub didn't reconnect after client reconnection.

**Comment by mp911de** [comment] 2023-10-26 12:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2023-10-26 12:40 UTC
