### ISSUE TITLE
Cannot determine own partition of redis cluster

### ISSUE THREAD

**Issue by journey51** [lettuce-io/lettuce-core#1911] opened 2021-11-04 07:15 UTC
## Bug Report

Connect to Alibaba cloud redis cluster through direct connection，
Error: java.net.ConnectException: Connection refused: connect

**Comment by mp911de** [comment] 2021-11-08 08:14
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2021-12-03 10:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-12-03 10:22 UTC
Labels: status: waiting-for-feedback
