### ISSUE TITLE
RedisCommandTimeoutException occurs when TCP persistent connection  interrupted

### ISSUE THREAD

**Issue by JessicaAsXY** [lettuce-io/lettuce-core#1523] opened 2020-11-18 06:07 UTC
## Bug Report

io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)
        at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
        at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
        at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy93.hkeys(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at io.lettuce.core.support.ConnectionWrapping$DelegateCloseToConnectionInvocationHandler.handleInvocation(ConnectionWrapping.java:191)
        at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
        at com.sun.proxy.$Proxy93.hkeys(Unknown Source)

#### Current Behavior
 Traffic switch to another redis server（Ip  unchanged）causes persistent connection between redis client and server  interrupted。
  Traffic switch finished immediately，but exception continued several minutes.
  And other services use jedis as redis-client sdk  did not occur exception at that time like ours

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s):    5.1.4.RELEASE
- Redis version: 3.2.8

**Comment by JessicaAsXY** [comment] 2020-11-18 06:25
As I know, when  persistent connection interrupted  dubbo can re-establishs it. And lettuce can do it？

**Comment by mp911de** [comment] 2020-11-18 08:08
Lettuce auto-reconnects if a connection was disconnected. If the disconnect lasts longer than the timeout, than that's a possible explanation. Other than that, check the [reference documentation on timeouts](https://lettuce.io/core/release/reference/#faq.timeout) as timeouts are a symptom, not the cause.

**Comment by mp911de** [comment] 2020-11-21 20:15
Closing this ticket since as we can't do anything here. Feel free to provide more details so we can reopen this ticket if necessary.

**Closed by mp911de** 2020-11-21 20:15 UTC
Labels: type: bug
