### ISSUE TITLE
CommandHandler.rebuildQueue() causes long locks

### ISSUE THREAD

**Issue by nikolayspb** [lettuce-io/lettuce-core#615] opened 2017-10-02 13:05 UTC
Hello Mark,

I use Letttuce 4.4.1 version.

I test case when Redis goes down by restarting all nodes. Even though I use CompleteableFuture API I got main worker (jetty threads) blocked.

```
Stack Trace
qtp533415944-412 [412] (BLOCKED)
   com.lambdaworks.redis.protocol.CommandHandler.incrementWriters line: 489 
   com.lambdaworks.redis.protocol.CommandHandler.write line: 345 
   com.lambdaworks.redis.RedisChannelHandler.dispatch line: 133 
   com.lambdaworks.redis.StatefulRedisConnectionImpl.dispatch line: 219 
   com.lambdaworks.redis.AbstractRedisAsyncCommands.dispatch line: 1979 
   com.lambdaworks.redis.AbstractRedisAsyncCommands.setex line: 874 
```

Also in logs I can see, which is expected. but BLOCKING all threads is unexpected.
```
java.util.concurrent.CompletionException: com.lambdaworks.redis.RedisException: Internal stack size exceeded: 500000. Commands are not accepted until the stack size drops.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1284)
        at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1270)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at com.lambdaworks.redis.protocol.AsyncCommand.doCompleteExceptionally(AsyncCommand.java:134)
        at com.lambdaworks.redis.protocol.AsyncCommand.completeExceptionally(AsyncCommand.java:127)
        at com.lambdaworks.redis.protocol.CommandHandler.addToStack(CommandHandler.java:718)
        at com.lambdaworks.redis.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:641)
        at com.lambdaworks.redis.protocol.CommandHandler.write(CommandHandler.java:625)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:732)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:795)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:807)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:788)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:824)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1017)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:255)
        at com.lambdaworks.redis.protocol.CommandHandler.writeAndFlush(CommandHandler.java:459)
        at com.lambdaworks.redis.protocol.CommandHandler.writeToChannel(CommandHandler.java:434)
        at com.lambdaworks.redis.protocol.CommandHandler.write(CommandHandler.java:352)
        at com.lambdaworks.redis.protocol.CommandHandler$RetryListener.operationComplete(CommandHandler.java:1226)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
        at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:676)
        at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:294)
        at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:617)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:613)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:812)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:394)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollOutReady(AbstractEpollStreamChannel.java:859)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:387)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.lambdaworks.redis.RedisException: Internal stack size exceeded: 500000. Commands are not accepted until the stack size drops.
        at com.lambdaworks.redis.protocol.CommandHandler.validateWrite(CommandHandler.java:733)
        at com.lambdaworks.redis.protocol.CommandHandler.addToStack(CommandHandler.java:700)
```

**Comment by mp911de** [comment] 2017-10-02 13:51
Can you provide the full thread dump that involves netty threads or showing Lettuce frames?

**Comment by nikolayspb** [comment] 2017-10-02 14:16
That's basically it. Empty lines are proprietary lines which I have removed.

```
Stack Trace
qtp533415944-554 [554] (BLOCKED)
   com.lambdaworks.redis.protocol.CommandHandler.incrementWriters line: 489 
   com.lambdaworks.redis.protocol.CommandHandler.write line: 345 
   com.lambdaworks.redis.RedisChannelHandler.dispatch line: 133 
   com.lambdaworks.redis.StatefulRedisConnectionImpl.dispatch line: 219 
   com.lambdaworks.redis.AbstractRedisAsyncCommands.dispatch line: 1979 
   com.lambdaworks.redis.AbstractRedisAsyncCommands.zadd line: 1078 
   
   org.springframework.cglib.proxy.MethodProxy.invoke line: 204 
   org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint line: 738 
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 157 
   org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke line: 136 
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 179 
   org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept line: 673 
  
   sun.reflect.GeneratedMethodAccessor56.invoke line: not available 
   sun.reflect.DelegatingMethodAccessorImpl.invoke line: 43 
   java.lang.reflect.Method.invoke line: 498 
   
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 179 
   
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 179 
   
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 179 
   
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 179 
   
   org.springframework.aop.framework.ReflectiveMethodInvocation.proceed line: 179 
   org.springframework.aop.framework.JdkDynamicAopProxy.invoke line: 213 
   com.sun.proxy.$Proxy95.acceptAsync line: not available 
   sun.reflect.GeneratedMethodAccessor72.invoke line: not available 
   sun.reflect.DelegatingMethodAccessorImpl.invoke line: 43 
   java.lang.reflect.Method.invoke line: 498 

   
   javax.servlet.http.HttpServlet.service line: 790 
   org.eclipse.jetty.servlet.ServletHolder.handle line: 848 
   org.eclipse.jetty.servlet.ServletHandler.doHandle line: 584 
   org.eclipse.jetty.server.session.SessionHandler.doHandle line: 224 
   org.eclipse.jetty.server.handler.ContextHandler.doHandle line: 1180 
   org.eclipse.jetty.servlet.ServletHandler.doScope line: 512 
   org.eclipse.jetty.server.session.SessionHandler.doScope line: 185 
   org.eclipse.jetty.server.handler.ContextHandler.doScope line: 1112 
   org.eclipse.jetty.server.handler.ScopedHandler.handle line: 141 
   org.eclipse.jetty.server.handler.StatisticsHandler.handle line: 169 
   org.eclipse.jetty.server.handler.gzip.GzipHandler.handle line: 493 
   
   org.eclipse.jetty.server.handler.HandlerWrapper.handle line: 134 
   
   org.eclipse.jetty.server.handler.HandlerCollection.handle line: 119 
   org.eclipse.jetty.server.handler.HandlerWrapper.handle line: 134 
   org.eclipse.jetty.server.Server.handle line: 534 
   org.eclipse.jetty.server.HttpChannel.handle line: 320 
   org.eclipse.jetty.server.HttpConnection.onFillable line: 251 
   org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded line: 283 
   org.eclipse.jetty.io.FillInterest.fillable line: 108 
   org.eclipse.jetty.io.SelectChannelEndPoint$2.run line: 93 
   org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume line: 303 
   org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume line: 148 
   org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run line: 136 
   org.eclipse.jetty.util.thread.QueuedThreadPool.runJob line: 671 
   org.eclipse.jetty.util.thread.QueuedThreadPool$2.run line: 589 
   java.lang.Thread.run line: 748 
```

**Comment by nikolayspb** [comment] 2017-10-02 14:18
Hot methods show

```
Stack Trace	Sample Count	Percentage(%)
com.lambdaworks.redis.protocol.CommandWrapper.unwrap(RedisCommand)	1 520	51,508
   com.lambdaworks.redis.protocol.AsyncCommand.equals(Object)	1 520	51,508
      java.util.concurrent.LinkedBlockingQueue.contains(Object)	1 520	51,508
         com.lambdaworks.redis.protocol.CommandHandler.rebuildQueue()	1 520	51,508
            com.lambdaworks.redis.protocol.CommandHandler.channelInactive(ChannelHandlerContext)	1 520	51,508
               io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 520	51,508
                  io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 520	51,508
                     io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	1 520	51,508
                        io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	1 520	51,508
                           com.lambdaworks.redis.ChannelGroupListener.channelInactive(ChannelHandlerContext)	1 520	51,508
                              io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 520	51,508
                                 io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 520	51,508
                                    io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	1 520	51,508
                                       io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	1 520	51,508
                                          com.lambdaworks.redis.PlainChannelInitializer$1.channelInactive(ChannelHandlerContext)	1 520	51,508
                                             io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 520	51,508
                                                io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 520	51,508
                                                   io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	1 520	51,508
                                                      io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(ChannelHandlerContext)	1 520	51,508
                                                         io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 520	51,508
                                                            io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 520	51,508
                                                               io.netty.channel.DefaultChannelPipeline.fireChannelInactive()	1 520	51,508
                                                                  io.netty.channel.AbstractChannel$AbstractUnsafe$7.run()	1 520	51,508
                                                                     io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long)	1 520	51,508
                                                                        io.netty.channel.epoll.EpollEventLoop.run()	1 520	51,508
                                                                           io.netty.util.concurrent.SingleThreadEventExecutor$2.run()	1 520	51,508
                                                                              io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run()	1 520	51,508
                                                                                 java.lang.Thread.run()	1 520	51,508

```

**Comment by nikolayspb** [comment] 2017-10-02 14:19
and
```
Stack Trace	Sample Count	Percentage(%)
com.lambdaworks.redis.protocol.AsyncCommand.equals(Object)	1 321	42,124
   java.util.concurrent.LinkedBlockingQueue.contains(Object)	1 321	42,124
      com.lambdaworks.redis.protocol.CommandHandler.rebuildQueue()	1 321	42,124
         com.lambdaworks.redis.protocol.CommandHandler.channelInactive(ChannelHandlerContext)	1 321	42,124
            io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 321	42,124
               io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 321	42,124
                  io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	1 321	42,124
                     io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	1 321	42,124
                        com.lambdaworks.redis.ChannelGroupListener.channelInactive(ChannelHandlerContext)	1 321	42,124
                           io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 321	42,124
                              io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 321	42,124
                                 io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	1 321	42,124
                                    io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	1 321	42,124
                                       com.lambdaworks.redis.PlainChannelInitializer$1.channelInactive(ChannelHandlerContext)	1 321	42,124
                                          io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 321	42,124
                                             io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 321	42,124
                                                io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	1 321	42,124
                                                   io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(ChannelHandlerContext)	1 321	42,124
                                                      io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	1 321	42,124
                                                         io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	1 321	42,124
                                                            io.netty.channel.DefaultChannelPipeline.fireChannelInactive()	1 321	42,124
                                                               io.netty.channel.AbstractChannel$AbstractUnsafe$7.run()	1 321	42,124
                                                                  io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long)	1 321	42,124
                                                                     io.netty.channel.epoll.EpollEventLoop.run()	1 321	42,124
                                                                        io.netty.util.concurrent.SingleThreadEventExecutor$2.run()	1 321	42,124
                                                                           io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run()	1 321	42,124
                                                                              java.lang.Thread.run()	1 321	42,124

```

**Comment by nikolayspb** [comment] 2017-10-02 14:21
Maybe it helps

```
Stack Trace	Sample Count	Percentage(%)
java.lang.Thread.run()	2 951	100
   io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run()	2 951	100
      io.netty.util.concurrent.SingleThreadEventExecutor$2.run()	2 951	100
         io.netty.channel.epoll.EpollEventLoop.run()	2 951	100
            io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long)	2 951	100
               io.netty.channel.AbstractChannel$AbstractUnsafe$7.run()	2 951	100
                  io.netty.channel.DefaultChannelPipeline.fireChannelInactive()	2 951	100
                     io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	2 951	100
                        io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	2 951	100
                           io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(ChannelHandlerContext)	2 951	100
                              io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	2 951	100
                                 io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	2 951	100
                                    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	2 951	100
                                       com.lambdaworks.redis.PlainChannelInitializer$1.channelInactive(ChannelHandlerContext)	2 951	100
                                          io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	2 951	100
                                             io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	2 951	100
                                                io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	2 951	100
                                                   io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	2 951	100
                                                      com.lambdaworks.redis.ChannelGroupListener.channelInactive(ChannelHandlerContext)	2 951	100
                                                         io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	2 951	100
                                                            io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	2 951	100
                                                               io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	2 951	100
                                                                  io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	2 951	100
                                                                     com.lambdaworks.redis.protocol.CommandHandler.channelInactive(ChannelHandlerContext)	2 951	100
                                                                        com.lambdaworks.redis.protocol.CommandHandler.rebuildQueue()	2 951	100
                                                                           java.util.concurrent.LinkedBlockingQueue.contains(Object)	2 951	100
                                                                              java.util.concurrent.LinkedBlockingQueue.fullyUnlock()	72	2,44
                                                                                 java.util.concurrent.locks.ReentrantLock.unlock()	72	2,44
                                                                                    java.util.concurrent.locks.AbstractQueuedSynchronizer.release(int)	72	2,44
                                                                              com.lambdaworks.redis.protocol.AsyncCommand.equals(Object)	2 589	87,733
                                                                                 com.lambdaworks.redis.protocol.CommandWrapper.unwrap(RedisCommand)	1 520	51,508

```

**Comment by mp911de** [comment] 2017-10-02 14:45
A single thread cannot block itself, other threads must be involved. The reported line [CommandHandler.java:489](https://github.com/lettuce-io/lettuce-core/blob/644ccc5196598ce233332545af66e9d575e668c0/src/main/java/com/lambdaworks/redis/protocol/CommandHandler.java#L489) is a `synchronized` block.

**Comment by nikolayspb** [comment] 2017-10-02 14:48
Yes, I know. All 250 threads block there.

**Comment by mp911de** [comment] 2017-10-02 14:53
One of them must hold the lock therefore I asked you for the complete trace. Maybe you can spot it yourself, if you don't want to post it here.

**Comment by nikolayspb** [comment] 2017-10-02 18:02
Looks like rebuild queue takes long time, all other writes get blocked.

**Comment by mp911de** [comment] 2017-10-02 18:40
Thanks a lot for tracing down the cause. Without the traces the previous profiler trees didn't make any sense to me. I will check what we can do improve rebuilding performance. In the meantime, setting the queue limit to a smaller, reasonable number (1000 or 10000) should unblock your application.

**Comment by nikolayspb** [comment] 2017-10-02 18:59
The most unexpected part is that my caller threads got blocked. However they are not supposed as async API is used.

**Comment by nikolayspb** [comment] 2017-10-03 07:36
By the way, I see no effect of com.lambdaworks.redis.AbstractRedisClient#setDefaultTimeout in this situation. I set it to 1 sec, so I expect that commands got evicted from queue after period.

**Comment by nikolayspb** [comment] 2017-10-03 08:34
Reducing queue size does not really help, because of reconnect it does not get cleared.
#616

**Comment by mp911de** [comment] 2017-10-03 09:40
The timeout affects only command synchronization using the synchronous API. There's #435 to investigate further on command timeouts as asynchronously executed commands do not time out at all.

**Comment by nikolayspb** [comment] 2017-10-04 08:50
So do you have ideas how to fix it? Apart from queue rebuild performance writer threads should not compete for the same lock, especially in a caller thread before giving back a CompletableFuture.

**Comment by mp911de** [comment] 2017-10-04 09:00
There are two things to do:

1. Fix the queue rebuild.
2. Investigate the impact on thread switching for the actual write. Using the channel thread to write the command makes a lot of sense because we could probably get rid of some synchronization code and subsequent channel I/O does not require further context switching (see #617). 

The former can happen within a bugfix release, the latter is a good story for 4.5/5.1 as it probably requires object pooling to prevent performance degradation.

**Comment by mp911de** [comment] 2017-10-04 14:52
I pushed a fix for the various versions. Can you give `lettuce-4.4.2-SNAPSHOT` a spin?

**Comment by nikolayspb** [comment] 2017-10-04 17:07
Thanks, I have tried it. I still use 10000 as request queue size.
So I restart all Redises at the same time. They are configured to wait 12 seconds before restart. 

Commands rate drops to 0 and restores back only after 3 minutes.

**Comment by mp911de** [comment] 2017-10-04 17:41
Can you provide a reproducible test case (w/o Redis restart) that outlines how your case looks like?

Am 4. Okt. 2017, 19:07 +0200 schrieb Nikolay Kuznetsov <notifications@github.com>:

**Comment by nikolayspb** [comment] 2017-10-04 17:48
Basically I store key-value pairs with rate of 3-8K per sec.

**Comment by mp911de** [comment] 2017-10-05 10:28
Running a test that queues 10000 commands in a disconnected state and then start Redis again recovers within a few seconds.

Ther were unique commands checks in the offline mode caused some severe slowdown. With 10000 commands it's a matter of several seconds (10 seconds or so) to enqueue a command. Removing the checks reduces the enqueue time to a few ns.

**Comment by nikolayspb** [comment] 2017-10-05 13:19
I have just tested with 4.4.1 and 4.4.2-SNAPSHOT again and requestQueue size 500.
After Redis restart in 4.4.1 flow with Redis got stuck. In 4.4.2 it just went very smoothly and perfect. Thanks!

**Comment by mp911de** [comment] 2017-10-05 13:27
Thanks a lot. Closing this ticket as it's solved.

**Closed by mp911de** 2017-10-05 13:27 UTC
Labels: bug

**Comment by nikolayspb** [comment] 2017-10-05 14:00
Can you release?

**Comment by mp911de** [comment] 2017-10-05 14:08
Expect a release (4.4.2) by end of October. There are a couple of other issues that should make it into the release, first of all, I need to to some housekeeping. Use either the snapshot or, if you have that possibility, deploy an intermediate release to your own artifact repository.
