### ISSUE TITLE
zset zrangebyscore 

### ISSUE THREAD

**Issue by 10119255** [lettuce-io/lettuce-core#881] opened 2018-10-09 12:25 UTC
## Bug Report

In some environments `zrangebyscore(zSetKey, range).get(WAIT_TIME, TimeUnit.SECONDS)` is not responding

#### Current Behavior

In the development environment and test environment, the program is normal. But there is no response in the production environment

#### code(java)
```java
        StatefulRedisClusterConnection<String, String> connection = null;
        try {
            connection = lettucePool.acquire().get(WAIT_TIME, TimeUnit.SECONDS);
            RedisAdvancedClusterAsyncCommands<String, String> command = connection.async();

            // no response
            List<String> expireKeyList = command.zrangebyscore(zSetKey, range).get(WAIT_TIME, TimeUnit.SECONDS);

            return doDeleteKey(command, zSetKey, expireKeyList);
        } catch (Exception e) {
            log.error(e.getMessage(), e);
            return false;
        } finally {
            if (connection != null) {
                IndicatorUtil.releaseConnection(lettucePool, connection);
            }
        }
```

**Comment by mp911de** [comment] 2018-10-10 06:30
What do you mean with no response? Care to add more context what happens (timeout, …) here?

Please also enable debug logging for the `io.lettuce.core.protocol` logger to see what's happening on the transport.

**Comment by 10119255** [comment] 2018-10-10 12:21
No response means the program has been stuck here.

**Comment by mp911de** [comment] 2018-10-11 06:40
This can be caused by various things:
* Connection to Redis is disconnected (`connection.isOpen()` returns `false`)
* The connection is blocked by a previous command
* The connection is in a transactional state (`connection.isMulti()` returns `true`)

**Comment by 10119255** [comment] 2018-10-15 12:09
> This can be caused by various things:
> 
> * Connection to Redis is disconnected (`connection.isOpen()` returns `false`)
> * The connection is blocked by a previous command
> * The connection is in a transactional state (`connection.isMulti()` returns `true`)

Thank you very much for your reply. 
I don’t think it’s the case, In order to solve the production problem immediately, I have replaced the implementation of `jedisClusterClient` implementation, and the problem is solved.

**Comment by mp911de** [comment] 2018-10-15 13:27
Thanks for your feedback. Closing this one as solved.

**Closed by mp911de** 2018-10-15 13:27 UTC
Labels: status: cannot-reproduce, status: waiting-for-feedback

**Comment by yinbingqiu** [comment] 2018-10-16 13:34
我平时这样使用StatefulRedisClusterConnection demo

**Comment by yinbingqiu** [comment] 2018-10-16 13:35
I usually use the StatefulRedisClusterConnection demo like this.
```
 RedisClusterClient redisClusterClient;

    public void test() {
        StatefulRedisClusterConnection<String, String> connection = LettuceUtil.getConnection(redisClusterClient); //get a connection
        RedisAdvancedClusterAsyncCommands<String, String> command = connection.async();
        command.setAutoFlushCommands(false);
        List<RedisFuture> futureList = new ArrayList<>();
        futureList.add(command.get("aaa"));
        futureList.add(command.get("bbb"));
        futureList.add(command.get("cc"));
        futureList.add(command.get("ddd"));
        // ....Some command .....
        command.flushCommands();
        LettuceUtil.execute(futureList.toArray(new RedisFuture[futureList.size()]));//call LettuceFutures.awaitAll

        // other command
        List<RedisFuture> futureList1 = new ArrayList<>();
        futureList1.add(command.get("aaa"));
        futureList1.add(command.get("bbb"));
        futureList1.add(command.get("cc"));
        futureList1.add(command.get("ddd"));
        // ....Some other command .....
        command.flushCommands();
        LettuceUtil.execute(futureList1.toArray(new RedisFuture[futureList1.size()]));  //call LettuceFutures.awaitAll


        LettuceUtil.releaseConnection(connection);//call connection.close

    }
```
Is this used correctly?
@mp911de

**Comment by mp911de** [comment] 2018-10-16 14:06
@yinbingqiu Please do not resurrect closed issues for other purposes. Please post your question to Stackoverflow.
