### ISSUE TITLE
RedisCommandTimeoutException when there is a network glitch

### ISSUE THREAD

**Issue by dhaval-bhanderi** [lettuce-io/lettuce-core#762] opened 2018-04-18 10:52 UTC
Hi,

We have a daemon process which pushes data to redis on AWS using lettuce-core. I have noticed that during network glitch i.e when a connection is disconnected , I get below exception :

```
io.lettuce.core.RedisCommandTimeoutException: Command timed out
at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:62)
at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
at com.sun.proxy.$Proxy11.hmget(Unknown Source)
```

Code to reproduce : 

```
public class TestMain {
	public static void main(String[] args) {
		Duration timeout = Duration.ofMillis(10000);
		RedisClient client = RedisClient.create(RedisURI.create("redis://127.0.0.1:6379"));
		client.setDefaultTimeout(timeout);
		RedisCommands<String, String> commands = client.connect().sync();
		String[] arr = { "test", "test2" };
		int i = 1;
		while (i <= 1000) {
			try {
				List<KeyValue<String, String>> op = commands.hmget("TEST", arr);
				System.out.println(op);
				i++;
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
}
```
Version : 

```
<dependency>
	<groupId>io.lettuce</groupId>
	<artifactId>lettuce-core</artifactId>
	<version>5.0.3.RELEASE</version>
</dependency>
```

After the connection is re-established it works fine. The time out given is around 10 seconds and network connection is fixed before 10 seconds but still this exception occur. Ideally it should have waited for 10 seconds before throwing the exception.

Also the exception thrown seems to be incorrect i.e `RedisCommandTimeoutException` , could have been something different.

**Comment by mp911de** [comment] 2018-04-23 12:38
Care to provide a reproducible test case?


I did a cursory test with a simple Java class and killing Redis/restarting it:

Test case:

```java
public class ConnectToRedis {

    public static void main(String[] args) {

        RedisClient redisClient = RedisClient.create("redis://localhost:6379/0");
        redisClient.setDefaultTimeout(10, TimeUnit.SECONDS);
        StatefulRedisConnection<String, String> connection = redisClient.connect();

        while (true)
            try {
                System.out.println(connection.sync().set("foo", "bar"));
                Thread.sleep(1000);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
}
```

Output:

```
2018-04-23 14:37:05 [INFO ] [main] Starting without optional Epoll library (EpollProvider:101)
2018-04-23 14:37:05 [INFO ] [main] Starting without optional kqueue library (KqueueProvider:101)
OK
OK
OK
2018-04-23 14:37:08 [INFO ] [lettuce-eventExecutorLoop-1-2] Reconnecting, last destination was localhost/127.0.0.1:6379 (ConnectionWatchdog:106)
2018-04-23 14:37:08 [WARN ] [lettuce-nioEventLoop-4-2] Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379 (ConnectionWatchdog:136)
2018-04-23 14:37:11 [INFO ] [lettuce-nioEventLoop-4-4] Reconnected to localhost:6379 (ReconnectionHandler:106)
OK
OK
OK
OK
OK
OK
OK
OK
```

**Comment by dhaval-bhanderi** [comment] 2018-04-23 13:53
Hi,

Probably restarting the redis wont help to reproduce it.

Steps to reproduce:
1. Start Redis on a different instance (not local)
2. Run the above code with timeout
3. While running just disconnect your network so that your Redis instance is unreachable ( I simply removed my LAN cable)
4. Reconnect your network
5. You should be able to see the exception.

Note : Although command retries till the set timeout but when network disconnection persists above the set timeout , i get the RedisCommandTimeoutException. 

RedisCommandTimeoutException from the name suggests that exception is because of slowness in running query and we started looking for slowlogs and couldn't find anything.
But after debugging came to know that it is because of network disconnection.

**Comment by mp911de** [comment] 2018-04-23 16:31
>  I simply removed my LAN cable

This makes a difference in availability and TCP behavior. A clean disconnect puts the client into a defined state. If a server is just unreachable (i.e. no response at all), TCP packets are being retransmitted until reaching the OS timeout for TCP packets.

In that time, the client isn't aware that the server isn't reachable (or comes back again). That said, there's no recovery in the first place if the server is physically reachable again. The client needs to run either into a TCP timeout (note: that's not a read timeout) or get a rejected packet from the server (as the server knows there is no connection) to reset the client. Recovery can, therefore, happen quite a while later.

See also https://stackoverflow.com/questions/13085676/tcp-socket-no-connection-timeout.

**Comment by mp911de** [comment] 2018-05-14 06:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2018-05-14 06:54 UTC
Labels: feedback requested

**Comment by jaimess** [comment] 2018-10-17 20:17
this params would mend it:
echo "1" > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo "10" > /proc/sys/net/ipv4/tcp_keepalive_probes
echo "6" > /proc/sys/net/ipv4/tcp_keepalive_time
echo "3" > /proc/sys/net/ipv4/tcp_retries2

mp911de is right but it may worth have a look to cassandra or elasticsearch drivers which are able to recover from these problem

**Comment by jaimess** [comment] 2018-10-18 07:58
diving a bit I found nettycustommizer, this works too:

        NettyCustomizer nettyCustomizer = new NettyCustomizer() {
            
            @Override
            public void afterChannelInitialized(Channel channel) {
                channel.pipeline().addLast(
                        new IdleStateHandler(readerIdleTimeSeconds, writerIdleTimeSeconds, allIdleTimeSeconds));
                channel.pipeline().addLast(new ChannelDuplexHandler() {
                    @Override
                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
                        if (evt instanceof IdleStateEvent) {
                            ctx.disconnect();
                        }
                    }
                });
            }
            
            @Override
            public void afterBootstrapInitialized(Bootstrap bootstrap) {
            }
            
        };
        ClientResources res = DefaultClientResources.builder()
                .nettyCustomizer(nettyCustomizer ).build();
