### ISSUE TITLE
"Lpushx" Command Error

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#847] opened 2018-09-15 09:42 UTC
#### Current Behavior

I use the lettuce(5.0.2.RELEASE) to execute "lpushx" command, and when I input the key and just one arg, it works well, but when I input more than  one args, it reports exception

#### Input Code
Here is my test code:
long result = conn.syncStr().lpushx("name", "aa");
result = conn.syncStr().lpushx("name", "aa", "cc");

the conn is the object I create, and it uses the lettuce method: 
RedisFuture<Long> lpushx(K key, V... values);
 
the exception detail:

```
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR wrong number of arguments for 'lpushx' command
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:118)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:57)
	at io.lettuce.core.cluster.ClusterCommand.complete(ClusterCommand.java:63)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:563)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:516)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

#### Expected behavior/code

A clear and concise description of what you expected to happen (or code).

#### Environment

- Lettuce version(s): [5.0.2.RELEASE]
- Redis version: [e.g. 4.0.10]

**Comment by StillerRen** [comment] 2018-09-15 09:44
"rpushx" has the same problem

**Comment by mp911de** [comment] 2018-09-15 19:36
Thanks for reporting this issue. This is a duplicate of the conversation in https://github.com/lettuce-io/lettuce-core/issues/267#issuecomment-231473617. Variadic LPUSHX and RPUSHX are available only in newer Redis versions.

**Closed by mp911de** 2018-09-15 19:36 UTC
Labels: status: invalid
