### ISSUE TITLE
Lettuce set and get method IllegalStateException:ValueOutput does not support set(long)

### ISSUE THREAD

**Issue by zhangjianleittntty** [lettuce-io/lettuce-core#1958] opened 2022-01-06 10:08 UTC
#### Current Behavior

I have two docker online environment.It's A and B. 
   Springboot version: 2.4.11
   lettuce version: 6.0.8

First be set(String), than running get(String). Operation normal in the A, but B throw exception,following:

`

    exception: org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is 
    java.lang.IllegalStateException: io.lettuce.core.output.ValueOutput does not support set(long), dubbo version: 2.7.14, current host: 
    org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is 
    java.lang.IllegalStateException: io.lettuce.core.output.ValueOutput does not support set(long)
	at 
    org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:53)
	at 
     org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:43)
	at 
 
 
org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:274)
	at 
 org.springframework.data.redis.connection.lettuce.LettuceStringCommands.convertLettuceAccessException(LettuceStringCommands.java:800)
	
	at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:70)
	
	at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:267)
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:57)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:60)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:222)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:53)
	
	at cn.com.esgcc.gwtrip.utils.redis.RedisUtil.get(RedisUtil.java:150)

`

<details>
<summary>Stack trace</summary>

```java
if (RedisUtil.hasKey(key)) {

            String value = String.valueOf(RedisUtil.get(key));
            return JSON.parseObject(value, TrainStopStationDto.class);
        } else {
            SupResponse<TrainStopStationDto> supResponse = selectServiceBiz.queryTrainStopStation(req);
            if (!Objects.isNull(supResponse.getData()) && CollectionUtils.isNotEmpty(supResponse.getData().getStopStationInfos())) {
                RedisUtil.set(key, JSON.toJSONString(supResponse.getData()), 12, TimeUnit.HOURS);
                return supResponse.getData();
            }
        }


```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. lettuce-core:6.0.8.RELEASE]
- Redis version: [e.g. 3.2.0]

**Comment by mp911de** [comment] 2022-01-11 08:11
Can you provide a minimal reproducer using Lettuce only to reproduce the issue?

**Comment by mp911de** [comment] 2022-01-21 07:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-01-21 07:49 UTC
Labels: status: waiting-for-feedback
