### ISSUE TITLE
Huge numbers of Epoll EventLoopGroup created in a JVM

### ISSUE THREAD

**Issue by sazbad** [lettuce-io/lettuce-core#1215] opened 2020-02-03 23:23 UTC
Recently, we have deployed our code in production and started seeing strange behavior regarding threads. We found that our thread count is continuously increasing and ad some point hitting 3k threads in a single JVM. Taking a thread dump showed that there are almost 3k threads like below which seems to be created by lettuce library. The machine in question has the configuration of 8vcpus, 32 cores and CentOS 7.4.1708 (Core). 

The same code has been deployed in various sites and does not exhibit the behavior.  Can someone share some lights why so many EventLoopGroups been created for this case? This issue essentially crashes the JVM and the deployment becomes unusable. 

```lettuce-epollEventLoop-2300-1
priority:5 - threadId:0x00007f028696f000 - nativeId:0x2aa - nativeId (decimal):682 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at io.netty.channel.epoll.Native.epollWait0(Native Method)
at io.netty.channel.epoll.Native.epollWait(Native.java:96)
at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:276)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None
lettuce-epollEventLoop-2297-1
priority:5 - threadId:0x00007f02866c5000 - nativeId:0x1d0 - nativeId (decimal):464 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at io.netty.channel.epoll.Native.epollWait0(Native Method)
at io.netty.channel.epoll.Native.epollWait(Native.java:96)
at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:276)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None
lettuce-epollEventLoop-2294-1
priority:5 - threadId:0x00007f02866c7000 - nativeId:0x187 - nativeId (decimal):391 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at io.netty.channel.epoll.Native.epollWait0(Native Method)
at io.netty.channel.epoll.Native.epollWait(Native.java:96)
at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:276)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None
lettuce-epollEventLoop-2291-1
priority:5 - threadId:0x00007f0286799000 - nativeId:0x156 - nativeId (decimal):342 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at io.netty.channel.epoll.Native.epollWait0(Native Method)
at io.netty.channel.epoll.Native.epollWait(Native.java:96)
at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:276)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None



lettuce-epollEventLoop-11-1
priority:5 - threadId:0x00007f03dc273800 - nativeId:0x1d79 - nativeId (decimal):7545 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at io.netty.channel.epoll.Native.epollWait0(Native Method)
at io.netty.channel.epoll.Native.epollWait(Native.java:96)
at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:276)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None
lettuce-epollEventLoop-8-1
priority:5 - threadId:0x00007f03dc25d800 - nativeId:0x1d37 - nativeId (decimal):7479 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE
at io.netty.channel.epoll.Native.epollWait0(Native Method)
at io.netty.channel.epoll.Native.epollWait(Native.java:96)
at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:276)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:745)
Locked ownable synchronizers:
- None
```

**Comment by mp911de** [comment] 2020-02-04 08:03
Please do not cross-post. Duplicate of https://groups.google.com/d/msg/lettuce-redis-client-users/3CJECjFQHW8/LFlE3vlVAgAJ.

**Closed by mp911de** 2020-02-04 08:03 UTC
Labels: for: stackoverflow, status: duplicate
