### ISSUE TITLE
OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory 

### ISSUE THREAD

**Issue by bililee** [lettuce-io/lettuce-core#2540] opened 2023-11-01 01:45 UTC
When I use Lettuce for operations, the program is prone to encountering the following error: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 117440519, max: 134217728). In my current scenario, I need to frequently handle relatively large data objects (around 200KB). Do you have any suggestions on how to avoid this error?

**Comment by mp911de** [comment] 2023-11-01 07:46
This is a duplicate of #2531

**Closed by mp911de** 2023-11-01 07:46 UTC
