### ISSUE TITLE
can't connect to redis cluster using ssl on ibmjava

### ISSUE THREAD

**Issue by chershma** [lettuce-io/lettuce-core#1070] opened 2019-06-26 13:02 UTC
hi
my code works well on openjdk and oracle java, but fails on ibmjava
any suggestions?

io.lettuce.core.RedisConnectionException: Unable to connect to redis-10001.redis-qa.mycomp.com:10001
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
        at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:235)
        at io.lettuce.core.RedisClient.connect(RedisClient.java:204)
        at io.lettuce.core.RedisClient.connect(RedisClient.java:189)
        at com.mycomp.mymodule.util.helpers.RedisHelper.initRedisConnection(RedisHelper.java:103)
        at com.mycomp.mymodule.util.helpers.RedisHelper.initSyncCommands(RedisHelper.java:70)
        at com.mycomp.mymodule.util.StaticContextInitializer.init(StaticContextInitializer.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$165.00000000ACB49400.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.mycomp.mymodule.Application.main(Application.java:11)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: io.netty.channel.ExtendedClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source)

**Comment by mp911de** [comment] 2019-06-26 14:28
The cause is still missing, we cannot do anything without it. 
Also, please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by mp911de** [comment] 2019-06-29 16:20
Can you provide an approach how to reproduce the issue? I tried to find an IBM Java Runtime for MacOS but wasn't able to find one.

**Comment by chershma** [comment] 2019-06-30 06:24
I am using docker image: FROM ibmjava:8-jre-alpine

And start a spring boot app with this code:
SslOptions sslOptions = SslOptions.builder().jdkSslProvider()
      .keystore(new File(keyStoreFilePath), keyStorePassword.toCharArray())
      .truststore(new File(trustStoreFilePath), trustStorePassword).build();


ClientOptions clientOptions = ClientOptions.builder().sslOptions(sslOptions).build();


RedisClient redisClient = RedisClient.create("rediss://" + password + "@" + hostName + ":" + port);

redisClient.setOptions(clientOptions);


try {
   // this is where the exception is thrown:
   StatefulRedisConnection<String, String> connection = redisClient.connect();


Thank you
Carmit Hershman
Architect | MIS | Check Point Software Technologies<http://www.checkpoint.com/>
• +972-3-6115075 | M +972-52-4349692 | F +972-3-6241100 | • chershma@checkpoint.com<mailto:chershma@checkpoint.com>

**Comment by mp911de** [comment] 2019-07-02 19:50
Successfully connected using Docker with the IBM JRE:

```
java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 8.0.5.37 - pxa6480sr5fp37-20190618_01(SR5 FP37))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190617_419755 (JIT enabled, AOT enabled)
OpenJ9   - 354b31d
OMR      - 0437c69
IBM      - 4972efe)
JCL - 20190606_01 based on Oracle jdk8u211-b25
```

In my case, I have no proper SSL certificate so I'm bypassing host verification with `redisURI.setVerifyPeer(false);`.

**Comment by chershma** [comment] 2019-07-03 06:09
Can you please send your coed snippet?

Thank you
Carmit Hershman
Architect | MIS | Check Point Software Technologies<http://www.checkpoint.com/>
• +972-3-6115075 | M +972-52-4349692 | F +972-3-6241100 | • chershma@checkpoint.com<mailto:chershma@checkpoint.com>

**Comment by mp911de** [comment] 2019-07-03 06:41
That's the following snippet:

```java
	SslOptions sslOptions = SslOptions.builder().jdkSslProvider().truststore(new File("truststore.jks")).build();

	ClientOptions clientOptions = ClientOptions.builder().sslOptions(sslOptions).build();
	RedisURI redisURI = RedisURI.create("rediss://192.168.55.166:6443");
	redisURI.setVerifyPeer(false);
	RedisClient client = RedisClient.create(redisURI);
	client.setOptions(clientOptions);

	StatefulRedisConnection<String, String> connection = client.connect();

	connection.sync().set("key", "value");

	connection.close();
	client.shutdown();
```

**Comment by chershma** [comment] 2019-07-04 10:47
Thanks. I added the redisURI.setVerifyPeer(false); but it still fails
Are you using a docker file? Can you please share it?

Thank you
Carmit Hershman
Architect | MIS | Check Point Software Technologies<http://www.checkpoint.com/>
• +972-3-6115075 | M +972-52-4349692 | F +972-3-6241100 | • chershma@checkpoint.com<mailto:chershma@checkpoint.com>

**Comment by mp911de** [comment] 2019-07-04 12:47
I was running the example via `docker run ibmjava:8-jre-alpine java -jar my-example.jar`.

**Comment by mp911de** [comment] 2019-07-19 06:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-07-19 06:40 UTC
Labels: for: stackoverflow
