### ISSUE TITLE
DefaultClientResources is not closed  when unable to establish a connection to Redis

### ISSUE THREAD

**Issue by yelliver** [lettuce-io/lettuce-core#1974] opened 2022-01-25 09:33 UTC
#### Current Behavior

<details>
I have a retry mechanism to connect to Redis, after several times of errors that cannot connect to Redis, once it is able to connect to Redis, there is a warning:

` DefaultClientResources - io.lettuce.core.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit) 
`

</details>

#### Input Code

<details>

<summary>Input Code</summary>

```java
      while (true) {
        try {
          log.info("Creating Redis connection...");
          conn = RedisClusterClient.create(redisUri).connect(codec);
          log.info("Successful to create Redis connection");
          break;
        } catch (Exception e) {
          log.error("Fail to create Redis connection, Retrying in {}s: {}", redisRetry, e.toString());
          sleep(redisRetry);
        }
```

</details>

**Comment by mp911de** [comment] 2022-01-25 09:38
Duplicate of #1975

**Closed by mp911de** 2022-01-25 09:38 UTC
