### ISSUE TITLE
RedisCommandTimeoutException at application startup

### ISSUE THREAD

**Issue by emas80** [lettuce-io/lettuce-core#1251] opened 2020-03-31 13:30 UTC
## Current Behavior

We have some hi-traffic applications using Spring Boot and Lettuce as a redis client.
After upgrading to Spring Boot 2.1 and switching from Jedis to Lettuce, we've seen that every time those applications start receiving traffic, for the first 20 to 30 seconds the logs are completly full of RedisCommandTimeoutException, it seems that every command fails because of a timeout.

After 20-30 seconds, the errors completely stop, and the applications work normally, no more redis timeouts.

We use redis mainly as cache layer, using spring-boot-starter-data-redis. Almost all of the commands are get and set.

#### Input Code

This is the code we use to setup the redis pool configuration

```
private final int maxTotal = 100;
private final int maxIdle = 10;
private final int minIdle = 5;
private final int maxWaitMillis = 1000;
private final int numTestsPerEvictionRun = 3;
private final int timeBetweenEvictionRunsMillis = 10000;
private final int commandTimeoutMillis = 100;
private final int connectionTimeoutMillis = 2000;

@Bean
    public LettucePoolingClientConfiguration lettucePoolConfig(ClientResources clientResources) {
        GenericObjectPoolConfig redisPoolConfig = new GenericObjectPoolConfig();

        redisPoolConfig.setMaxTotal(env.getProperty("spring.redis.maxTotal", Integer.class, maxTotal));
        redisPoolConfig.setMaxIdle(env.getProperty("spring.redis.maxIdle", Integer.class, maxIdle));
        redisPoolConfig.setMinIdle(env.getProperty("spring.redis.minIdle", Integer.class, minIdle));
        redisPoolConfig.setMaxWaitMillis(env.getProperty("spring.redis.maxWaitMillis", Integer.class, maxWaitMillis));
        redisPoolConfig.setNumTestsPerEvictionRun(env.getProperty("spring.redis.numTestsPerEvictionRun", Integer.class, numTestsPerEvictionRun));
        redisPoolConfig.setTimeBetweenEvictionRunsMillis(env.getProperty("spring.redis.timeBetweenEvictionRunsMillis", Integer.class, timeBetweenEvictionRunsMillis));

        Integer commandTimoutMillis = env.getProperty("spring.redis.commandTimeoutMillis", Integer.class, commandTimeoutMillis);
        ClientOptions options = ClientOptions.builder().autoReconnect(true).disconnectedBehavior(DisconnectedBehavior.REJECT_COMMANDS)
                .socketOptions(SocketOptions.builder().connectTimeout(Duration.ofMillis(env.getProperty("spring.redis.timeout", Integer.class, connectionTimeoutMillis))).build())
                .timeoutOptions(TimeoutOptions.enabled(Duration.ofMillis(commandTimoutMillis))).build();


        return LettucePoolingClientConfiguration.builder().poolConfig(redisPoolConfig).clientOptions(options).clientName(clientName).clientResources(clientResources)
                .commandTimeout(Duration.ofMillis(commandTimoutMillis)).build();
    }
```

The idea is to have 2 sec connection timeout, and 100ms as command timeout.

#### Expected behavior/code

We would expect the applications to start serving traffic normally.

#### Environment
- Spring Boot 2.1.9
- Lettuce version(s): 5.1.8.RELEASE
- Redis version: 4.0.14 on GCP (Memorystore)

#### Additional context

The applications are microservices serving traffic through http calls, as soon as the applications start receiving traffic Spring cache try contacting Redis but fail because of the RedisCommandTimeoutException for 20 to 30 seconds. 
Please note that as soon as they start receiving traffic, they are receiving a lot of traffic, normally about 2-300 operations per second. They are alll very, very fast, a few ms each because they're mostly get and set (of small amount of data).
The applications run on Kubernetes and have all between 1 and 2 core of required resources

We think it's related to how the connections are established, but we don't understand what could be wrong in our configuration and how to fix it.
We were thinking some sort of pre-warm of the connections, so that they're already available when they're needed in order to avoid the time it takes to establish the connection.
But it seems a command timeout we are hitting, not a connection timeout.

Would you please help us pointing to a better configuration?

**Comment by mp911de** [comment] 2020-03-31 14:51
A command timeout of 100ms is pretty sharp. It sounds as until the JIT kicks in, some bits are so slow that you experience command timeouts. Did you try increasing the timeout to investigate whether that is the cause?

**Comment by emas80** [comment] 2020-03-31 17:51
I've tried setting it to 1 sec, and I still see errors.

We use it for caching, if it takes more than 100ms to read a value from the cache, then it's better to read it from the database.
A timeout of 100ms is acceptable, even if not optimal (ideally we would like to go down even to 30-50ms) because at least we hit the database and we can reply in a reasonable amount of time.

The real problem here is that it's possible that one call to the end point triggers multiple GET to redis, and so the timeouts are chained when the application starts and this can cause issues to the caller because instead of 20ms all the calls for the first 30 seconds take a few seconds.

I'have some logs from one instance on our production environment, this is when the requests start hitting the application:

```
2020-03-31T15:05:15.814Z 61144 [http-nio-8080-exec-141] io.lettuce.core.RedisClient - Trying to get a Redis connection for: RedisURI [host='XXXXX', port=6379] 
2020-03-31T15:05:16.632Z 61962 [http-nio-8080-exec-141] io.lettuce.core.EpollProvider - Starting without optional epoll library 
2020-03-31T15:05:16.637Z 61967 [http-nio-8080-exec-141] io.lettuce.core.KqueueProvider - Starting without optional kqueue library 
2020-03-31T15:05:16.783Z 62113 [http-nio-8080-exec-141] i.l.c.r.DefaultEventLoopGroupProvider - Allocating executor io.netty.channel.nio.NioEventLoopGroup 
2020-03-31T15:05:16.783Z 62113 [http-nio-8080-exec-141] i.l.c.r.DefaultEventLoopGroupProvider - Creating executor io.netty.channel.nio.NioEventLoopGroup 
2020-03-31T15:05:16.828Z 62158 [http-nio-8080-exec-141] i.l.c.r.DefaultEventLoopGroupProvider - Adding reference to io.netty.channel.nio.NioEventLoopGroup@50d82160, existing ref count 0 
2020-03-31T15:05:16.912Z 62242 [http-nio-8080-exec-141] io.lettuce.core.RedisClient - Resolved SocketAddress XXXXX:6379 using RedisURI [host='XXXXX', port=6379] 
2020-03-31T15:05:16.914Z 62244 [http-nio-8080-exec-141] io.lettuce.core.RedisClient - Connecting to Redis at XXXXX:6379 
2020-03-31T15:05:17.425Z 62755 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x33826780, [id: 0x013bdafc] (inactive), chid=0x1] channelRegistered() 
2020-03-31T15:05:17.442Z 62772 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, chid=0x1] channelActive() 
2020-03-31T15:05:17.444Z 62774 [lettuce-nioEventLoop-4-1] i.l.core.protocol.DefaultEndpoint - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, epid=0x1] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered 
2020-03-31T15:05:17.445Z 62775 [lettuce-nioEventLoop-4-1] i.l.core.protocol.DefaultEndpoint - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, epid=0x1] activating endpoint 
2020-03-31T15:05:17.445Z 62775 [lettuce-nioEventLoop-4-1] i.l.core.protocol.DefaultEndpoint - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, epid=0x1] flushCommands() 
2020-03-31T15:05:17.445Z 62775 [lettuce-nioEventLoop-4-1] i.l.core.protocol.DefaultEndpoint - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, epid=0x1] flushCommands() Flushing 0 commands 
2020-03-31T15:05:17.446Z 62776 [lettuce-nioEventLoop-4-1] i.l.c.protocol.ConnectionWatchdog - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, last known addr=XXXXX/192.168.17.4:6379] channelActive() 
2020-03-31T15:05:17.446Z 62776 [lettuce-nioEventLoop-4-1] i.l.c.protocol.ConnectionWatchdog - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, last known addr=XXXXX/192.168.17.4:6379] channelActive() 
2020-03-31T15:05:17.450Z 62780 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x33826780, /10.8.47.180:46942 -> XXXXX/192.168.17.4:6379, chid=0x1] channelActive() done 
2020-03-31T15:05:17.451Z 62781 [lettuce-nioEventLoop-4-1] io.lettuce.core.RedisClient - Connecting to Redis at XXXXX:6379: Success 

```

1.5 sec to have a connection during the startup. That seems a lot. Please note it's a production application with a production setup: it runs on Google Kubernetes Engine with MemoryStore in the same region and it's plenty of resources. It's not a new app, it's been running for a few years, even if only recently we've started (in this specific app) to use redis more than before (doubling the traffic to redis), the general setup is battle tested.
This log is from when the timeout is 100ms, we have similar values (of course) when we set the timeout to be 1sec.
After the "Success", then A LOT of commands are executed.

Running the same code locally, it takes about 800ms to establish a connection (if that is what the logs mean). Redis was running on docker in my test.

I also do not see any other RedisClient log in the production application logs, I've kept it running for 5 minutes in debug mode - does that mean that it is only one connection?

**Comment by mp911de** [comment] 2020-04-01 07:13
The first connection is tied to a lot of initialization code so 600 to 1000ms for the first connection are pretty normal. The creation of the event loop and timer (threads) alone takes around 300 ms. Classloading, buffer pool initialization, and native transport detection take another 600 ms.

![Screenshot 2020-04-01 09 11 47](https://user-images.githubusercontent.com/1035015/78109179-09ff5200-73f9-11ea-9a82-3e1533a95806.png)

Once Lettuce is initialized, subsequent connection creation takes only 3-4ms.

**Comment by emas80** [comment] 2020-04-01 08:26
Ok, so those times are normal. I've managed to have more than one connection, and yes it takes a few millis to open a new one after the startup.

So, do you think there is something wrong in our setup? Or is it expected that if we set 1sec we are failing almost all of the command (I remember: GET and SET) during the first 30 sec) under a lot of load?
Maybe there is some sort of queue? They are queued and executed after that the connection is open 
(e.g. after 1 sec) and some of them run into the timeout?

I can provide some more logs - they're not well organized as the app receives a lot of traffic and it's hard to understand what is going on, but in general this is the pattern:

After the connection being established, I see

```
D 2020-03-31T17:35:48.161Z 59974 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.162Z 59975 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.162Z 59975 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.163Z 59976 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.163Z 59976 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.163Z 59976 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.163Z 59976 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.164Z 59977 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.164Z 59977 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.168Z 59981 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.172Z 59985 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.176Z 59989 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.177Z 59990 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] write(ctx, AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise) 
D 2020-03-31T17:35:48.177Z 59990 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandEncoder - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379] writing command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.178Z 59991 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Received: 1024 bytes, 64 commands in the stack 
D 2020-03-31T17:35:48.178Z 59991 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 64 commands 
D 2020-03-31T17:35:48.178Z 59991 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.179Z 59992 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: false 
D 2020-03-31T17:35:48.179Z 59992 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Received: 16384 bytes, 64 commands in the stack 
D 2020-03-31T17:35:48.180Z 59993 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 64 commands 
D 2020-03-31T17:35:48.181Z 59994 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.181Z 59994 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@27588e8a, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.182Z 59995 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 63 commands 
D 2020-03-31T17:35:48.183Z 59996 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.184Z 59997 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@fa034a9, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.184Z 59997 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 62 commands 
D 2020-03-31T17:35:48.184Z 59997 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.184Z 59997 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@7af1f10a, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.188Z 60001 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 61 commands 
D 2020-03-31T17:35:48.189Z 60002 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.189Z 60002 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: false 
D 2020-03-31T17:35:48.190Z 60003 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Received: 65536 bytes, 61 commands in the stack 
D 2020-03-31T17:35:48.191Z 60004 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 61 commands 
D 2020-03-31T17:35:48.191Z 60004 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.192Z 60005 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@3f0eab0, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.192Z 60005 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 60 commands 
D 2020-03-31T17:35:48.193Z 60006 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.193Z 60006 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@60bf089a, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.194Z 60007 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 59 commands 
D 2020-03-31T17:35:48.194Z 60007 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.194Z 60007 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@6e346d58, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.195Z 60008 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 58 commands 
D 2020-03-31T17:35:48.195Z 60008 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.195Z 60008 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@1b38b835, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.196Z 60009 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 57 commands 
D 2020-03-31T17:35:48.196Z 60009 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand] 
D 2020-03-31T17:35:48.197Z 60010 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@1f997488, error='null'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
D 2020-03-31T17:35:48.197Z 60010 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 56 commands 
```

hundreds of lines like those, in less than one second, this is just a very small part.

Then after about 1 second I start to see the redis error handler handling the RedisCommandTimeoutException:

```

D 2020-03-31T17:35:48.618Z 60431 [http-nio-8080-exec-26] io.lettuce.core.RedisChannelHandler - dispatching command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.619Z 60432 [http-nio-8080-exec-26] i.l.core.protocol.DefaultEndpoint - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, epid=0x1] write() writeAndFlush command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
W 2020-03-31T17:35:48.640Z 60453 [http-nio-8080-exec-81] c.f.c.cache.RedisCacheErrorHandler - exception on get cache [accessTokenService] key [token:YYYY], fallback to noop: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s) 
D 2020-03-31T17:35:48.641Z 60454 [http-nio-8080-exec-26] i.l.core.protocol.DefaultEndpoint - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, epid=0x1] write() done 
W 2020-03-31T17:35:48.641Z 60454 [http-nio-8080-exec-197] c.f.c.cache.RedisCacheErrorHandler - exception on get cache [accessTokenService] key [token:YYYY], fallback to noop: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s) 
D 2020-03-31T17:35:48.642Z 60455 [http-nio-8080-exec-126] io.lettuce.core.RedisChannelHandler - dispatching command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
D 2020-03-31T17:35:48.642Z 60455 [http-nio-8080-exec-126] i.l.core.protocol.DefaultEndpoint - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, epid=0x1] write() writeAndFlush command AsyncCommand [type=GET, output=ValueOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command] 
W 2020-03-31T17:35:48.647Z 60460 [http-nio-8080-exec-40] c.f.c.cache.RedisCacheErrorHandler - exception on get cache [accessTokenService] key [token:YYYY], fallback to noop: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s) 
W 2020-03-31T17:35:48.648Z 60461 [http-nio-8080-exec-112] c.f.c.cache.RedisCacheErrorHandler - exception on get cache [accessTokenService] key [token:YYYY], fallback to noop: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s) 
D 2020-03-31T17:35:48.648Z 60461 [lettuce-nioEventLoop-4-1] i.l.core.protocol.CommandHandler - [channel=0x791ced3b, /10.8.43.7:32898 -> XXXXX/192.168.17.4:6379, chid=0x1] Stack contains: 26 commands 
D 2020-03-31T17:35:48.648Z 60461 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decode LatencyMeteredCommand [type=GET, output=ValueOutput [output=null, error='Command timed out after 1 second(s)'], commandType=io.lettuce.core.protocol.AsyncCommand] 
W 2020-03-31T17:35:48.648Z 60461 [http-nio-8080-exec-55] c.f.c.cache.RedisCacheErrorHandler - exception on get cache [accessTokenService] key [token:YYYY], fallback to noop: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s) 
D 2020-03-31T17:35:48.649Z 60462 [lettuce-nioEventLoop-4-1] i.l.core.protocol.RedisStateMachine - Decoded LatencyMeteredCommand [type=GET, output=ValueOutput [output=[B@4298933, error='Command timed out after 1 second(s)'], commandType=io.lettuce.core.protocol.AsyncCommand], empty stack: true 
```

and it's like that for the next 20 to 30 seconds (exception from Spring Error Handler and Lettuce logs), after that the timeout exceptions completely disappear and it's just Lettuce debug log.

**Comment by mp911de** [comment] 2020-04-01 09:24
To me, it seems like a temporary overload. The log above shows that roughly 8 commands get processed within 20ms. So I think what you see is the effect of warming the application. Until all JIT compilation is done (collecting profiling data, identifying hot code paths, compilation), the required throughput cannot be met.

I recommend issuing a few hundred Redis requests during startup until your app is able to handle the required load. Ideally, run your application with [jitwatch](https://github.com/AdoptOpenJDK/jitwatch) to measure how long it typically takes until your app is ready after starting the JVM.

**Comment by emas80** [comment] 2020-04-01 14:23
We have already tried doing that, issuing some ping commands just after the startup, but it didn't see it helped. It wasn't a few hundreds, it was much less than that.
We initially thought the reason was it was using always the same connection, without opening new ones, but maybe the reason was that the number of requests was not enough?

Please consider that the application starts currently in about 20 seconds, but it does not receive traffic immediately, it starts receiving traffic about 50 seconds later.

Do you have any other suggestion on how to prewam the redis connections?

**Comment by mp911de** [comment] 2020-04-01 14:30
Without additional data, it's hard to say anything. Therefore I recommend jitwatch to observe what happens on the JIT before we can proceed.

**Comment by mp911de** [comment] 2020-04-15 08:24
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-04-15 08:24 UTC
Labels: status: waiting-for-triage

**Comment by rkoushik10** [comment] 2020-11-25 18:15
We are also facing a similar issue, for 20-25 sec lettuce taking time to initialize and due to this circuit breaker is opening, We are thinking before bringing service into Load Balancer will bombard request for 30sec.

Do you have any better solution for this? Please suggest.

**Comment by parmar049** [comment] 2022-07-01 09:46
I am also having the same issue mentioned by @emas80 .

**Comment by zoltan-toth-mw** [comment] 2022-09-19 09:40
For us creating the connection upfront helped but didn't fix all the problems. We increased the timeout from 500ms to 1000 and limited the tomcat threads to 140 (was 200) and the startup issue is gone.

```
 public static class LettuceConnectionFactoryCustomizer implements BeanPostProcessor {

        @Nullable
        @Override
        public Object postProcessBeforeInitialization(@NonNull Object bean, @NonNull String beanName) throws BeansException {
            if (bean instanceof LettuceConnectionFactory factory) {
                factory.setEagerInitialization(true);
            }
            return bean;
        }

    }
```
