### ISSUE TITLE
Outputting repeated "Reconnecting last destination" and "Reconnected to" log messages

### ISSUE THREAD

**Issue by sdYoo** [lettuce-io/lettuce-core#2480] opened 2023-08-14 08:15 UTC
#### Current Behavior

Hello,

I use lettuce to connect to Redis(ha+sentinel), I get the following log output repeatedly:
I want to know why the log below occurs although functions such as data retrieval and saving work normally.
I would like to know in detail whether the log is a normal log or a problem.
I want know under what circumstances the logs below occur.

Thanks 

<details>
<summary>Stack trace</summary>

2023-08-14T16:37:49.482+09:00  INFO 7669 --- [xecutorLoop-1-9] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was sandbox.com/10.1.1.1:6379
2023-08-14T16:37:49.525+09:00  INFO 7669 --- [oEventLoop-6-10] i.l.core.protocol.ReconnectionHandler    : Reconnected to sandbox.com/<unresolved>:6379
2023-08-14T16:38:04.578+09:00  INFO 7669 --- [ecutorLoop-1-10] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was sandbox.com/10.1.1.1:6379
2023-08-14T16:38:04.618+09:00  INFO 7669 --- [ioEventLoop-6-1] i.l.core.protocol.ReconnectionHandler    : Reconnected to sandbox.com/<unresolved>:6379
2023-08-14T16:38:19.680+09:00  INFO 7669 --- [xecutorLoop-1-1] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was sandbox.com/10.1.1.1:6379
2023-08-14T16:38:19.716+09:00  INFO 7669 --- [ioEventLoop-6-2] i.l.core.protocol.ReconnectionHandler    : Reconnected to sandbox.com/<unresolved>:6379
2023-08-14T16:38:34.778+09:00  INFO 7669 --- [xecutorLoop-1-2] i.l.core.protocol.ConnectionWatchdog     : Reconnecting, last destination was sandbox.com/10.1.1.1:6379
2023-08-14T16:38:34.821+09:00  INFO 7669 --- [ioEventLoop-6-3] i.l.core.protocol.ReconnectionHandler    : Reconnected to sandbox.com/<unresolved>:6379

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
  @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        // redis option
        RedisStandaloneConfiguration redisConfiguration = new RedisStandaloneConfiguration();
        redisConfiguration.setHostName(host);
        redisConfiguration.setPort(port);
        redisConfiguration.setPassword(password);

        // lettuce option
        ClientOptions clientOptions = ClientOptions.builder()
                .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                .autoReconnect(true)
                .socketOptions(SocketOptions.builder().connectTimeout(Duration.ofSeconds(600)).build())
                .build();

        LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder()
                .commandTimeout(Duration.ofMinutes(1))
                .shutdownTimeout(Duration.ZERO)
                .clientOptions(clientOptions)
                //.readFrom(ReadFrom.REPLICA_PREFERRED)
                //.clientOptions(ClientOptions.builder().autoReconnect(true).build())
                //.clientOptions(ClientOptions.builder().timeoutOptions(TimeoutOptions.builder().connectionTimeout().build()).build())
                .build();

        return new LettuceConnectionFactory(redisConfiguration, lettuceClientConfiguration);
    }
```

```redis config

redis:6379> config get timeout
1) "timeout"
2) "0"
redis:6379> config get tcp*
1) "tcp-backlog"
2) "511"
3) "tcp-keepalive"
4) "300"

```

</details>

#### Environment

- Lettuce version(s): latest
- Redis version: 7.0.7

**Comment by mp911de** [comment] 2023-08-14 09:32
Duplicate of #2479

**Closed by mp911de** 2023-08-14 09:32 UTC
