### ISSUE TITLE
Lettuce Throwing  java.lang.IndexOutOfBoundsException.

### ISSUE THREAD

**Issue by HarryTheHawk** [lettuce-io/lettuce-core#735] opened 2018-03-18 17:53 UTC
Hello,

We are finding that some of our lettuce client hosts start spontaneously throwing the following exception:

```
Caused by: com.lambdaworks.redis.RedisException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at com.lambdaworks.redis.cluster.MultiNodeExecution.execute(MultiNodeExecution.java:31)
    at com.lambdaworks.redis.cluster.RedisAdvancedClusterAsyncCommandsImpl.lambda$mget$1(RedisAdvancedClusterAsyncCommandsImpl.java:118)
    at com.lambdaworks.redis.cluster.PipelinedRedisFuture.lambda$new$0(PipelinedRedisFuture.java:24)
    at com.lambdaworks.redis.protocol.AsyncCommand.completeResult(AsyncCommand.java:88)
    at com.lambdaworks.redis.protocol.AsyncCommand.complete(AsyncCommand.java:76)
    at com.lambdaworks.redis.protocol.CommandWrapper.complete(CommandWrapper.java:30)
    at com.lambdaworks.redis.cluster.ClusterCommand.complete(ClusterCommand.java:44)
    at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:170)
    at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:141)
    at com.lambdaworks.redis.cluster.RedisAdvancedClusterAsyncCommandsImpl.lambda$null$0(RedisAdvancedClusterAsyncCommandsImpl.java:118)
    at com.lambdaworks.redis.cluster.MultiNodeExecution.execute(MultiNodeExecution.java:29)
```
Some of the host continue to throw this exception until they are restarted, while others will heal on their own.

We do not see anything interesting in the DEBUG logs leading up to these exceptions; no disconnects or errors, just the expected output leading to the exception such as:
```
15 Mar 2018 11:30:30,413 [DEBUG] {} (lettuce-nioEventLoop-3-7) com.lambdaworks.redis.protocol.RedisStateMachine: Decoded ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[null], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0], empty stack: true
15 Mar 2018 11:30:30,413 [DEBUG] {} (lettuce-nioEventLoop-3-3) com.lambdaworks.redis.protocol.RedisStateMachine: Decode ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0]
15 Mar 2018 11:30:30,413 [DEBUG] {} (lettuce-nioEventLoop-3-3) com.lambdaworks.redis.protocol.RedisStateMachine: Decoded ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[null], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0], empty stack: true
```
Our environment:
Lettuce 4.1.1.Final
Redis 3.2

[Link to code where exception is thrown.](https://github.com/lettuce-io/lettuce-core/blob/d4dc4095996ddc0bacf0c14696bf620b8017522e/src/main/java/com/lambdaworks/redis/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L118)

**Comment by mp911de** [comment] 2018-03-19 07:25
Care to upgrade to Lettuce 4.4.3?

**Comment by HarryTheHawk** [comment] 2018-03-19 16:23
We are in the process of migrating to 4.4.3 - just conducting some final testing.

**Comment by sheen-aa** [comment] 2018-03-23 05:31
We also see the same exception with 4.1.1.Final. As a result of internal restriction, we cannot migrate immediately. Can you share the patch to this issue so we can fix it internally temporarily? 
> Care to upgrade to Lettuce 4.4.3?

**Comment by mp911de** [comment] 2018-03-23 07:58
Currently, the cause is unknown. It seems to be caused by a protocol offset.

**Comment by sheen-aa** [comment] 2018-03-24 01:41
Are there any suggestions at this stage?

**Comment by mp911de** [comment] 2018-03-24 09:13
You might want to record a debug log to see what causes the actual protocol offset.

**Comment by sheen-aa** [comment] 2018-03-25 13:07
Is it expected that a RedisFuture is used when aConnection.sync().mget(keys) is called?

**Comment by mp911de** [comment] 2018-03-25 15:27
@sheen-aa Yes. Lettuce is an asynchronous/reactive driver and the synchronous API is a synchronization layer on top of the asynchronous API.

**Comment by sheen-aa** [comment] 2018-03-27 07:20
When mget returns only one element, exists returns null.

**Comment by mp911de** [comment] 2018-03-27 07:38
@sheen-aa I don't follow. Care to elaborate? Which exists are you talking about?

**Comment by sheen-aa** [comment] 2018-03-27 08:39
I check some of the failing requests and find that all values for keys passing to mget of Redis do not exist. Then I want to confirm whether all failing requests do not have values for all keys and call exists of Redis with the same set of keys passed to mget of Redis and find that exists of Redis returns null instead of 0. 
> @sheen-aa I don't follow. Care to elaborate? Which exists are you talking about?

**Comment by sheen-aa** [comment] 2018-03-27 09:15
* In [this page](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster), `EXISTS` and `MGET` are both documented as "supported for cross-slot command execution". As written in my last comment, I cannot use `EXISTS` to count how many keys exist when `MGET` fails without all values returned. However, `GET` behaves as normal.
* I am only call mget with all keys passed in the same slot. During one debug run, I find:
  ** Lettuce `mget` returns at [this line](https://github.com/lettuce-io/lettuce-core/blob/4.1.x/src/main/java/com/lambdaworks/redis/cluster/RedisAdvancedClusterAsyncCommandsImpl.java#L130).
  ** [This line](https://github.com/lettuce-io/lettuce-core/blob/4.1.x/src/main/java/com/lambdaworks/redis/cluster/StatefulRedisClusterConnectionImpl.java#L343) is executed multiple times inside one `mget` call.
* Normally, it happens more frequently on higher TPS and does not happen with manual test. However, I was once able to "reproduce" this `MGET` behavior with `mget(key1, key2, key3)` only for several times in a manual test with key1 and key3 exist while key2 not.

 Does it seem to be related to cross-slot command execution?

**Comment by sheen-aa** [comment] 2018-03-27 09:40
> Using keys that reside in the same slot doesn't cause IndexOutOfBoundsException as the code path isn't executed in which the result correlation happens. I'm not able to reproduce the issue, neither with 4.1 nor 4.4.

I think this is exactly why it seems interesting and why I am commenting this. We use hash tag of Redis and all 3 keys passed to `mget` have the same hash tag.

> If you are able to reproduce the issue, please capture the debug log to track down what happened.

Below is a sample DEBUG log with some sensitive value replaced:
```
25 Mar 2018 12:02:40,222 [DEBUG] INTERNAL_TRACE_ID_1 (INTERNAL_NAME_X : 5) RedisChannelHandler: dispatching command AsyncCommand [type=MGET, output=ValueListOutput [output=[], error='null'], commandType=com.lambdaworks.redis.protocol.Command]
25 Mar 2018 12:02:40,222 [DEBUG] INTERNAL_TRACE_ID_1 (INTERNAL_NAME_X : 5) PooledClusterConnectionProvider: getConnection(READ, 10382)
25 Mar 2018 12:02:40,222 [DEBUG] INTERNAL_TRACE_ID_1 (INTERNAL_NAME_X : 5) CommandHandler: [/HOST:PORT_1 -> /HOST:PORT_2] write() writeAndFlush Command ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0]
25 Mar 2018 12:02:40,222 [DEBUG] INTERNAL_TRACE_ID_1 (INTERNAL_NAME_X : 5) CommandHandler: [/HOST:PORT_1 -> /HOST:PORT_2] write() done 
25 Mar 2018 12:02:40,222 [DEBUG] INTERNAL_TRACE_ID_2 (lettuce-nioEventLoop-3-6) CommandEncoder: [/HOST:PORT_1 -> /HOST:PORT_2] writing command ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0]
25 Mar 2018 12:02:40,222 [DEBUG] INTERNAL_TRACE_ID_2 (lettuce-nioEventLoop-3-6) CommandHandler: [/HOST:PORT_1 -> /HOST:PORT_2] Queue contains: 1 commands
25 Mar 2018 12:02:40,223 [DEBUG] INTERNAL_TRACE_ID_2 (lettuce-nioEventLoop-3-6) RedisStateMachine: Decode ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0]
25 Mar 2018 12:02:40,223 [DEBUG] INTERNAL_TRACE_ID_2 (lettuce-nioEventLoop-3-6) RedisStateMachine: Decoded ClusterCommand [command=AsyncCommand [type=MGET, output=ValueListOutput [output=[REAL_OUTPUT_VALUE_1], error='null'], commandType=com.lambdaworks.redis.protocol.Command], executions=0], empty stack: true 
```

**Comment by mp911de** [comment] 2018-03-27 12:10
Thanks. The debug log shows very little and nothing unusual. We'd need to have a larger section showing an interaction between multiple commands with one or two commands executed before on the same connection. I understand if you have concerns regarding sensitive data.

**Comment by sheen-aa** [comment] 2018-03-27 12:34
Thanks for your understanding! By "unusual", do you have something on suspicion so I can pay more attention in the log? As has been commented by HarryTheHawk, there is "just the expected output". We cannot reproduce it stably, but it does happen a lot so I need to pick lines which are more suspicious.

Also, is it possible to use `mget` in a normal mode which is not supported for cross-slot command execution? By normal mode, I want to mean the mode `get` uses?

**Comment by mp911de** [comment] 2018-03-27 13:21
I suspect there's some offset in the protocol meaning there's a response on the decode buffer that gets used to complete commands and which does not belong to the actual command but the previous one. It's hard to debug how/where a particular response sneaked in as Lettuce 4 reuses `CommandHandler` and its buffer across multiple TCP connections. Lettuce 5 spins up always a fresh `CommandHandler` and decode buffer which would solve the issue naturally.

Regarding your second question, you can fetch node connections directly if you know that a command should hit a particular node. Node connections don't apply aggregation/routing of commands but are regular standalone connections.

**Comment by sheen-aa** [comment] 2018-03-28 06:38
Is there a way such as manually closing TCP connection or creating another new `CommandHandler` to recover from a failing state?

I find the following tracebacks during `mget` issue for some `get` calls:
```
com.lambdaworks.redis.RedisException: java.lang.IllegalStateException
        at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:106)
        at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:74)
        at com.lambdaworks.redis.cluster.StatefulRedisClusterConnectionImpl$ClusterFutureSyncInvocationHandler.handleInvocation(StatefulRedisClusterConnectionImpl.java:343)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(Unknown Source)
        at com.sun.proxy.$Proxy13.get(Unknown Source)
        at com.amazon.cn3p.dao.cache.redis.RedisSableCacheDao.getCache(RedisSableCacheDao.java:144)
        ... 62 more
Caused by: java.lang.IllegalStateException
        at com.lambdaworks.redis.output.CommandOutput.set(CommandOutput.java:63)
        at com.lambdaworks.redis.protocol.RedisStateMachine.lambda$safeSet$0(RedisStateMachine.java:178)
        at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:195)
        at com.lambdaworks.redis.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:178)
        at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:118)
        at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:162)
        at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:141)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
```

**Comment by mp911de** [comment] 2018-03-28 08:04
You can either recreate the connection or call `.reset()`. That's also the same issue. `GET` decodes an integer response from a previous command.

**Comment by mp911de** [comment] 2018-04-17 08:32
Closing this one as it seems we cannot do anything further here.

**Closed by mp911de** 2018-04-17 08:32 UTC
Labels: bug, feedback requested
