### ISSUE TITLE
StackOverflow when startup

### ISSUE THREAD

**Issue by 1522140840** [lettuce-io/lettuce-core#1568] opened 2020-12-25 02:40 UTC
2020-12-24 20:25:15.153 [lettuce-nioEventLoop-25-21] WARN  io.lettuce.core.protocol.CommandHandler - null Unexpected exception during request: java.lang.StackOverflowError
java.lang.StackOverflowError: null
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2013)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:1982)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:1794)

**Comment by 1522140840** [comment] 2020-12-25 02:56
When the system starts, there is only this warning and there is no exception. It's all right after it's started。
version：5.2.1

**Comment by mp911de** [comment] 2020-12-25 09:39
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2021-01-08 14:04
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-01-08 14:04 UTC
