### ISSUE TITLE
migrated from oracle to IBM java - now getting netty Failed to initialize a channel

### ISSUE THREAD

**Issue by chershma** [lettuce-io/lettuce-core#1067] opened 2019-06-25 12:29 UTC
I have a docker container trying to connect to redis cluster.
When its using Oracle or openjdk jvms the connection works fine
But, when I start from an IBM java, it fails with:

```
io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xc27adaa5]
```

the lettuce failure log is io.lettuce.core.RedisConnectionException: Unable to connect to redis-server.mycomp.com

this is a sample of connecting code:

```
String trustStoreType = "JKS";
String keyStoreType = "PKCS12" ;
...
SslOptions sslOptions = SslOptions.builder().jdkSslProvider()
				.keystore(new File(keyStoreFilePath), keyStorePassword.toCharArray())
				.truststore(new File(trustStoreFilePath), trustStorePassword).build();
ClientOptions clientOptions = ClientOptions.builder().sslOptions(sslOptions).build();
RedisClient redisClient = RedisClient.create("rediss://" + password + "@" + hostName + ":" + port);
redisClient.setOptions(clientOptions);
StatefulRedisConnection<String, String> connection = redisClient.connect();
```

The exception is thrown for the last line of code 

Any idea?

Thank you
Carmit

**Comment by mp911de** [comment] 2019-06-26 06:20
Please post the full exception stack trace including all causes. Otherwise, we do not have sufficient information to diagnose the issue.

**Comment by chershma** [comment] 2019-06-26 06:31
Its two log lines:
First a log message:
----------------------------------
"logger_name":"io.netty.channel.ChannelInitializer"
"message":"Failed to initialize a channel. Closing: [id: 0xc27adaa5]"}

And then an exception:
-----------------------------------
Unable to connect to redis-10001.redis-qa.mycomp.com:10001\\n[io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:235)
io.lettuce.core.RedisClient.connect(RedisClient.java:204)
io.lettuce.core.RedisClient.connect(RedisClient.java:189)
com.mycomp.mymodule.util.helpers.RedisHelper.initRedisConnection(RedisHelper.java:97)
com.mycomp.mymodule.util.helpers.RedisHelper.initSyncCommands(RedisHelper.java:65)
com.mycomp.mymodule.util.StaticContextInitializer.init(StaticContextInitializer.java:33)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
java.lang.reflect.Method.invoke(Method.java:508)
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$165.0000000078ADB340.getObject(Unknown Source)
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843)
org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
com.mycomp.mymodule.Application.main(Application.java:11)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
java.lang.reflect.Method.invoke(Method.java:508)
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51

Thank you
Carmit Hershman
Architect | MIS | Check Point Software Technologies<http://www.checkpoint.com/>
• +972-3-6115075 | M +972-52-4349692 | F +972-3-6241100 | • chershma@checkpoint.com<mailto:chershma@checkpoint.com>

**Comment by mp911de** [comment] 2019-06-26 06:36
This does not look complete. There are typically `Caused by` elements.

**Comment by chershma** [comment] 2019-06-26 07:22
That’s what I have:

"logger_name":"io.netty.channel.ChannelInitializer","level":"WARN","level_value":30000,"message":"Failed to initialize a channel. Closing: [id: 0xe6705625]"}
"message":"{\"exception\":\"io.lettuce.core.RedisConnectionException: Unable to connect to redis-10001.mis-redis-qa.mycomp.com:10001\",\"call_sess_id\":\"NA\",\"method\":\"initRedisConnection\",\"level\":\"ERROR\",\"logger\":\"com.mycomp.mymodule.util.helpers.RedisHelper\",\"type\":\"MS-APPLICATION\",\"message\":\"Unable to connect to redis-10001.mis-redis-qa.mycomp.com:10001\\n[io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78), io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56), io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:235), io.lettuce.core.RedisClient.connect(RedisClient.java:204), io.lettuce.core.RedisClient.connect(RedisClient.java:189), com.mycomp.mymodule.util.helpers.RedisHelper.initRedisConnection(RedisHelper.java:98), com.mycomp.mymodule.util.helpers.RedisHelper.initSyncCommands(RedisHelper.java:66), com.mycomp.mymodule.util.StaticContextInitializer.init(StaticContextInitializer.java:33), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55), java.lang.reflect.Method.invoke(Method.java:508), org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363), org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307), org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136), org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414), org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770), org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593), org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515), org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320), org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$165.000000007CB62810.getObject(Unknown Source), org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222), org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318), org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199), org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:843), org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877), org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549), org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142), org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775), org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397), org.springframework.boot.SpringApplication.run(SpringApplication.java:316), org.springframework.boot.SpringApplication.run(SpringApplication.java:1260), org.springframework.boot.SpringApplication.run(SpringApplication.java:1248), com.mycomp.mymodule.Application.main(Application.java:11), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55), java.lang.reflect.Method.invoke(Method.java:508), org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48), org.springframework.boot.loader.Launcher.launch(Launcher.java:87), org.springframework.boot.loader.Launcher.launch(Launcher.java:50), org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)]

"logger_name":"org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext","level":"WARN","level_value":30000,"message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'staticContextInitializer': Invocation of init method failed; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to redis-10001.mis-redis-qa.mycomp.com:10001



Thank you
Carmit Hershman
Architect | MIS | Check Point Software Technologies<http://www.checkpoint.com/>
• +972-3-6115075 | M +972-52-4349692 | F +972-3-6241100 | • chershma@checkpoint.com<mailto:chershma@checkpoint.com>

**Comment by mp911de** [comment] 2019-06-26 07:50
You logging tool then strips the causes as it shows only the outermost exception. We cannot do anything without a cause. 

Closing this issue, therefore. Feel free to reopen it once you have more information.

**Closed by mp911de** 2019-06-26 07:50 UTC
Labels: status: waiting-for-feedback

**Comment by chershma** [comment] 2019-06-26 13:03
Found it. Opened a new question on https://github.com/lettuce-io/lettuce-core/issues/1070

Thank you
Carmit Hershman
Architect | MIS | Check Point Software Technologies<http://www.checkpoint.com/>
• +972-3-6115075 | M +972-52-4349692 | F +972-3-6241100 | • chershma@checkpoint.com<mailto:chershma@checkpoint.com>
