### ISSUE TITLE
StatefulRedisClusterConnection.close method hangs indefinitely in 6.0.0.RC1

### ISSUE THREAD

**Issue by terrytheplatypus** [lettuce-io/lettuce-core#1397] opened 2020-08-25 16:16 UTC
#### Current Behavior
When i create a StatefulRedisClusterConnection, do some simple async set commands over it, and try to close it, it never closes. I don't have a stack trace for this because the program never terminates.

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

Java

<details>
<summary>Input Code</summary>

```java
RedisURI r = RedisURI.Builder
                .redis(ip, 6379).build();

        RedisClusterClient client = RedisClusterClient.create(r);
        System.out.println("Client is created");
        StatefulRedisClusterConnection<String, String> connection = client.connect();
 commands.setAutoFlushCommands(false);
List<RedisFuture<?>> futures = Lists.newArrayList();
        for (int i = 0; i < 20; i++) {
            futures.add(commands.set("key-" + i, "value-" + i));
            futures.add(commands.expire("key-" + i, 3600));
            System.out.println("Iteration" + i);
        }
for(RedisFuture f:futures) {
            System.out.println("Awaiting command" + q++);
            try {
                f.await(100, TimeUnit.MILLISECONDS);
            } catch (InterruptedException ex) {
                System.out.println(ex.getMessage());
            }
        }
commands.flushCommands();
connection.close();
```

</details>

#### Expected behavior/code

StatefulRedisClusterConnection.close method should close the connection and terminate instead of hanging.

#### Environment

Lettuce  6.0.0.RC1
Redis 6.0.6

**Comment by mp911de** [comment] 2020-09-04 09:15
Thanks, we need to have a look. Also, feel free to submit a pull request if you've identified the cause.

**Comment by mp911de** [comment] 2020-09-28 09:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-09-28 09:59 UTC
Labels: status: waiting-for-feedback, type: bug
