### ISSUE TITLE
RedisCommandTimeoutException: Command timed out

### ISSUE THREAD

**Issue by ppj19891020** [lettuce-io/lettuce-core#1407] opened 2020-09-02 09:56 UTC
## Bug Report
version: 5.0.5.RELEASE

Problems in the test environment！！！！
note: No slow command!

```less
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: 2020-09-02 17:04:07.029 dxy-live-extensions [lettuce-epollEventLoop-5-1] ERROR c.d.redis.lock.RedisDistributedLock - set redis occured an exception:Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceScriptingCommands.convertLettuceAccessException(LettuceScriptingCommands.java:236)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceScriptingCommands.evalSha(LettuceScriptingCommands.java:195)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.DefaultedRedisConnection.evalSha(DefaultedRedisConnection.java:1240)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at java.lang.reflect.Method.invoke(Method.java:498)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.sun.proxy.$Proxy169.evalSha(Unknown Source)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.script.DefaultScriptExecutor.eval(DefaultScriptExecutor.java:77)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.script.DefaultScriptExecutor.lambda$execute$0(DefaultScriptExecutor.java:68)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.script.DefaultScriptExecutor.execute(DefaultScriptExecutor.java:58)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.script.DefaultScriptExecutor.execute(DefaultScriptExecutor.java:52)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:346)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.dxy.redis.lock.RedisDistributedLock.redisLock(RedisDistributedLock.java:121)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.dxy.redis.lock.RedisDistributedLock.doLock(RedisDistributedLock.java:92)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.dxy.redis.lock.AbstractDistributedLock.lock(AbstractDistributedLock.java:46)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.dxy.redis.util.RedisLockUtils.tryLock(RedisLockUtils.java:64)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.dxy.listener.AbstractMessageListener.tryLock(AbstractMessageListener.java:21)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at com.dxy.listener.LiveInfoChangeMessageListener.onMessage(LiveInfoChangeMessageListener.java:34)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceMessageListener.message(LettuceMessageListener.java:43)
Sep  2 17:04:07 live-uat dxy-live-extensions-uat[117]: #011at org.springframework.data.redis.connection.lettuce.LettuceMessageListener.message(LettuceMessageListener.java:29)
```

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
       
       StringBuilder lockStringBuilder = new StringBuilder();
        // 检查是否key已经被占用，如果没有则设置超时时间和唯一标识，初始化value=1
        lockStringBuilder.append("if (redis.call('exists', KEYS[1]) == 0) then ");
        lockStringBuilder.append("  redis.call('hset', KEYS[1], ARGV[2], 1); ");
        lockStringBuilder.append("  redis.call('pexpire', KEYS[1], ARGV[1]); ");
        lockStringBuilder.append("  return nil; ");
        lockStringBuilder.append("end; ");
        // 如果锁重入,需要判断锁的key field 都一直情况下 value 加一
        lockStringBuilder.append("if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then ");
        lockStringBuilder.append("  redis.call('hincrby', KEYS[1], ARGV[2], 1); ");
        //锁重入重新设置超时时间
        lockStringBuilder.append("  redis.call('pexpire', KEYS[1], ARGV[1]); ");
        lockStringBuilder.append("  return nil;");
        lockStringBuilder.append("end; ");
        // 返回剩余的过期时间
        lockStringBuilder.append("return redis.call('pttl', KEYS[1]);");

   @Override
    public boolean doReleaseLock(String key) {
        // 释放锁的时候，有可能因为持锁之后方法执行时间大于锁的有效期，此时有可能已经被另外一个线程持有锁，所以不能直接删除
        try {
            Map<String,String> flags = lockFlag.get();
            String flag = null;
            if(null == flags || null == flags.get(key)){
                LOGGER.error("该线程不是持有该key:{} 权限，非法解锁！",key);
                return false;
            }
            //flag为当前线程当前key
            flag = flags.get(key);
            RedisScript<Long> redisScript = new DefaultRedisScript<Long>(UNLOCK_LUA,Long.class);
            Long result = (Long)redisTemplate.execute(redisScript, Collections.singletonList(key),flag);
            boolean res = result != null && result > 0;
            LOGGER.debug("{} 解锁:{}",key,res);
            if(res){
                //解锁成功，清楚threadlocal
                flags.remove(key);
                if(flags.isEmpty()){
                    //只有当size为0的时候，才表示该线程已经全部解锁所有的key
                    lockFlag.remove();
                }
            }
            return res;
        } catch (Exception e) {
            LOGGER.error("release lock occured an exception:{}", e.getMessage());
        }
        return false;
    }
```

</details>

#### Environment

- Lettuce version(s): 5.0.5.RELEASE
- Redis version: 4.0.9

#### Possible Solution
Is there a problem with executing the lua script？

#### Additional context
 No slow command!

**Comment by mp911de** [comment] 2020-09-02 10:22
Please upgrade to Lettuce 5.3 to see whether the issue is solved in the newer version. Please attach a thread dump if the problem persists.

**Comment by ppj19891020** [comment] 2020-09-03 06:47
> Please upgrade to Lettuce 5.3 to see whether the issue is solved in the newer version. Please attach a thread dump if the problem persists.

use lettuce version:5.3.1.RELEASE，It's the same mistake

log：
```less
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:257)
	at org.springframework.data.redis.connection.lettuce.LettuceScriptingCommands.convertLettuceAccessException(LettuceScriptingCommands.java:236)
	at org.springframework.data.redis.connection.lettuce.LettuceScriptingCommands.evalSha(LettuceScriptingCommands.java:195)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.evalSha(DefaultedRedisConnection.java:1240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy142.evalSha(Unknown Source)
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.eval(DefaultScriptExecutor.java:77)
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.lambda$execute$0(DefaultScriptExecutor.java:68)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.execute(DefaultScriptExecutor.java:58)
	at org.springframework.data.redis.core.script.DefaultScriptExecutor.execute(DefaultScriptExecutor.java:52)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:346)
	at com.dxy.redis.lock.RedisDistributedLock.redisLock(RedisDistributedLock.java:121)
	at com.dxy.redis.lock.RedisDistributedLock.doLock(RedisDistributedLock.java:82)
	at com.dxy.redis.lock.AbstractDistributedLock.lock(AbstractDistributedLock.java:46)
	at com.dxy.redis.util.RedisLockUtils.tryLock(RedisLockUtils.java:64)
	at com.dxy.listener.AbstractMessageListener.tryLock(AbstractMessageListener.java:21)
	at com.dxy.listener.LiveInfoChangeMessageListener.onMessage(LiveInfoChangeMessageListener.java:34)
	at org.springframework.data.redis.connection.lettuce.LettuceMessageListener.message(LettuceMessageListener.java:43)
	at org.springframework.data.redis.connection.lettuce.LettuceMessageListener.message(LettuceMessageListener.java:29)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:185)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:174)
	at io.lettuce.core.pubsub.PubSubCommandHandler.doNotifyMessage(PubSubCommandHandler.java:214)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:120)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:551)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:396)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:189)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:263)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 5 second(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:120)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy140.evalsha(Unknown Source)
	at org.springframework.data.redis.connection.lettuce.LettuceScriptingCommands.evalSha(LettuceScriptingCommands.java:193)
	... 50 common frames omitted```

**Comment by jchambers** [comment] 2020-09-03 15:18
@ppj19891020 It sounds like you're running into the issue described in #1402.

**Comment by mp911de** [comment] 2020-09-03 15:38
Like @jchambers wrote, you're blocking the thread that calls the listener. By doing so, the EventLoop cannot progress and continue processing the remaining commands (sending/receiving). Note that the reference documentation has a FAQ entry for command timeouts that mentions explicitly to not block the eventloop: https://lettuce.io/core/release/reference/index.html#faq.timeout

Please let me know if we can close this ticket.

**Comment by ppj19891020** [comment] 2020-09-04 04:08
@mp911de，@jchambers  So, how to solve the blocking problem of congestion？
for example：blop、subscribe

**Comment by mp911de** [comment] 2020-09-04 08:33
Removing `synchronized` and `RedisLockUtils` from the calls would be a first good step. Alternatively, move your unit of work onto a different thread. That is, once your message listener gets called, you submit a `Runnable` to a thread pool (e.g. `ThreadPoolExecutor`).

**Closed by mp911de** 2020-09-04 08:33 UTC
Labels: status: waiting-for-feedback
