### ISSUE TITLE
IllegalReferenceCountException in CommandHandler

### ISSUE THREAD

**Issue by travispeloton** [lettuce-io/lettuce-core#2110] opened 2022-06-06 20:06 UTC
## Bug Report

Netty `IllegalReferenceCountException` in `CommandHandler`. Been running `6.1.8.RELEASE` since 4/19/22, and saw this today (once) for the first time.

```java
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
    at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
    at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
    at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:600)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run
```

#### Environment

- Lettuce version(s): `6.1.8.RELEASE`
- Redis version: AWS ElastiCache 6.x

**Comment by mp911de** [comment] 2022-06-13 06:31
Thanks for the report. We haven't seen such an issue for quite a long time. What codec are you using? Without a reproducer, there's likely no chance of diagnosing the cause.

**Comment by mp911de** [comment] 2022-11-22 10:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-11-22 10:40 UTC

**Comment by tishun** [comment] 2024-07-11 10:37
Seems to be the same as #2542
