### ISSUE TITLE
Lettuce constantly tries to reconnect on SB request thread when running in cluster mode

### ISSUE THREAD

**Issue by tmuplayer33** [lettuce-io/lettuce-core#2085] opened 2022-04-26 12:36 UTC
#### Current Behavior

I am trying to use redis as my cache backend in a SpringBoot 2.5.5 service. For operating the service in production it is a must that the service immediately falls back to processing the calls uncached if the redis cluster becomes unavailable.

This is working very fine when lettuce is configured to only connect to one redis node. When the redis backend becomes unavailable, all incoming calls are still being processed uncached without delay. As soon as the redis backend becomes available again, lettuce reconnects to it and all calls are served by the cache again. This was archieved by using the Spring `@Cacheable` annotation and customizing the lettuce configuration:

<details>
<summary>Lettuce Configuration</summary>

```java
    @Bean
    LettuceClientConfigurationBuilderCustomizer lettuceClientConfigurationBuilderCustomizer() {
        return clientConfigurationBuilder -> {
            clientConfigurationBuilder.clientOptions(ClientOptions.builder()
                    .disconnectedBehavior(ClientOptions.DisconnectedBehavior.REJECT_COMMANDS)
                    .build()
            );

            clientConfigurationBuilder.clientResources(ClientResources.builder()
                    .reconnectDelay(Delay.constant(Duration.ofSeconds(1)))
                    .build()
            );
        };
    }

```

</details>

However, if I configure lettuce to connect to multiple nodes by setting `spring.redis.cluster.nodes`, it always tries to reconnect to the nodes on the same thread as the SpringBoot request thread when trying to get/put the cache. This increases the call duration by 2x the connection timeout and thus making the service much slower than processing the call without using a cache.

I tried multiple configurations by setting `autoReconnect=false`, `cancelCommandsOnReconnectFailure=true`, `suspendReconnectOnProtocolFailure=true` without luck. I also set the `DisconnectedBehavior` to `REJECT_COMMANDS` in the `ClusterClientOptions`.

</details>

#### Log output

<details>
<summary>Log Output</summary>
Note: 
[InReq] is logged on an incoming call
[OutRes] is logged when the call was answered

Connection Timeout: 1s

```java
2022-04-26 14:05:44.998  INFO [comet-core-service,db0a08d5d6c2e353,db0a08d5d6c2e353] 24542 --- [nio-8080-exec-2] c.o.b.c.c.service.ContractServiceImpl    : [InReq]
2022-04-26 14:05:46.034  WARN [comet-core-service,,] 24542 --- [oEventLoop-6-12] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.124:6379]: connection timed out: /123.123.123.124:6379
2022-04-26 14:05:46.034  WARN [comet-core-service,,] 24542 --- [oEventLoop-6-11] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.123:6379]: connection timed out: /123.123.123.123:6379
2022-04-26 14:05:47.415  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-1] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.123:6379]: connection timed out: /123.123.123.123:6379
2022-04-26 14:05:47.415  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-2] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.124:6379]: connection timed out: /123.123.123.124:6379
2022-04-26 14:05:47.417  INFO [comet-core-service,db0a08d5d6c2e353,db0a08d5d6c2e353] 24542 --- [nio-8080-exec-2] c.o.b.c.c.service.ContractServiceImpl    : [OutRes]
2022-04-26 14:05:47.546  INFO [comet-core-service,235877d24cadd90b,235877d24cadd90b] 24542 --- [nio-8080-exec-4] c.o.b.c.c.service.ContractServiceImpl    : [InReq]
2022-04-26 14:05:48.582  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-4] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.124:6379]: connection timed out: /123.123.123.124:6379
2022-04-26 14:05:48.582  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-3] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.123:6379]: connection timed out: /123.123.123.123:6379
2022-04-26 14:05:49.945  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-5] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.123:6379]: connection timed out: /123.123.123.123:6379
2022-04-26 14:05:49.945  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-6] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.124:6379]: connection timed out: /123.123.123.124:6379
2022-04-26 14:05:49.946  INFO [comet-core-service,235877d24cadd90b,235877d24cadd90b] 24542 --- [nio-8080-exec-4] c.o.b.c.c.service.ContractServiceImpl    : [OutRes]
2022-04-26 14:05:50.075  INFO [comet-core-service,09f2f3d90cc5c3e4,09f2f3d90cc5c3e4] 24542 --- [nio-8080-exec-6] c.o.b.c.c.service.ContractServiceImpl    : [InReq]
2022-04-26 14:05:51.111  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-7] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.123:6379]: connection timed out: /123.123.123.123:6379
2022-04-26 14:05:51.112  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-8] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.124:6379]: connection timed out: /123.123.123.124:6379
2022-04-26 14:05:52.479  WARN [comet-core-service,,] 24542 --- [ioEventLoop-6-9] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.123:6379]: connection timed out: /123.123.123.123:6379
2022-04-26 14:05:52.479  WARN [comet-core-service,,] 24542 --- [oEventLoop-6-10] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [123.123.123.124:6379]: connection timed out: /123.123.123.124:6379
2022-04-26 14:05:52.480  INFO [comet-core-service,09f2f3d90cc5c3e4,09f2f3d90cc5c3e4] 24542 --- [nio-8080-exec-6] c.o.b.c.c.service.ContractServiceImpl    : [OutRes]
```

</details>

#### Expected behavior/code

Like in single node configuration: 
Lettuce tries to connect to the cluster nodes on thread that does not impact the duration of the calls. If the nodes are unavailable, all cache commands are rejected. If the redis nodes become available, use them for caching.

#### Environment

- Lettuce version: 6.1.5-RELEASE
- Redis version: 6.2.6

**Comment by mp911de** [comment] 2022-04-26 13:30
Thanks for reaching out. In single-host mode, we have a single command dispatcher that uses the configured endpoint and if the endpoint is not connected, we can easily reject commands.

In cluster mode, we asynchronously try to establish a connection, and once the connection was established successfully, we write out the command to the connection by using future chaining. 

Reconnect happens on I/O or worker threads. The blocking behavior you experience is caused by Lettuce waiting for command completion on the request thread.

In a cluster scenario we can have two basic states:

1. The node connection is not available because connections are created lazily
2. The node connection is not available because the connection was disconnected

In the first state, we want to create the connection and actually wait until the connection is there to send the Redis command. In the second state, we could want to reject the command immediately.

The log above doesn't show any reconnects. I assume we have the first case, that connections are created lazily to the cluster. We cannot know whether the node is disconnected because we never had a successful connection created to the target node. Therefore, `DisconnectedBehavior` isn't applicable.

One way around could be to establish connections to all nodes upon cluster connection startup but that would also allocate connections up front even if not all connections are required. 

I currently don't have a good idea how to address that issue. Pre-initialization could be a way out but it is costly.

**Comment by ExploreNcrack** [comment] 2022-05-04 00:55
Hi @mp911de  just another question, how can we force eager initialization or configure the cluster mode client to ensure Pre-initialization on Startup? Is there a way to do that if I am not using Spring framework? Thanks in advanced

**Comment by tmuplayer33** [comment] 2022-05-11 12:49
I managed circumvent this issue by re-implementing the `RedisCacheWriter` with `resilience4j` annotations like this:

Note: The actual logic is copied from the `org.springframework.data.redis.cache.DefaultRedisCacheWriter`.
```java
@Slf4j
@Component
@RequiredArgsConstructor
public class ResilientRedisCacheWriter implements RedisCacheWriter {

    public static final String BACKEND = "redisCache";
    private final RedisConnectionFactory connectionFactory;


    @Override
    @CircuitBreaker(name = BACKEND)
    public void put(String name, byte[] key, byte[] value, Duration ttl) {
        execute(name, connection -> {

            if (shouldExpireWithin(ttl)) {
                connection.set(key, value, Expiration.from(ttl.toMillis(), TimeUnit.MILLISECONDS), RedisStringCommands.SetOption.upsert());
            } else {
                connection.set(key, value);
            }

            return "OK";
        });
    }

    // other methods omitted

}
```

And then telling spring to use my own implementation:

```java
@Bean
public RedisCacheManagerBuilderCustomizer redisCacheManagerBuilderCustomizer(ResilientRedisCacheWriter resilientRedisCacheWriter) {
    return (builder) -> {
        builder.cacheWriter(resilientRedisCacheWriter);
    };
}
```

I hope this helps someone.

**Comment by mp911de** [comment] 2022-11-22 10:39
Closing this one as the connects happen on I/O threads, not the ones used for requests.

**Closed by mp911de** 2022-11-22 10:39 UTC
