### ISSUE TITLE
Memory leak in connection?

### ISSUE THREAD

**Issue by wangjia184** [lettuce-io/lettuce-core#515] opened 2017-04-20 08:24 UTC
I am using Lettuce  4.3.1.Final + Netty 4.1.9.Final and see the following error.

> ERROR 2017-04-20 08:10:45.153 [main] ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
> Recent access records: 0
> Created at:
>         io.netty.util.ResourceLeakDetector.track(ResourceLeakDetector.java:237)
>         io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:327)
>         io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
>         io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
>         com.lambdaworks.redis.protocol.CommandHandler.<init>(CommandHandler.java:76)
>         com.lambdaworks.redis.RedisClient.connectStandalone(RedisClient.java:450)
>         com.lambdaworks.redis.RedisClient.connect(RedisClient.java:362)

It seems the leak is from the `connect `method.

**Comment by mp911de** [comment] 2017-04-20 10:00
The allocated buffer is released with `CommandHandler.close()`. Looks like your connection was not closed properly. Please provide a minimal, reproducible test case if the issue persists.

**Comment by mp911de** [comment] 2017-04-25 15:46
Any update on this issue?

**Comment by mp911de** [comment] 2017-06-07 13:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2017-06-07 13:58 UTC
Labels: feedback requested

**Comment by laxmi-narayan-nitdgp** [comment] 2018-10-05 12:07
Hi @mp911de 

I am also getting same issue , while trying to do pipeline from code. Example code is taken from 
https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing

io.lettuce.core.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit) 
2018-10-05 17:32:39 ERROR ResourceLeakDetector:311 - LEAK: HashedWheelTimer.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:

**Comment by laxmi-narayan-nitdgp** [comment] 2018-10-05 12:52
not an issue , connection was not closed properly.
