### ISSUE TITLE
redis key occasionally set fail

### ISSUE THREAD

**Issue by linchuyao** [lettuce-io/lettuce-core#1022] opened 2019-04-24 05:23 UTC

**Comment by linchuyao** [comment] 2019-04-24 05:49
![image](https://user-images.githubusercontent.com/32710423/56635334-ce5ff200-6697-11e9-9bd0-5a2b177d7f7f.png)

**Comment by mp911de** [comment] 2019-04-24 05:53
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by linchuyao** [comment] 2019-04-24 05:53
![image](https://user-images.githubusercontent.com/32710423/56635473-57772900-6698-11e9-86a7-f92b28ac8b9c.png)

**Comment by mp911de** [comment] 2019-04-24 06:07
Sorry, a screenshot of your code isn’t helpful. Please describe what you’re attempting to achieve, what happens and what you expect to happen. On failures, please attach a stack trace.

**Comment by mp911de** [comment] 2019-05-19 12:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-05-19 12:31 UTC
Labels: status: waiting-for-feedback, type: bug
