### ISSUE TITLE
Does  async() expire work?

### ISSUE THREAD

**Issue by jemiller2019** [lettuce-io/lettuce-core#1079] opened 2019-07-12 00:55 UTC
## Bug Report

I can successfully create a key but after also setting expiration I get after TTLing a return of -1 which I think indicates that the key has no expiration time.

<details>
<summary>Stack trace</summary>

```java
// your stack trace here;
```

</details>

#### Input Code

try {
     getRedisConnection().async().expire(getRedisKey(cluster), getCacheExpiry());
} catch (Exception e) {
   logger.error("Redis expire error: "+e.getMessage());
}
//(Note that getRedisKey uses a string argument to derive the key and getCacheExpiry() returns a long. //There is no error from the call.)
I get after TTLing a return of -1 which I think indicates that the key has no expiration time.
<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]

**Comment by mp911de** [comment] 2019-07-12 06:50
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by jemiller2019** [comment] 2019-07-12 14:32
I am simply asking if the API works for setting expiration for a key. I suspect I might be trying to set a timeout in a slave node -- if that does not work, is there a status returned indicating that?

**Comment by mp911de** [comment] 2019-07-12 14:40
Any reason it should not work?
Expire is considered a write command so with Redis Cluster, it's routed to the master node serving the particular key.

**Comment by jemiller2019** [comment] 2019-07-12 14:49
should i connect to the master specifically? i am given a choice of 3 nodes
(I read this from a JSON array) and am trying to choose one at random. I
was thinking that when i write to a slave, it fails and that I should only
be reading from slaves (or the master) but writing exclusively to the
master, including setting expiration.

this is legacy code and i am not sure how things are configured; i only
realized there were slave and master nodes when i tried using redis-api and
it did not allow me to set expiration on a read-only node.

i sure appreciate the help of the author of the code and apologize for not
providing more detail at first but i am extremely new to Redis.

**Comment by mp911de** [comment] 2019-07-12 14:56
When using Redis Cluster, then use any of the nodes. `RedisClusterClient` obtains its topology and routing information from the cluster itself.

When using just replication, then please rather use the [`MasterSlave` API](https://github.com/lettuce-io/lettuce-core/wiki/Master-Replica).

No need to worry. It's just questions that "Does X work?" are kind of silly because we're usually shipping only features that are known to work. So any more detail that helps diagnose the issue is appreciated.

**Comment by jemiller2019** [comment] 2019-07-16 22:19
Thanks for your help. I think the problem simply was setting the expiration
before setting key value. Fairly dumb of me.

**Comment by mp911de** [comment] 2019-07-17 06:37
Thanks for coming back. Closing this one.

**Closed by mp911de** 2019-07-17 06:37 UTC
Labels: status: invalid
