### ISSUE TITLE
Keep reconnecting when put large data onto redis

### ISSUE THREAD

**Issue by 1zg12** [lettuce-io/lettuce-core#2093] opened 2022-05-12 09:11 UTC
#### Current Behavior

When send large data onto redis through lettuce, it would fall into a infinite loop of keep reconnecting.

After switching from lettuce to jedis, which exposed the real issue, where redis actually send back a response of 
`error: invalid bulk length`

which lettuce however responded with a infinite loop of checking and reconnecting the netty `inactivechannel.`

<details>
<summary>Stack trace</summary>

there is no logs really, but the infinite messages from ConnectionWatchDog
```
https://github.com/lettuce-io/lettuce-core/blob/7be77cb8298b456cb68754f71c5eb3fed412c0f9/src/main/java/io/lettuce/core/protocol/ConnectionWatchdog.java#L244
```

looking at the stacks, its keep calling the `channelInActive` method on netty
```
https://github.com/netty/netty/blob/6ceca6342ddb87d32129412e35376cc70cf9c818/transport/src/main/java/io/netty/channel/ChannelInboundHandlerAdapter.java#L80
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

I am using Spring Cache as below, 
```
@Cachable(..)
public LargeData loadData(){
   ...
  return theLargeData;
}
```
but a simple call like this should result in the same situation
```
syncCommands.set("key", largeDateHere);
```

</details>

#### Environment

- Lettuce version(s): 6.1.8.RELEASE
- Redis version: 6.2.6

**Comment by mp911de** [comment] 2022-07-01 12:11
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2022-07-11 06:56
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2022-07-11 06:56 UTC
Labels: status: waiting-for-feedback
