### ISSUE TITLE
Redis command timeouts

### ISSUE THREAD

**Issue by shivabhalla** [lettuce-io/lettuce-core#784] opened 2018-05-28 19:00 UTC
Hi,

We are currently using Lettuce 4.3.0.Final version (also tried 4.4.2), facing a lot of RedisCommandTimeoutExceptions.

`com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:113)
	com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:92)
	com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63)
	com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	com.sun.proxy.$Proxy31.keys(Unknown Source)`

Our use case is, we hit several KEYS prefix*  command (also tried using SCAN instead but didn't help) which fetches a list of keys (hashes in our case) for which we one by one fetch values (using hgetall), and this is run in a loop, at some point of time in the loop this exception occurs.
We have set commandTimeout value pretty high, exception is thrown even before that.

Regards,
Shiva Bhalla

**Comment by mp911de** [comment] 2018-05-29 09:35
Can you provide a reproducible sample? Having the log or at least knowing what happens around the timeout is extremely helpful. Getting timeouts is something that can happen depending on a lot of factors (Redis load, disconnects, timeout settings).

**Comment by shivabhalla** [comment] 2018-05-29 09:49
Redis client/connection - 
```
CommandLatencyCollectorOptions options = DefaultCommandLatencyCollectorOptions.create();
    ClientResources resources = DefaultClientResources
      .builder()
      .commandLatencyCollectorOptions(options)
      .commandLatencyCollector(new CodehaleMetricCollector(options, metricManager))
      .commandLatencyPublisherOptions(DefaultEventPublisherOptions.create())
      .build();
    redisClient = RedisClient.create(resources);
  StatefulRedisMasterSlaveConnection<String, String> connection = MasterSlave.connect(
        redisClient,
        new Utf8StringCodec(),
        RedisURI.create("some redis url"));
      connection.setReadFrom(ReadFrom.MASTER_PREFERRED);
```


Part of code where I am facing this issue ->


```
redisCommand = connection.sync();
redisCommand.setTimeout(60, TimeUnit.SECONDS);
for (String hour : hourSet) {
      String timeStamp = hour;
      List<String> keyList = redisCommand.keys(timeStamp + '*');

      for (String key : keyList) {
        Map<String, String> mp = redisCommand.hgetall(key);
        faultyList.put(key, mp);
      }
}
```


I am sending you redis debug logs on mail.

**Comment by alx696** [comment] 2018-09-06 04:55
**io.lettuce:lettuce-core:5.0.5.RELEASE**

I have the same problem: `io.lettuce.core.RedisCommandTimeoutException: Command timed out`
```
  class SubscribeRunnable implements Runnable {

    StreamObserver<DetectionPointProto.SubscribeResponse> responseObserver;
    boolean loop = true;

    SubscribeRunnable(StreamObserver<DetectionPointProto.SubscribeResponse> responseObserver) {
      this.responseObserver = responseObserver;
    }

    @Override
    public void run() {
      try (
          StatefulRedisConnection<String, String> redisConnection = Redis.getInstance().connect();
          StatefulRedisPubSubConnection<String, String> pubSubConnection = Redis.getInstance().connectPubSub()
      ) {
        RedisCommands<String, String> commands = redisConnection.sync();
        RedisPubSubCommands<String, String> pubSubCommands = pubSubConnection.sync();

        pubSubConnection.addListener(new RedisPubSubListener<String, String>() {
          @Override
          public void message(String channel, String message) {
            L.debug("收到:{},{}", channel, message);

            Map<String, String> dataMap = commands.hgetall(message + "-data");

            try {
              responseObserver.onNext(
                  DetectionPointProto.SubscribeResponse.newBuilder()
                      .setChannel(channel)
                      .setId(message)
                      .setDataJson(
                          Json.toJson(dataMap)
                      )
                      .build()
              );
            } catch (Exception e) {
              loop = false;
            }
          }

          @Override
          public void message(String pattern, String channel, String message) {
          }

          @Override
          public void subscribed(String channel, long count) {
            L.debug("进行订阅:{}?{}", channel, count);
          }

          @Override
          public void psubscribed(String pattern, long count) {
          }

          @Override
          public void unsubscribed(String channel, long count) {
            L.debug("取消订阅:{}?{}", channel, count);
          }

          @Override
          public void punsubscribed(String pattern, long count) {
          }
        });

        pubSubCommands.subscribe(
            constant.Redis.CHANNEL_DETECTION_POINT,
            constant.Redis.CHANNEL_DETECTION_POINT_ASSET
        );

        while (loop) {
          Thread.sleep(3000);
        }

        L.debug("订阅实时数据客户断开");
      } catch (Exception e) {
        responseObserver.onError(
            Status.INTERNAL.asRuntimeException()
        );
        L.catching(e);
      }
    }
  }
```
### Problem Log:
```
收到:detection_point,110
12:44:25.814 DEBUG [lettuce-epollEventLoop-4-1] RedisChannelHandler io.lettuce.core.RedisChannelHandler.dispatch 
dispatching command AsyncCommand [type=HGETALL, output=MapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
12:44:25.814 DEBUG [lettuce-epollEventLoop-4-1] DefaultEndpoint DefaultEndpoint.channelWriteAndFlush 
[channel=0x8dea52f0, /192.168.1.248:56532 -> np.lilu.red/27.17.7.86:50120, epid=0xbc] write() writeAndFlush command AsyncCommand [type=HGETALL, output=MapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
12:44:25.814 DEBUG [lettuce-epollEventLoop-4-4] CommandHandler CommandHandler.write 
[channel=0x8dea52f0, /192.168.1.248:56532 -> np.lilu.red/27.17.7.86:50120, chid=0xbc] write(ctx, AsyncCommand [type=HGETALL, output=MapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
12:44:25.814 DEBUG [lettuce-epollEventLoop-4-1] DefaultEndpoint DefaultEndpoint.write 
[channel=0x8dea52f0, /192.168.1.248:56532 -> np.lilu.red/27.17.7.86:50120, epid=0xbc] write() done
12:44:25.815 DEBUG [lettuce-epollEventLoop-4-4] CommandEncoder CommandEncoder.encode 
[channel=0x8dea52f0, /192.168.1.248:56532 -> np.lilu.red/27.17.7.86:50120] writing command AsyncCommand [type=HGETALL, output=MapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
12:44:25.815 DEBUG [lettuce-epollEventLoop-4-4] CommandHandler CommandHandler.channelRead 
[channel=0x8dea52f0, /192.168.1.248:56532 -> np.lilu.red/27.17.7.86:50120, chid=0xbc] Received: 348 bytes, 1 commands in the stack
12:44:25.815 DEBUG [lettuce-epollEventLoop-4-4] CommandHandler CommandHandler.decode 
[channel=0x8dea52f0, /192.168.1.248:56532 -> np.lilu.red/27.17.7.86:50120, chid=0xbc] Stack contains: 1 commands
12:44:25.816 DEBUG [lettuce-epollEventLoop-4-4] RedisStateMachine RedisStateMachine.decode 
Decode AsyncCommand [type=HGETALL, output=MapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
12:44:25.816 DEBUG [lettuce-epollEventLoop-4-4] RedisStateMachine RedisStateMachine.decode 
Decoded AsyncCommand [type=HGETALL, output=MapOutput [output={ts=1536209065774, value=27.449464797973633, text=, alarm_level=-1, fault_status=-1, run_status=-1, special_status=, change=-1.8791866302490234, max=29.999195098876953, min=25.004179000854492, count=2025, sum=55590.515209198}, error='null'], commandType=io.lettuce.core.protocol.Command], empty stack: true
12:44:25.816 DEBUG [grpc-default-worker-ELG-3-6] NettyServerHandler io.netty.util.internal.logging.Log4J2Logger.log 
[id: 0x5ef95834, L:/127.0.0.1:6000 - R:/127.0.0.1:41934] OUTBOUND DATA: streamId=3 padding=0 endStream=false length=292 bytes=000000011f0a0f646574656374696f6e5f706f696e7412033131301a86027b227473223a2231353336323039303635373734222c2276616c7565223a2232372e...
12:44:26.049 WARN  [lettuce-epollEventLoop-4-3] CommandHandler logging.Log4J2Logger.log 
[channel=0x794e68f9, /192.168.1.248:56402 -> np.lilu.red/27.17.7.86:50120, chid=0xbb] Unexpected exception during request: io.lettuce.core.RedisCommandTimeoutException: Command timed out
io.lettuce.core.RedisCommandTimeoutException: Command timed out
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114)
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:62)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy19.hgetall(Unknown Source)
	at service.infrastructure.DetectionPoint$SubscribeRunnable$1.message(DetectionPoint.java:276)
	at service.infrastructure.DetectionPoint$SubscribeRunnable$1.message(DetectionPoint.java:271)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyListeners(PubSubEndpoint.java:93)
	at io.lettuce.core.pubsub.PubSubEndpoint.notifyMessage(PubSubEndpoint.java:85)
	at io.lettuce.core.pubsub.PubSubCommandHandler.decode(PubSubCommandHandler.java:104)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:508)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:410)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
12:44:26.050 DEBUG [lettuce-epollEventLoop-4-3] CommandHandler CommandHandler.channelRead 
[channel=0x794e68f9, /192.168.1.248:56402 -> np.lilu.red/27.17.7.86:50120, chid=0xbb] Received: 464 bytes, 0 commands in the stack
12:44:26.051 DEBUG [lettuce-epollEventLoop-4-3] RedisStateMachine RedisStateMachine.decode 
Decode null
12:44:26.051 DEBUG [lettuce-epollEventLoop-4-3] RedisStateMachine RedisStateMachine.decode 
Decoded null, empty stack: true
```

**Comment by alx696** [comment] 2018-09-06 05:10
Call `hgetall` fast, the problem show. And it will block all RedisCommands.

After restart the client, the problem gone. So the redis server is ok, the problem Caused by lettuce.

**Comment by mp911de** [comment] 2018-09-06 06:53
@alx696 thanks a lot for all the details, that's exactly what's needed to diagnose the problem. Looking at the log and the code, you're calling blocking methods on the netty event loop. In your first message, you posted code that calls `hgetall(…)` inside of `RedisPubSubListener`. The listener callback is invoked on a netty event loop thread which gets blocked by invoking `hgetall(…)`. Please either move that call to a different thread or use the asynchronous API which is safe to use.

**Comment by alx696** [comment] 2018-09-07 15:12
I have change the method, the timed out problem gone...

Move the RedisPubSubListener to the Constructor Method:
```
  private static final List<StreamObserver<DetectionPointProto.SubscribeResponse>> REAL_DATA_CALLBACK_LIST = new ArrayList<>();

  public DetectionPoint() {
      //订阅实时数据
      RedisCommands<String, String> redisCommands = Redis.getInstance().connect().sync();
      StatefulRedisPubSubConnection<String, String> pubSubConnection = Redis.getInstance().connectPubSub();
      pubSubConnection.addListener(new RedisPubSubListener<String, String>() {
        @Override
        public void message(String channel, String message) {
          Map<String, String> dataMap = redisCommands.hgetall(message + "-data");
          L.debug("实时数据:[{}:{}] {}", channel, message, dataMap);

          //进行回调
          DetectionPointProto.SubscribeResponse subscribeResponse = DetectionPointProto.SubscribeResponse.newBuilder()
              .setChannel(channel)
              .setId(message)
              .setDataJson(
                  Json.toJson(dataMap)
              )
              .build();
          Iterator<StreamObserver<DetectionPointProto.SubscribeResponse>> iterator = REAL_DATA_CALLBACK_LIST.iterator();
          while (iterator.hasNext()) {
            try {
              iterator.next()
                  .onNext(subscribeResponse);
            } catch (Exception e) {
              L.debug("客户断开");
              iterator.remove();
            }
          }
        }
...
      });
      RedisPubSubCommands<String, String> pubSubCommands = pubSubConnection.sync();
      pubSubCommands.subscribe(
          constant.Redis.CHANNEL_DETECTION_POINT,
          constant.Redis.CHANNEL_DETECTION_POINT_ASSET
      );
  }

  @Override
  public void subscribeRealData(DetectionPointProto.Empty request, StreamObserver<DetectionPointProto.SubscribeResponse> responseObserver) {
    try {
      L.info("订阅实时数据");

      REAL_DATA_CALLBACK_LIST.add(responseObserver);
    } catch (Exception e) {
      responseObserver.onError(
          Status.INTERNAL.asRuntimeException()
      );
      L.catching(e);
    }
  }
```
So do not need to create RedisPubSubListener every call.

I will try asynchronous API to `hgetall`. Thanks for you suggest^^

**Comment by mp911de** [comment] 2018-09-10 07:50
One more thing to consider in your code is error handling. The publisher returned by `hgetall` should have at least a `doOnError(…)` callback for generic error handling.

Closing this ticket as it was solved.

**Closed by mp911de** 2018-09-10 07:50 UTC
Labels: status: cannot-reproduce, status: waiting-for-feedback
