### ISSUE TITLE
Reopen #2111 there was a misunderstanding

### ISSUE THREAD

**Issue by Emibergo02** [lettuce-io/lettuce-core#2258] opened 2022-11-22 00:00 UTC
the issue #2111 was closed but @mp911de made a mistake.
the package io.lettuce.core is relocated. the issue remains valid

**Comment by mp911de** [comment] 2022-11-22 08:03
With respect to your knowledge, care to elaborate on what the problem is and what is causing it?

**Comment by Emibergo02** [comment] 2022-11-22 16:58
https://github.com/lettuce-io/lettuce-core/pull/2260

**Comment by mp911de** [comment] 2022-11-23 07:26
Fixed via #2260

**Closed by mp911de** 2022-11-23 07:26 UTC
Labels: type: bug
