### ISSUE TITLE
Lettuce suppressing connection info 

### ISSUE THREAD

**Issue by developerreactive** [lettuce-io/lettuce-core#754] opened 2018-04-04 18:45 UTC
While coding for Redis failure scenario, changed Redis Endpoint to non existing url. Expectation was for spring-data-redis to throw a connection exception, but no exception was thrown and Flux kept on waiting. By enabling DEBUG logs on framework, noticed there is a connection error being logged. Looks like error is suppressed in the framework. Here is the logs:

```
03-29-2018 IST 22:47:28.792 [elastic-2] DEBUG io.lettuce.core.RedisClient - Resolved SocketAddress _xxx-sampleapp.xxx.cache.amazonaws.com:6379 using RedisURI [host='_xxx-sampleapp.xxx.cache.amazonaws.com', port=6379]
03-29-2018 IST 22:47:28.792 [elastic-2] DEBUG io.lettuce.core.RedisClient - Connecting to Redis at _xxx-sampleapp.xxx.cache.amazonaws.com:6379
03-29-2018 IST 22:47:29.040 [lettuce-nioEventLoop-6-1] DEBUG io.lettuce.core.RedisClient - Connecting to Redis at_xxx-sampleapp.xxx.cache.amazonaws.com:6379: {}
java.net.UnknownHostException: _xxx-sampleapp.xxx.cache.amazonaws.com
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

We should get a connection exception and onErrorResume subscriber should be called. 

Here is the code snippet which should catch the error.

```java
return hashOps.values(KEY)
.flatMap(map -> {
Map result = (Map) map;
String productId = (String) result.get("devprod_id");
LOG.info("product id: {}", productId);
Map productMap = new HashMap();
productMap.put(productId, result);
return Flux.just(productMap);
})
.switchIfEmpty(LoadSampleData.loadSampleDataFromFile("From switchIfEmpty"))
.onErrorResume(e -> {
LOG.info("-> inside onErrorResumeWith()");
return LoadSampleData.loadSampleDataFromFile("From onErrorResume");
})
//Redis Connection error is not thrown. Flux is holding on with no response. Timesout the request after 20 secs.
.timeout(Duration.ofMillis(20000), LoadSampleData.loadSampleDataFromFile("From timeout"));
```

**Comment by mp911de** [comment] 2018-04-05 06:59
Could you elaborate what you mean with 

> changed Redis Endpoint to non existing url

When/how did you change the url? Do you have some code to reproduce the issue and version numbers of Spring Data Redis/Lettuce?

**Comment by mp911de** [comment] 2018-04-17 08:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2018-04-17 08:31 UTC
Labels: feedback requested

**Comment by hiteshshahjee** [comment] 2018-04-17 11:54
We had this issue while using spring boot version 2.0.0.RELEASE.
We upgraded to 2.0.1.RELEASE version and the issue is fixed.

Issue occurred while testing for ReactiveHashOperation values method using and invalid Redis endpoint. Expectation was to get an connection error. It didn't happen with 2.0.0.RELEASE, after upgrading to 2.0.1.RELEASE, we get proper redis onconnection error.
