### ISSUE TITLE
NullPointerException  some times

### ISSUE THREAD

**Issue by saturnLong** [lettuce-io/lettuce-core#1331] opened 2020-07-04 06:54 UTC
hi,
sentinel mode,  use pipelining.  some times .occur  NullPointerException.  version at : 5.1.7.RELEASE
exception1:
java.lang.NullPointerException: null
        at io.lettuce.core.internal.AsyncConnectionProvider$Sync.doWithConnection(AsyncConnectionProvider.java:266)
        at io.lettuce.core.internal.AsyncConnectionProvider.lambda$forEach$3(AsyncConnectionProvider.java:190)
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
        at io.lettuce.core.internal.AsyncConnectionProvider.forEach(AsyncConnectionProvider.java:190)
        at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.flushCommands(MasterSlaveConnectionProvider.java:240)
        at io.lettuce.core.masterslave.MasterSlaveChannelWriter.flushCommands(MasterSlaveChannelWriter.java:239)
        at io.lettuce.core.RedisChannelHandler.flushCommands(RedisChannelHandler.java:324)

exception2:
java.lang.NullPointerException: null
        at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.lambda$setAutoFlushCommands$0(MasterSlaveConnectionProvider.java:253)
        at io.lettuce.core.internal.AsyncConnectionProvider$Sync.doWithConnection(AsyncConnectionProvider.java:266)
        at io.lettuce.core.internal.AsyncConnectionProvider.lambda$forEach$3(AsyncConnectionProvider.java:190)
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
        at io.lettuce.core.internal.AsyncConnectionProvider.forEach(AsyncConnectionProvider.java:190)
        at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.setAutoFlushCommands(MasterSlaveConnectionProvider.java:253)
        at io.lettuce.core.masterslave.MasterSlaveChannelWriter.setAutoFlushCommands(MasterSlaveChannelWriter.java:234)
        at io.lettuce.core.RedisChannelHandler.setAutoFlushCommands(RedisChannelHandler.java:320)

**Comment by mp911de** [comment] 2020-07-09 09:51
Can you upgrade to 5.3.1 and retest? This is a duplicate of #1301.

**Closed by mp911de** 2020-07-09 09:51 UTC
Labels: status: duplicate, type: bug

**Comment by saturnLong** [comment] 2020-07-14 05:44
ok，thank you。 i try   upgrade to a new version

**Comment by webbershare** [comment] 2020-11-06 05:18
My version is 5.3.1.RELEASE.
But I still occur the exception as:
`java.lang.NullPointerException: null
        at io.lettuce.core.internal.AsyncConnectionProvider$Sync.doWithConnection(AsyncConnectionProvider.java:273)
        at io.lettuce.core.internal.AsyncConnectionProvider.lambda$forEach$3(AsyncConnectionProvider.java:195)
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
        at io.lettuce.core.internal.AsyncConnectionProvider.forEach(AsyncConnectionProvider.java:193)
        at io.lettuce.core.masterslave.MasterSlaveConnectionProvider.flushCommands(MasterSlaveConnectionProvider.java:245)
        at io.lettuce.core.masterslave.MasterSlaveChannelWriter.flushCommands(MasterSlaveChannelWriter.java:239)
        at io.lettuce.core.RedisChannelHandler.flushCommands(RedisChannelHandler.java:326)
        at com.yy.boot.component.redis.dispatch.SyncPipelineExecuter.exe(SyncPipelineExecuter.java:42)
        at com.yy.boot.component.redis.ApiInvocationHandler.invoke(ApiInvocationHandler.java:75)
        at com.sun.proxy.$Proxy94.pipeline4List(Unknown Source)`

**Comment by michaelassraf** [comment] 2022-06-17 18:40
I'm getting this at 6.18
