### ISSUE TITLE
Large number of AsyncCommands in heap dump 

### ISSUE THREAD

**Issue by pallavsh** [lettuce-io/lettuce-core#484] opened 2017-03-15 23:46 UTC
Observing large number of AsyncCommands, Commands, CommandArgs in heap dump.  Is there way to clean references of AsyncCommands after performing set OR get operation to redis server .  Here is application usage of Lettuce - 

lettuce version (4.3.2-SNAPSHOT) + TwemProxy + 10 Elasticache (1 Master 1 Slave ) cluster

1.  Single Redis Connection is been made with TwemProxy in constructor of the class

                ClientResources res = new DefaultClientResources.Builder()
                        .ioThreadPoolSize(8)
                        .computationThreadPoolSize(8)
                        .reconnectDelay(Delay.constant(5000, TimeUnit.MILLISECONDS))
                        .build();
                redisClient = RedisClient.create(res, RedisURI.Builder.redis(redisNodeBean.getServerLoc(), redisNodeBean.getServerPort()).build());
                redisClient.setDefaultTimeout(300, TimeUnit.MILLISECONDS);
                SocketOptions sock =  SocketOptions.builder().connectTimeout(300, TimeUnit.MILLISECONDS)
                        .keepAlive(true)
                        .tcpNoDelay(true).build();
                
                redisClient.setOptions(new ClientOptions.Builder()
                        .autoReconnect(true)
                        .disconnectedBehavior(ClientOptions.DisconnectedBehavior.ACCEPT_COMMANDS.DEFAULT)
                        .suspendReconnectOnProtocolFailure(false)
                        .socketOptions(sock)
                        .build()); 
                  this.stringConnection = redisClient.connect();

2. then use connection to get "async commands" to perform get & set data for different Web request landed on tomcat as below - 
 
                 private String redisGet(String mappedKey){
                     RedisAsyncCommands<String, String> aSyncCommands = stringConnection.async();
                      RedisFuture<String> future = aSyncommands.get(mappedKey);
                       return future.get(nodeBean.getTimeout(), TimeUnit.MILLISECONDS);
                 }

OR Set operation :
                      commands = stringConnection.async();
                      commands.set(mappedKey, final value);

3. Connection is being closed during the Web application shutdown();

              @PreDestroy()
              public void redisCleanUps() {        
              try {
                    if (stringConnection != null) {
                         stringConnection.close();
                     }
               } catch (Exception ex) {
                     logger.error(" async connecetion couldn't close ", ex);
              }
             try {
                   if (simpleClient != null) {
                       simpleClient.shutdown();
                  }
              } catch (Exception ex) {
                  logger.error(" simpleClient connecetion shutdown failed", ex);
              }
              }

Can you suggest what/which-all steps should be changed so we can clean up AsyncCommands references as soon as set/get operations are done ? So our memory usage can be improved ..

Thx for your help !!

**Comment by mp911de** [comment] 2017-03-16 10:54
Lettuce uses `Command` and `AsyncCommand` instances for an event-driven approach of Redis interaction. `AsyncCommand` is a `CompletableFuture` that holds a reference to `Command`. If you release the future (exposed via `RedisFuture`), then these instances are garbage collected.

I tried to approach excessive object allocation with pooling but I wasn't able yet to find a way to use pooling and not break things.

You might want to check for the object roots and where they are held.

**Comment by pallavsh** [comment] 2017-03-17 01:56
Thanks Mark , we also thought the same but try confirming here as we couldn't find suitable Junit test or example for this .. 

Also we saw yesterday that during higher heap usage , CPU cycle spikes really high and lettuce starts throwing "java.util.concurrent.ExecutionException: java.lang.IllegalStateException" and after that response received from lettuce was out of order intermittently.  We faced out of order issue earlier so we upgraded the lettuce lib so this issue didn't happened for long time but sad to see this issue again while high heap usage & with CPU spikes .  We are using async get/set/expire operation as of now.  

This problem is very similar to these problem   - https://github.com/mp911de/lettuce/issues/202 OR https://github.com/mp911de/lettuce/issues/262 OR https://github.com/mp911de/lettuce/issues/253 .. 

 Should we enable  cancelCommandsOnReconnectFailure ? OR changing disconnectedBehavior can help in this case ?

**Comment by mp911de** [comment] 2017-03-24 20:57
It would be good seeing the trace of `IllegalStateException`. Limiting the queue size and setting `disconnectedBehavior` to reject are measures to protect your application. Do you get a lot of reconnects? It would be good having a snapshot of a failure situation (logs, thread dump, maybe even a heap dump) to investigate the cause.

**Comment by pallavsh** [comment] 2017-04-12 23:39
Thanks Mark for replying . We do get reconnect some time, some time it happens because twem-proxy dies or there could be actual network issue with AWS . Good thing is we haven't see this issue since we discussed  last time ... will change disconnectedBehavior and share more details if it happen again .  

I would like to confirm one more thing .  We have put reconnect delay as 5 second . I do see in the log that its trying to reconnect in every 5 seconds . Does it check if it has a healthy connection before establishing  a new connection ? or am I misreading the logs . thx .. 

[AT - 15:20:53 ]
================
2017-03-28 15:20:53,016 INFO  [lettuce-eventExecutorLoop-57-2] [] [] [] [] [lid=] [bid:] [ReconnectionHandler] - Reconnected to localhost/127.0.0.1:11212

[After 5 seconds AT - 15:20:58 ]
================================
2017-03-28 15:20:58,027 INFO  [lettuce-eventExecutorLoop-6-3] [] [] [] [] [lid=] [bid:] [ConnectionWatchdog] - Reconnecting, last destination was localhost/127.0.0.1:11212
2017-03-28 15:20:58,029 INFO  [lettuce-eventExecutorLoop-12-3] [] [] [] [] [lid=] [bid:] [ConnectionWatchdog] - Reconnecting, last destination was localhost/127.0.0.1:11213
2017-03-28 15:20:58,040 INFO  [lettuce-eventExecutorLoop-12-3] [] [] [] [] [lid=] [bid:] [ReconnectionHandler] - Reconnected to localhost/127.0.0.1:11213

**Comment by mp911de** [comment] 2017-04-13 06:38
It's always the same user-facing connection and the same `CommandHandler` that are used for reconnecting. `ConnectionWatchdog` uses a scheduler to schedule the next connection attempt, that's why you see `lettuce-eventExecutorLoop-12-…` in your logs. If the connection attempt was successful, then the connection is activated. If the connection attempt fails, a next attempt is scheduled.

Closing this issue because we can't really move forward and the actual cause for your issue is still unknown.

**Closed by mp911de** 2017-04-13 06:38 UTC
Labels: question

**Comment by laxmi-narayan-nitdgp** [comment] 2017-06-10 06:15
redisAsyncCommands close throws error . is it only once used , i tried reusing object but could not , and if i try to close , it says : already closed.
