### ISSUE TITLE
A lost data scenes confirmation

### ISSUE THREAD

**Issue by LittleJZ** [lettuce-io/lettuce-core#1945] opened 2021-12-24 10:33 UTC
hi, I've encountered the loss of subkey and subvalue when writing Map type data to redis using lettuce, and I'd like to confirm if this happens when I do the following

Firstly: I turned off the command auto flush
![image](https://user-images.githubusercontent.com/51402665/147343972-de133b67-1256-49e0-821e-4707e1a0c01c.png)

Secondly: I performed the operation of deleting the key first, and then inserting the data，The key is the same
![image](https://user-images.githubusercontent.com/51402665/147344197-cd7db041-3730-43e5-8992-feb581f139bb.png)

Finally: i flush commands
![image](https://user-images.githubusercontent.com/51402665/147344266-6edf7577-edaa-476d-8aa5-c346d38f0d01.png)

I use the async api for my del and hset operations
![image](https://user-images.githubusercontent.com/51402665/147344327-054be0ee-eb38-4c20-9698-ef559ca8d0bc.png)

I want to know if this operation will first hset several subkeys and subvalue, and then delete the data of this key, and finally hset several subkeys and subvalue?

Thank you for your Reply!

**Comment by LittleJZ** [comment] 2021-12-31 05:47
I found that this does happen by monitoring the execution commands of redis, is this a bug?

**Comment by mp911de** [comment] 2022-01-03 08:20
Duplicate of #1928.

`flushCommands` requires a lot of attention and pre-caution to avoid improper synchronization.

**Closed by mp911de** 2022-01-03 08:20 UTC
Labels: status: duplicate
