### ISSUE TITLE
Reactive increment blocking unexpectedly 

### ISSUE THREAD

**Issue by a-cordier** [lettuce-io/lettuce-core#1718] opened 2021-04-12 16:09 UTC
Hi 👋 

Don't know if that's a bug really or a misconfiguration on our side but we are experiencing behaviours that we cannot figure out when it come to network failure handling with redis

##  Context

```xml
<lettuce.version>6.1.0.RELEASE</lettuce.version>
```
  - We are using Redis as a backend to share our API gateway rate limit increments across several instances
  - We have a Couchbase / Memcached implementation beside Redis that works just as expected
  - Both implementation are based on Reactive APIs

We have a `LocalFirstRateLimitPolicy` that computes the increments in memory and asynchronously computes that same increment in the backend before merging it to the local store eg:
```java
RateLimitKey key = RateLimitKey.of(globalRateLimit);

Flux.fromIterable(backends) // backends is a singleton list containing only the redis impl. in that case
    .flatMap(backend -> backend.incrementCounter(key))
    .timeout(Duration.ofMillis(operationTimeoutMs))
    .onErrorReturn(0L)
    .take(1)
    .next()
    .subscribe(remoteCount -> {
        log.debug("remote value for {}: {}", key, remoteCount);
        this.localMap.merge(key.getId(), remoteCount, Math::max); // keep the biggest (and thus the latest) value
    });

return Mono.just(computeStatus(globalRateLimit, getLocalCount(key)));
```

The incrementCounter implementation being:

```java
return Mono.zip(
                redisCommands.incr(key.getId()), 
                setExpiry(key),
                (count, ok) -> count
            );
```

This operation is performed in a jetty filter before proxying the request to the upstream service (or sending back a 429 response if the rate limiting bucket is exhausted)

## Behaviour

The idea of the above is to fail fast on connection errors and return a pass through result on the increment with a value of 0.

With both auto reconnect enabled or disabled, shutting down the connection to the redis backend through a firewall leads to dramatical increases of the overall proxy latency that we do not expect to happen, eventually making client requests timeout.

## Here is what happens exactly during a load test

<img width="735" alt="Screenshot 2021-04-12 at 17 55 25" src="https://user-images.githubusercontent.com/3619261/114424926-dda81500-9bb8-11eb-8132-3cdd79fb597a.png">

This is the clientOptions we used when running this test 

```java
ClientOptions.builder()
            .autoReconnect(false)
            .publishOnScheduler(true)
            .disconnectedBehavior(REJECT_COMMANDS)
            .build();
```

We tried a bunch of combinations (the publishOnScheduler being our last attempt) but each one of them lead to network failures between the redis backend and our application having effects on request latencies

## What we do not understand

Given that the increment is performed asynchronously and that our service actually returns a locally computed value, we would expect disconnection to have no effect at all on the overall latency (that's actually what we are experiencing with our other implementation)

Did we miss anything / are we doing it wrong ?

Thank you 🙏

**Comment by mp911de** [comment] 2021-04-12 17:09
From the code above there's nothing that indicates a path that depends on the Redis client to be able to proceed. It looks as if congestion on the connection side/disconnect prevents reactive stages from progressing. If possible, add metering/logging to your reactive sequence to find out which stage suffers from the outage. 

Taking a thread dump to verify there's no blocked thread and potentially running a profiler to check thread load would be good first steps. Not that a single Redis connection can behave effectively as if your system was single-threaded as response signals are emitted on a single I/O thread.

**Comment by a-cordier** [comment] 2021-04-14 10:17
Hi, 

Here is a visual profile of the application when blocking the connexion abruptly during a load test

<img width="1395" alt="Screenshot 2021-04-14 at 11 20 20" src="https://user-images.githubusercontent.com/3619261/114689776-596ba400-9d16-11eb-8a71-dd6d7e45bdb4.png">

And a thread dump taken while used heap is about to hit the ceiling

[thread-dump-disconnected.txt](https://github.com/lettuce-io/lettuce-core/files/6310078/thread-dump-disconnected.txt)

Just in case a thread dump taken while everything is fine

[thread-dump-connected.txt](https://github.com/lettuce-io/lettuce-core/files/6310080/thread-dump-connected.txt)

During another profiling session we noticed a bunch of RedisException occurring

<img width="1167" alt="Screenshot 2021-04-13 at 17 02 06" src="https://user-images.githubusercontent.com/3619261/114694370-bf5a2a80-9d1a-11eb-8ed8-5553fcbdcd9b.png">

State of lettuce threads when things go wild

![image](https://user-images.githubusercontent.com/3619261/114694651-0d6f2e00-9d1b-11eb-9da2-c01194814621.png)

Most CPU consuming method

![image (1)](https://user-images.githubusercontent.com/3619261/114694954-5b843180-9d1b-11eb-916f-72cf5f13d2b0.png)

**Comment by mp911de** [comment] 2021-04-14 13:05
Thanks. The thread dump looks clean, with no locks. The growth in memory is likely caused by the backpressure as requests accumulate. Increased amount of `RedisException` creation is expected behavior, see: https://github.com/lettuce-io/lettuce-core/blob/cda3be6b9477da790365ad098c6e39c8687f5002/src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java#L281-L311

From a Lettuce perspective, all looks well.

**Comment by a-cordier** [comment] 2021-04-16 14:41
Hi, I found that setting the request queue size to a reasonably low limit (1024 in my test) instead of the default `Integer.MAX_VALUE` avoids the heap to grow like crazy.

Client Options
--
```java
return ClientOptions.builder()
            .autoReconnect(true)
            .requestQueueSize(1024)
            .publishOnScheduler(true)
            .cancelCommandsOnReconnectFailure(true)
            .suspendReconnectOnProtocolFailure(true)
            .disconnectedBehavior(REJECT_COMMANDS)
            .timeoutOptions(TimeoutOptions.enabled(Duration.ofSeconds(1)))
            .build();
```

From my interpretation of the documentation, using `REJECT_COMMANDS` as a disconnected behaviour should have short-circuit command queuing.

Was I assuming wrong ?

**Comment by mp911de** [comment] 2021-06-09 07:34
Reject commands should reject these right away without queueing these. Without any further details, it's hard to find out what actually happened.

In any case, things seem fine right now so closing this ticket.

**Closed by mp911de** 2021-06-09 07:34 UTC
Labels: status: waiting-for-feedback
