### ISSUE TITLE
StackOverflowError after DNS issues

### ISSUE THREAD

**Issue by jonathannaguin** [lettuce-io/lettuce-core#1739] opened 2021-05-06 12:55 UTC
## Bug Report

We are noticing some weird behaviour with Lettuce after DNS problems which provokes Lettuce to throw a StackOverflowError.

#### Current Behavior

Our DNS server has crashed a couple of times last week. 
When that happens our Java app fails to resolve any DNS hostname (for example, java.net.UnknownHostException: monitoring.us-east-1.amazonaws.com).
Eventually, the DNS comes back online and names can be resolved again, however Lettuce fails with the following exception:

<details>
<summary>Stack trace</summary>

```java
2021-05-05 14:03:47.795  WARN 1 --- [llEventLoop-5-1] io.lettuce.core.protocol.CommandHandler  : null Unexpected exception during request: java.lang.StackOverflowError
--
java.lang.StackOverflowError: null
at java.base/java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:73) ~[na:na]
at java.base/jdk.internal.reflect.GeneratedMethodAccessor511.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60) ~[logback-classic-1.2.3.jar!/:na]
at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72) ~[logback-classic-1.2.3.jar!/:na]
```

</details>

#### Input Code

https://github.com/spring-projects/spring-session/tree/main/spring-session-data-redis

#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version: 5.0.6
- Spring Session Data Redis: 2.3.2.RELEASE
- Spring Data Redis: 2.3.6.RELEASE

#### Possible Solution

None

#### Additional context

None

**Comment by mp911de** [comment] 2021-05-06 13:55
Actually, Logback is involved in wrapping suppressed exceptions that lies outside of our reach.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2021-06-09 07:34
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-06-09 07:34 UTC
Labels: status: waiting-for-feedback
