### ISSUE TITLE
CommandArgs StringArgument writeString method not support Chinese

### ISSUE THREAD

**Issue by zmmSh** [lettuce-io/lettuce-core#999] opened 2019-03-12 03:50 UTC
#### Current Behavior
There are some chinese annotation in my code 
when i eval() lua script the first time,the encode method went wrong

#### Input Code

```lua
local subDeviceListJsonStr = "[]"
-- 如果subDeviceList不为空则保存子设备列表
if next(subDeviceList) then
    -- 把子设备列表存于gwSession中
    subDeviceListJsonStr = cjson.encode(subDeviceList)
end
redis.call("hset",deviceKey,"subDeviceList",subDeviceListJsonStr)
```

#### Expected behavior/code

But the fact is:(I run wireshark find this)

local subDeviceListJsonStr = "[]"
-- subDeviceList
:zÝXP¾h
if next(subDeviceList) then
    -- P¾hXgwSession-
    subDeviceListJsonStr = cjson.encode(subDeviceList)
end

redis error is 
ERR Error compiling script (new function): user_script:34: unexpected symbol near ':'
the ':' which you can see above after subDeviceList （the right thing is a chinese word,but it went wrong）

#### Environment

- Lettuce version(s): [e.g. 5.0.5.RELEASE]
- Redis version: [e.g. 5.0.3]

#### Possible Solution
io.lettuce.core.protocol.CommandArgs.StringArgument#writeString line 586

                target.writeByte((byte) value.charAt(i));

the （byte）cast could cause code mess！

**Comment by mp911de** [comment] 2019-03-12 08:34
Please provide the following additional information:

* Which version of Lettuce are you using
* How do you invoke the script? The report contains Lua script but not the Java code that is used to invoke the script.

**Comment by zmmSh** [comment] 2019-03-12 08:45
1.version
<dependency>
      <groupId>io.lettuce</groupId>
      <artifactId>lettuce-core</artifactId>
      <version>5.0.5.RELEASE</version>
      <scope>compile</scope>
    </dependency>
2.invoke
```
@Component
@Getter
public class RedisLuaScriptHolder {
    private DefaultRedisScript refreshSession = new DefaultRedisScript();

    @PostConstruct
    public void init(){
        refreshSession.setScriptSource(new ResourceScriptSource(new ClassPathResource("luaScript/refreshSession.lua")));
    }
}
```
```
 public void refreshSession(String gwDeviceId,String gwVersion,String cacheVoListJson){
        ArrayList<String> keyList = Lists.newArrayList(getDeviceRedisKey(gwDeviceId,gwDeviceId));
        execute(redisLuaScriptHolder.getRefreshSession(),keyList,gwDeviceId,gwVersion,cacheVoListJson);
    }
```

```
private void execute(DefaultRedisScript script,List<String> keys, Object... args){
        RedisSerializer stringSerializer = redisTemplate.getStringSerializer();
        redisTemplate.execute(script,stringSerializer,stringSerializer,keys,args);
    }
```

**Comment by mp911de** [comment] 2019-03-12 10:52
This is a duplicate of #844. The bug was fixed with Lettuce 5.1 and newer. Care to upgrade to Lettuce 5.1.5 to check whether the issue is solved for you?

**Comment by mp911de** [comment] 2019-03-19 10:03
Any update on this issue?

**Comment by mp911de** [comment] 2019-03-26 07:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-03-26 07:32 UTC
Labels: status: duplicate, status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
