### ISSUE TITLE
DisconnectedEvent not fired on connection disruption

### ISSUE THREAD

**Issue by hero-sl** [lettuce-io/lettuce-core#533] opened 2017-05-04 08:48 UTC
I'm new to Lettuce and using 4.3.1 to connect to my Redis Sentinel.
I'm subscribed to the EventBus, I see initial events for Sentinel connection, and then actual Redis instance connection. And I'm also able to see if the node goes offline and Sentinel offering a new node.
But my problem is I'm not receiving a **DisconnectedEvent** upon a network outage. DefaultTimeout in client and ConnectTimeout in SocketOptions are set very small values. When I try to use a sync command when there's no connectivity to Redis, it throws a timeout exception. But still I'm missing the DisconnectedEvent. (KeepAlive and AutoReconnect is set to true) 
Any idea what's missing? Thanks in advance

**Comment by mp911de** [comment] 2017-05-09 14:54
I wasn't able to reproduce the issue. I connected to a Master/Slave setup and killed a node manually. With that test, I saw events emitted in the appropriate order:

```
ConnectedEvent [/192.168.100.1:50647 -> /192.168.100.129:6482]
ConnectionActivatedEvent [/192.168.100.1:50647 -> /192.168.100.129:6482]
```

… call `SHUTDOWN` on the server and then …

```
DisconnectedEvent [/192.168.100.1:50647 -> /192.168.100.129:6482]
ConnectionDeactivatedEvent [/192.168.100.1:50647 -> /192.168.100.129:6482]
```

Test code:

```java
RedisClient redisClient = RedisClient.create();

redisClient.getResources().eventBus().get().doOnNext(System.out::println).subscribe();

StatefulRedisMasterSlaveConnection<String, String> connection = MasterSlave.connect(redisClient, new Utf8StringCodec(),
        RedisURI.create("redis-sentinel://192.168.100.129:26380/0#mymaster"));
connection.setReadFrom(ReadFrom.MASTER_PREFERRED);

System.out.println("Connected to Redis");
while (true) {
    System.in.read();
    connection.async().ping().whenComplete((s, throwable) -> {

        System.out.println(s);
    });
}
```

**Comment by hero-sl** [comment] 2017-05-10 04:33
@mp911de Thanks for your time.
Yes, you are correct. I did the same with my remote sentinel setup and events were fired correctly.
But when I just disconnect my client from network (TCP close), I do not receive a DisconnectedEvent. 
I can still issue sync commands but those will result in timeouts.

**Comment by mp911de** [comment] 2017-05-11 06:02
I will give it another round of testing. I read your test case as network partition. The TCP channel tries to send commands and runs into a TCP retransmission timeout because the remote side isn't reachable.

**Comment by mp911de** [comment] 2018-06-16 17:42
Closing this one as we cannot reproduce the issue.

**Closed by mp911de** 2018-06-16 17:42 UTC
Labels: status: cannot-reproduce
