### ISSUE TITLE
Lettuce blocked in connecting to Redis in the case of concurrency

### ISSUE THREAD

**Issue by jbyjby1** [lettuce-io/lettuce-core#1269] opened 2020-04-16 05:29 UTC
## Bug Report

yes

#### Current Behavior

contidion:
maven import:
lettuce 5.2.2.Release
org.latencyutils.LatencyUtils 2.0.3
org.hdrhistogram.HdrHistogram 2.1.12

when I am running a simple test case -- use a threadpool to execute "basic usage"(https://lettuce.io/core/release/reference/#basic-usage). Every lettuce thread will block in 
`DefaultCommandLatencyCollector$DefaultPauseDetectorWrapper.getPauseDetector()`

There is a certain probability to meet this problem. But if I put a breakpoint in statement `instanceCounter.decrementAndGet()` in `DefaultCommandLatencyCollector$DefaultPauseDetectorWrapper.release()`, the problem will happen every time.

test case logic like below:

#### Input Code

<details>
<summary>Input Code</summary>

```java
// your code here;

Main.class:
public static void main(){
    //define a fixed thread pool
   ExecutorService es = Exectors.newFixedThreadPool(50);
   for (i = 0; i < 5000; i++){
        es.execute(new Runnable(){
            @Override
            public void run(){
                   if(RedisUtils.get("aaa") != null){
                        RedisUtils.del("aaa");
                   }else{
                        RedisUtils.set("aaa", "bbb");
                   }
             }
        })
   }
}

RedisUtils.class:
//just like the  "basic usage" in https://lettuce.io/core/release/reference/#basic-usage
//implement "get" "set" "del" method to get/set/delete redis key.

```

</details>

#### Environment

- Lettuce version(s): 5.2.2.RELEASE
- Redis version: 5.X
- maven import:
lettuce 5.2.2.Release
org.latencyutils.LatencyUtils 2.0.3
org.hdrhistogram.HdrHistogram 2.1.12

#### Possible Solution

As I see. DefaultCommandLatencyCollector$DefaultPauseDetectorWrapper.getPauseDetector() have a "while" statment. Maybe in the case of concurrency, the "DefaultCommandLatencyCollector$DefaultPauseDetectorWrapper.parseDetector" will be set to wrong value "null".
Maybe "DefaultCommandLatencyCollector$DefaultPauseDetectorWrapper.release()" method have a wrong invoke.

**Comment by mp911de** [comment] 2020-04-16 08:50
Please note that `ClientResources` are intended to be created once per JVM instance. Creating/shutting down `ClientResources` more than once indicates wrong API usage.

**Comment by jbyjby1** [comment] 2020-04-17 01:10
Thank you for your attention. Because someone on my side only read a part of the document, this problem occurred in the process of using lettuce. Now I know what to do, thank you.

**Comment by ackerL** [comment] 2020-04-24 14:59
Hi @mp911de ,
I encountered the similar problem in my code. I use thread pool and each thread will create a RedisClient instance, and will deal with create /shutdown issue separately.  So there may be multi `clientResource` in one JVM. 

Now I know that it is not recommended in lettuce. 

When I use  `Lettuce = 4.4.3.Final` version, there was the  similar exception: 

```
com.lambdaworks.redis.RedisCommandTimeoutException: Command timed out
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:118)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:96)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:61)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy40.info(Unknown Source)
	at com.amazon.redisnanny.provider.LettuceClient.getMonitorParameters(LettuceClient.java:82)
	at com.amazon.redisnanny.provider.ReplicationInfoCollector.lambda$getCurrentSnapshot$1(ReplicationInfoCollector.java:72)
```

And it may cause a block in the thread and all the `RedisCommands` do not work . 

```
"lettuce-epollEventLoop-592348-2" #2282594 daemon prio=5 os_prio=0 tid=0x00007f77ac28d000 nid=0x4af6 waiting for monitor entry [0x00007f776f8f9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1682)
	- waiting to lock <0x000000072956f370> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.lambdaworks.redis.metrics.DefaultCommandLatencyCollector.recordCommandLatency(DefaultCommandLatencyCollector.java:109)
	at com.lambdaworks.redis.protocol.CommandHandler.recordLatency(CommandHandler.java:342)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:327)
```



But the tricky is  the code work well  in the `Lettuce = 4.2.2.Final_snpPatch` version and it does not cause above exception though it runs for serveral months.

My doubt is why it works well with version `Lettuce = 4.2.2.Final_snpPatch` when there are multi `connectionResource` in one JVM.

Thanks for your time.

**Comment by mp911de** [comment] 2020-04-24 15:13
Thanks for your details.

What is version `4.2.2.Final_snpPatch`? Indeed, there seems an issue with synchronization. Thile multiple `ClientResource` instances are discouraged, we should not create a failure, therefore reopening this ticket.

**Comment by ackerL** [comment] 2020-04-24 15:31
Thx for your quick response. 

Sorry,  typo fix  `4.2.2.Final_snpPatch` ->  `4.2.2.Final`.

pls let me I add some background here.

Now the code with `4.2.2.Final` worked well for several months and not throw above exception although i use thread pool to create multi `clientResource`. 

The reason why i use thread pool is that i need to monitor `redis cluster` status, so i should connect to different host in `redis cluster`.  For efficiency,  thread pool is used in the code.

When i upgrade the version to `4.4.3.Final`, the exception occured and i see block in the thread.

So, is there practical way to use lettuce in this background?

**Comment by mp911de** [comment] 2020-04-24 15:39
Can you share the full thread dump for further investigation? I'm not able to reproduce the blocking issue. 

The `SimplePauseDetector` requires a bit of a dance to lazily create threads and to make sure that we only use a single instance in a JVM along with a proper shutdown.

Connecting asynchronously is fine with Lettuce, but I'd recommend using a single-node client that you keep reusing.

As a workaround, and if you don't require latencies, use `CommandLatencyCollector.disabled()` to avoid issues in the first place.

**Comment by ackerL** [comment] 2020-04-24 17:46
Thx for your suggestions.
In my opinion, one single-node can only hold one host.  it may be not suitable because there are many hosts in `redis cluster` and i need to pick some specific info seperately. it may not be very effective.

The following is some info that may help reproduce the question.

I pick major thread dump info here
```
"lettuce-epollEventLoop-592348-2" #2282594 daemon prio=5 os_prio=0 tid=0x00007f77ac28d000 nid=0x4af6 waiting for monitor entry [0x00007f776f8f9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1682)
	- waiting to lock <0x000000072956f370> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.lambdaworks.redis.metrics.DefaultCommandLatencyCollector.recordCommandLatency(DefaultCommandLatencyCollector.java:109)
	at com.lambdaworks.redis.protocol.CommandHandler.recordLatency(CommandHandler.java:342)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:327)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:276)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:260)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:749)

"lettuce-epollEventLoop-592348-1" #2282593 daemon prio=5 os_prio=0 tid=0x00007f77ac383000 nid=0x4af1 waiting on condition [0x00007f7766465000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.lambdaworks.redis.metrics.DefaultCommandLatencyCollector$DefaultPauseDetectorWrapper.getPauseDetector(DefaultCommandLatencyCollector.java:362)
	at com.lambdaworks.redis.metrics.DefaultCommandLatencyCollector.lambda$new$0(DefaultCommandLatencyCollector.java:83)
	at com.lambdaworks.redis.metrics.DefaultCommandLatencyCollector$$Lambda$38/10794757.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1664)
	- locked <0x000000072956f370> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.lambdaworks.redis.metrics.DefaultCommandLatencyCollector.recordCommandLatency(DefaultCommandLatencyCollector.java:109)
	at com.lambdaworks.redis.protocol.CommandHandler.recordLatency(CommandHandler.java:342)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:327)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:276)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:260)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:749)
```

Add the thread info in java process, It seems to have there epoll threads. 
```

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
22790 nobody    20   0 5422m 2.2g  31m S  0.3 14.8   2:02.65 SimplePauseDete
14816 nobody    20   0 5422m 2.2g  31m S  0.3 14.8   1:25.32 SimplePauseDete
18726 nobody    20   0 5422m 2.2g  31m S  0.3 14.8   0:26.73 lettuce-epollEv
18747 nobody    20   0 5422m 2.2g  31m S  0.3 14.8   0:27.02 lettuce-epollEv
19185 nobody    20   0 5422m 2.2g  31m R  0.3 14.8   0:26.11 lettuce-epollEv
19550 nobody    20   0 5422m 2.2g  31m S  0.3 14.8   0:00.21 RMI TCP Connect
```
I want to say the problem is not easy to reproduce. it cost several hours or days to reproduce in my test environment and it will definitely appear after i tried. 

Pls let me know if l lack some information.

**Comment by ackerL** [comment] 2020-04-25 14:40
Hi @mp911de,  i reproduced it again in my test environment. This time, it cost 2 hours to reproduce it. i use three schedule task and each task will try to create many `clientResources`. the timed interval is 1s. 

We can try to start multi threads(can use schedule task/thread pool) at the same time. Each thread we do `create client/connection/shutdown`. And it will be helpful to reproduce the problem.

**Comment by mp911de** [comment] 2020-04-25 15:51
Given the thread dump I have a clue how to address the issue.  It looks like the ConcurrentHashMap in conjunction with the lock in the wrapper cause the issue.

**Comment by ackerL** [comment] 2020-04-25 16:00
Yes, I agree with you. 

I compare the code between `4.4.3.Final`  and `4.2.2.Final`.
The code in `4.4.3.Final` use `computeIfAbsent` in method `recordCommandLatency` of class `DefaultCommandLatencyCollector` to instead traditional logic in version `4.2.2.Final`. 
And the issue does not appear in version `4.2.2.Final`. 

In the link [concurrentHashmap](https://stackoverflow.com/questions/57057467/)  also points the block.

**Comment by mp911de** [comment] 2020-04-27 09:07
That's fixed now.

**Closed** 2020-04-27 09:07 UTC
Labels: type: bug

**Comment by reed-sandberg** [comment] 2023-10-31 01:13
> Please note that `ClientResources` are intended to be created once per JVM instance. Creating/shutting down `ClientResources` more than once indicates wrong API usage.

@mp911de , is this still relevant for lettuce-core v6.2.x? I ask because I don't see much in the way of related docs in the Lettuce API, etc but am running into a similar issue (Lettuce is blocked connecting to redis) and am indeed creating/shutting down `ClientResources` more than once within a single JVM. I happened to see this thread while troubleshooting and researching the problem. While this would be an easy fix - just create a static member for the client resources, it is not easy to reproduce the issue, so would like to confirm this is a likely fix since the docs are not clear. If so, I might also suggest to clarify in the docs that this ClientResources object is not to be re-created.

For my use-case, we're detecting if redis commands are persistently failing, and if so, shutdown all existing connections and initiate all new connections from the seed hosts (clustered deployment) - kind of like a complete teardown/reset of all client connections.
