### ISSUE TITLE
waitForReplication runs on replicas

### ISSUE THREAD

**Issue by alec-bell** [lettuce-io/lettuce-core#1334] opened 2020-07-06 22:43 UTC
#### Error

```java
io.lettuce.core.RedisCommandExecutionException: ERR WAIT cannot be used with replica instances. Please also note that since Redis 4.0 if a replica is configured to be writable (which is not the default) writes to replicas are just local and are not propagated.
```

</details>

#### Method Call

```java
Long successfulReplicationCount = commands.waitForReplication(this.waitReplicas, this.waitTimeout);
```

</details>

#### Expected behavior

Should simply execute the Redis `WAIT` command on MASTER, but it appears to be trying to execute it on a replica instead. No failovers are occurring that would suggest a topology change. 

#### Environment

- Lettuce version(s): [e.g. 5.0.0.RELEASE, 4.2.2.Final]
- Redis version: [e.g. 4.0.9]
- AWS ElastiCache

**Comment by mp911de** [comment] 2020-07-09 09:53
This bug was fixed with Lettuce 5.0 already. 
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by alec-bell** [comment] 2020-07-16 20:58
Sorry for the delay - will update this with more information tomorrow.

**Comment by mp911de** [comment] 2020-07-28 09:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-07-28 09:23 UTC
Labels: status: waiting-for-feedback, type: bug

**Comment by weicliu** [comment] 2020-08-11 20:16
Hi, I'm seeing this issue as well. Would you please take a look?

#### Current Behavior

<details>
<summary>Stack trace</summary>

```java
io.lettuce.core.RedisCommandExecutionException: ERR WAIT cannot be used with replica instances. Please also note that since Redis 4.0 if a replica is configured to be writable (which is not the default) writes to replicas are just local and are not propagated.
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:135)
	at io.lettuce.core.ExceptionFactory.createExecutionException(ExceptionFactory.java:108)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
...
```

</details>

#### Input Code



<details>
<summary>Input Code</summary>

```java
commands.eval("script", ScriptOutputType.STATUS, scriptKeys, payload);
commands.waitForReplication(redisConfig.getReplicaCount(), WAIT_FOR_REPLICATION_TIMEOUT_MILLIS);

// configuration
RedisURI redisUri = RedisURI.Builder.redis(endpoint)
                                          .withPort(port)
                                          .withPassword(password)
                                          .withSsl(true)
                                          .build();

DefaultClientResources clientResources = DefaultClientResources.builder().dnsResolver(new DirContextDnsResolver()).build();

RedisClusterClient clusterClient = RedisClusterClient.create(clientResources, redisUri);

ClusterTopologyRefreshOptions topologyRefreshOptions =
        ClusterTopologyRefreshOptions.builder()
                                      .enablePeriodicRefresh(Duration.ofSeconds(this.redisConfig.getTopologyRefreshSeconds()))
                                      .enableAllAdaptiveRefreshTriggers()
                                      .build();
clusterClient.setOptions(ClusterClientOptions.builder().topologyRefreshOptions(topologyRefreshOptions).build());

StatefulRedisClusterConnection<String, String> connection = clusterClient.connect();
connection.setReadFrom(ReadFrom.MASTER);

RedisAdvancedClusterCommands<String, String> commands = connection.sync();
```

</details>

#### Expected behavior/code

It seems the wait is executed on replica instead of master. Note that I set ReadFrom.MASTER because otherwise eval is also executed on replica, throwing exceptions.

#### Environment

- Lettuce version(s): 5.2.2.RELEASE
- Redis version: 5.0.6
- AWS ElastiCache with cluster mode enabled (2 shards with 1 replica for each shard)

**Comment by mp911de** [comment] 2020-08-12 07:13
I think there's a general misconception here. `WAIT` is a command that does not have a key hence it does not qualify for key routing. Keys without a command get executed on the default connection which points to an arbitrary cluster node without considering its role. Issuing `WAIT` in Redis Cluster without specifying a node is pointless as you need to target a specific master node that holds the key/slot that you want to ensure gets replicated.

**Comment by weicliu** [comment] 2020-08-12 17:04
Thank you for your explanation Mark! Looks like we'll need manage a pool of connections for each individual master nodes and then issue `wait` on the specific one. I also found this discussion you had very helpful: https://groups.google.com/forum/m/#!topic/lettuce-redis-client-users/llH4sfkUj8k
