### ISSUE TITLE
smembers returns elements in non-deterministic order

### ISSUE THREAD

**Issue by alezandr** [lettuce-io/lettuce-core#823] opened 2018-07-26 10:49 UTC
I'm using Repositories from spring-data-redis, and I noticed that some of my tests against data repositories is unstable, sometimes they all passes, sometimes one of them fails. I found that CrudRepository.findAll() returns entities in order which is different from run to run. The problem is caused by unpredictable results ordering from call to smembers. I know that redis's set store do not guarantee ordering, but it must be at least deterministic, i.e. no changes in data -> no changes in order.

The order is changed in lettuce code, where the results are transformed to the byte[] and then they are stored in HashSet<byte[]>. Since byte[] does not care about hashCode, this brings to random position in hashset. The code where this behavior can be observed during debugging: io.lettuce.core.output.ValueSetOutput.

Possible solution: Probably byte[] must be replaced to ByteBuffer, because ByteBuffer has overridden method hashCode (i.e. it will stay the same until there's no changes in the data)

**Comment by mp911de** [comment] 2018-07-27 14:38
Good catch and thanks a lot for the bug report. The problem is indeed that `ValueSetOutput` uses a `HashSet` and not `LinkedHashSet`. `LinkedHashSet` has a predictable iteration order as it retains insertion order on unique elements.

**Comment by mp911de** [comment] 2018-07-27 14:47
That's fixed now for all maintained branches (4.x, 4.4.x, 5.0.x, 5.x/master).

**Closed by mp911de** 2018-07-27 14:47 UTC
Labels: type: bug, type: regression
