### ISSUE TITLE
xinfo api

### ISSUE THREAD

**Issue by tiiiyu** [lettuce-io/lettuce-core#995] opened 2019-03-08 03:23 UTC
hello,  Is xinfo api not supported in lettuce latest version?   Which version can it be added?
Thanks very much

**Comment by tiiiyu** [comment] 2019-03-08 03:32
I need it very much,Can it be added in next version?  Thanks...

**Comment by mp911de** [comment] 2019-03-08 06:15
Duplicate of #996

**Closed by mp911de** 2019-03-08 06:15 UTC
Labels: status: duplicate

**Comment by tiiiyu** [comment] 2019-03-08 08:03
Got ,Thanks
